openshift-kni/cnf-features-deploy

feature-configs/base/sctp/kustomization.yaml, feature-configs/base/sctp/sctp_module_mc.yaml, feature-configs/base/sctp/sctp_role.yaml, feature-configs/demo/sctp/kustomization.yaml, feature-configs/demo/sctp/sctp_machineconfigpool_patch.yaml
Kustomize example to deploy sctp.
It adds a new role to the nodes labelled as `node-role.kubernetes.io/worker-sctp: ""`
The choice of the node label to be used for the sctp pool is done via `kustomize`.
=> Sctp kustomize

hack/run-functests.sh
Our tests (and probably others we are going to import) depend on the fact that ginkgo is available.
We already download it, but it also has to be in the path
=> Set the $GOPATH/bin variable to path when running tests

hack/feature-wait.sh, hack/setup-test-cluster.sh
This is a temporary workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1792749
We pause / unpause machine config pools to have only one reboot.
=> Pause / unpause the machine pools to have one reboot only.

functests/sctp/sctp.go, functests/test_suite_test.go
Let's check if we have at least one available node and if not let's fail gracefully.
=> Check for having at least one node so tests won't panic.

functests/sctp/sctp.go, go.mod, go.sum, tools/sctptester/Dockerfile, tools/sctptester/main.go, vendor/github.com/ishidawataru/sctp/.gitignore, vendor/github.com/ishidawataru/sctp/.travis.yml, vendor/github.com/ishidawataru/sctp/GO_LICENSE, vendor/github.com/ishidawataru/sctp/LICENSE, vendor/github.com/ishidawataru/sctp/README.md, vendor/github.com/ishidawataru/sctp/ipsock_linux.go, vendor/github.com/ishidawataru/sctp/sctp.go, vendor/github.com/ishidawataru/sctp/sctp_linux.go, vendor/github.com/ishidawataru/sctp/sctp_unsupported.go, vendor/modules.txt
The sctp tests rely on a very simple executable that can act as server and client.
The sources were kept under the baremetal deploy repo but it make sense to have them near the tests.
In this PR I also remove the need for `quay.io/wcaban/net-toolbox:latest` as I add sctptool to the tester image itself.
The image is published on `quay.io/fpaoline`, but within CI context we can build it locally and use it. The tests rely on an env variable to provide an override.
=> Move the sctptester source code from baremetal deploy repo to here.

feature-configs/base/sctp/is_ready.sh, feature-configs/base/sctp/sctp_module_mc.yaml, feature-configs/e2e-gcp/sctp/sctp_module_mc_patch.yaml, functests/sctp/sctp.go, hack/setup-test-cluster.sh
This allows us to perform negative tests. By adding to the worker pool, we'll have
all no worker without the features installed.
Ideally, once the performance operator can be tied to a pool, we can use this same so we'll test all the features together.
This is also needed as https://github.com/openshift-kni/baremetal-deploy/pull/122 introduces negative tests.
=> Have a custom pool that matches two out of three nodes.

functests/utils/consts.go
These unused constants still point to worker-rt and worker roles. I'm just removing them so they don't get referenced again somewhere later on now that we're not converging on the worker-rt label.
=> remove unused references to worker-rt label

external-tests/clone_repo.sh, external-tests/performance/test.sh, hack/run-functests.sh, hack/setup-test-cluster.sh
This PR adds the wiring logic for download an external repo and execute its tests, and a makefile rule to do that.
It provides the performance operator as first example to do that.
=> Consume the performance operator tier 1 tests

hack/feature-deploy.sh, hack/feature-wait.sh, hack/setup-test-cluster.sh
That's more clear and reduces the "critical section" to the same file.
In this way we can run make setup-test-cluster and make features-deploy
without being forced to call make feature-wait.
=> Move the pause / unpause logic in feature_deploy.sh

feature-configs/demo/sriov/dpdk-network.yaml, feature-configs/demo/sriov/kustomization.yaml, feature-configs/demo/sriov/sriov-networknodepolicy-dpdk.yaml
This PR adds the requested yamls to configure the second interface in the demo environment to use vfio for dpdk.
=> Add network policy in demo for dpdk

openshift-ci/Dockerfile.tools
Fixes missing fedora RPM, see https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift-kni_cnf-features-deploy/40/pull-ci-openshift-kni-cnf-features-deploy-master-e2e-gcp/142/build-log.txt
=> Use gimme to install Go

openshift-ci/Dockerfile.tools
As we are now using gimme to provide the go binary, and the entry point is being executed via `/bin/sh`
=> Align PATH to the new go location

feature-configs/demo/sriov/sriov-networknodepolicy-dpdk.yaml, feature-configs/demo/sriov/sriov-networknodepolicy.yaml
This PR change the network config CR to work with mellanox
For mellanox cards the driver needs to by netdevice for both dpdk
workload or regular network card.
We also need to mark the RDMA as true for mellanox cards
=> Change the sriov network config in demo

openshift-ci/Dockerfile.tools
fixes:
```
ERROR: gcloud failed to load: invalid syntax (yaml_command_translator.py, line 241)
gcloud_main = _import_gcloud_main()
import googlecloudsdk.gcloud_main
from googlecloudsdk.command_lib.util.apis import yaml_command_translator
if self.spec.async:
SyntaxError: invalid syntax
This usually indicates corruption in your gcloud installation or problems with your Python interpreter.
Please verify that the following is the path to a working Python 2.7 executable:
/usr/bin/python3
If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 2.7 executable.
```
=> Added python2 for making gcloud client in CI happy

feature-configs/e2e-gcp/performance/operator_catalogsource.patch.yaml
the performance-addon-operator images are being mirrored to the quay.io/openshift-kni org. For the e2e tests, we can use the latest images to ensure we stay in sync. 
The other environments, like demo for instance, shouldn't use floating tags.
=> Use mirrored upstream repo for performance images

README.md
We can't have env variables as array as https://unix.stackexchange.com/questions/393091/unable-to-use-an-array-as-environment-variable so we rely on the string and we iterate over its values.
=> Change the FEATURES example as we expect it to be a string in README

hack/setup-test-cluster.sh
This PR patch the openshift network operator CRD.
By adding a network that request a dhcp ipam
the operator will deploy the dhcp daemonset in the cluster.
=> Patch the cluster network operator for dhcp

openshift-ci/Dockerfile.tools
The tests are executed via /bin/sh and there is no point in adding the alias to bashrc.
=> Remove kubectl alias and create a symlink to oc.

Makefile, feature-configs/demo/performance/kustomization.yaml, feature-configs/demo/ptp/kustomization.yaml, feature-configs/demo/sctp/kustomization.yaml, feature-configs/demo/sriov/kustomization.yaml, feature-configs/e2e-gcp/performance/kustomization.yaml, feature-configs/e2e-gcp/sctp/kustomization.yaml, hack/feature-deploy.sh, openshift-ci/Dockerfile.tools
Since `oc` comes with an older `kustomize` version, overrides need to use
`bases` instead `resources`
=> Replaced kustomize with oc apply -k

hack/setup-test-cluster.sh
Exclude nodes with 'master' label
=> Fix for labeling worker nodes

external-tests/clone_repo.sh, external-tests/origintests/test.sh, hack/run-functests.sh
This PR is to extract the ose tests binary from the ose tests image and then running the acceptance tests.
We can't consume the container as under CI, the tests are being executed in a pod and docker in docker require having privileges we don't have there.
So the not so pleasant way we do that is to use skopeo to fetch the image, look for the binary and then extract it.
=> Run the origin tests as part of the external tests

Makefile
Before it was begin created by the `kustomize` rule, now removed.
=> Always create TOOLS_DIR.

hack/feature-deploy.sh, hack/setup-test-cluster.sh
Removing the temporary workaround put in place for working around mcp issues when applying multiple mcs.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1792749
=> Remove pause / unpause workaround as CI is supposed to be fixed.

functests/sctp/sctp.go
This is to skip random "looking up service account sctptest/default: serviceaccount \"default\" not found" errors.
=> Check if the default service account is created for the test namespace.

functests/sctp/sctp.go
This removes skipping the tests as bz 1796157 is declared to be fixed in nightlies.
=> Remove the skip as the bz should be fixed.

feature-configs/demo/ptp/kustomization.yaml
This PR fixes the following issue
```
FEATURES_ENVIRONMENT=demo FEATURES="ptp" hack/feature-deploy.sh
[INFO] Deploying feature 'ptp' for environment 'demo'
error: couldn't make loader for ptpconfig-grandmaster.yaml: got file 'ptpconfig-grandmaster.yaml', but '/home/sscheink/Documents/GolangProjects/src/github.com/openshift-kni/cnf-features-deploy/feature-configs/demo/ptp/ptpconfig-grandmaster.yaml' must be a directory to be a root
```
After this PR: https://github.com/openshift-kni/cnf-features-deploy/pull/52
The `base` field is used only for folders.
In the kustomize version integrated with `oc` using the `-k` flag the resources field is for files only so we need to use both `base` and `resources` in the ptp configuration.
=> Fix demo ptp kustomization

functests/sctp/sctp.go
This is to remove flakes we are seeing in CI.
Sometimes, the first `checkForSctpReady` fails and I have the feeling is because it's the first time we use the tester image.
=> Make the wait for the checksctp pod longer.

Makefile, functests/dpdk/dpdk.go, functests/test_suite_test.go, functests/utils/pods/pods.go
The test checks whether DPDK stack works properly.
The test spins up a pod running appropriate container bundled with the DPDK utils and required tools. Then, it mounts appropriate bash/expect script as configmap and executes the script. The script starts up testpmd and uses expect to interact with the process. Afterward, the test parses output and makes a decision.
=> DPDK functests: adding a simple sanity test

feature-configs/demo/sriov/ipv6-network_attachment_defintion.yaml, feature-configs/demo/sriov/kustomization.yaml
This PR change the network attachment definition to use the sriov network CR.
Then the sriov operator is the one that creates the attachment.
This is the supported way to create sriov networks.
=> Fix the ipv6 network attachment

tools/buildingsctp/README.md, tools/buildingsctp/buildconfig.yaml, tools/buildingsctp/src/Dockerfile.sctp, tools/buildingsctp/src/sctp.c
Here we provide instructions and a working example on how to ship a ubi8 based image using OCP docker build strategy.
=> Add an example on how to build a UBI8 sctp application relying on OCP builds 

feature-configs/e2e-gcp/performance/performance_profile.patch.yaml
Set performance profile cpu's value for balanceIsolated as false to match CPU management tests.
After CPU management functional tests will be properly adapted to cover all aspects of this new value (added in https://github.com/openshift-kni/performance-addon-operators/pull/73) this could be changed accordingly
=> Adjust performance profile for CI

external-tests/clone_repo.sh, external-tests/origintests/test.sh, external-tests/performance/test.sh, external-tests/setup.sh
Also, make the version of the ose tests image configurable as well.
This is needed for handling 4.4 branching.
=> Make the branch of externally consumed tests configurable.

feature-configs/demo/dpdk/kustomization.yaml
This PR add a comment to the dpdk deployment feature.
For a dpdk workload to work we need huge-pages and cpu pinning, these two features are provided by the performance operator.
=> Add a comment to the dpdk deployment

feature-configs/demo/dpdk/kustomization.yaml
* Using resources allows to create overlays and still permits to deploy
it directly.
Signed-off-by: Sergi Jimenez <sjr@redhat.com>
=> fix: use resources for dpdk demo environment

tools/s2i-dpdk/test/test-app/test-template.sh
This PR add the --iova-mode=va flag.
This flag is must when running dpdk version 18.11 on a netdevice driver like mellanox.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1785933
=> Fix dpdk workload when using version 18.11

hack/run-functests.sh
Currently the `unit_report.xml` junit test result file of local tests will be overwritten by the performance external tests.
With this PR
- the filename of the local tests is modified so it won't be overwritten
- the junit file of external tests will be renamed after running in case they use `unit_report.xml`, in order to prevent multiple external tests overwriting their junit files.
@fedepaol
=> Use different junit filename than external tests.

external-tests/setup.sh, external-tests/sriov/test.sh
This will allow us to run openshift conformance tests against our deployment.
=> Consume the openshift sriov tests as external tests.

hack/setup-test-cluster.sh
Fails now because MCO added openAPIV3Schema to their CRDs
Signed-off-by: Marc Sluiter <msluiter@redhat.com>
=> Fixed MCP by removing null value

feature-configs/e2e-gcp/performance/performance_profile.patch.yaml
Reverts openshift-kni/cnf-features-deploy#109
RT kernel RPMs are back, see https://github.com/openshift-kni/performance-addon-operators/pull/136
=> Revert "Temporarily disable RT kernel"

feature-configs/base/performance/performance_profile.yaml, feature-configs/e2e-gcp/performance/performance_profile.patch.yaml
See https://github.com/openshift-kni/performance-addon-operators/pull/117
Fixes the last failing functest in periodic jobs
No backport needed for now
=> Added new numa.topologyPolicy to performance profile for CI

external-tests/setup.sh, external-tests/sriov/tests.sh
This commit allow us to run the sriov tests as external tests
cherry-pick from https://github.com/openshift-kni/cnf-features-deploy/pull/99
=> Add sriov tests for release 4.4

tools/s2i-dpdk/test/test-app/test-template.sh
```
./customtestpmd: unrecognized option '--no-mlockall'
EAL: Detected 80 lcore(s)
EAL: Detected 2 NUMA nodes
```
there is no `--no-mlockall` option in the testpmd binary
=> Fix dpdk test application

hack/README.md, hack/setup-test-cluster.sh
this is currently done by manually pre-labeling those with 'virtual-machine'
Signed-off-by: Yuval Kashtan <yuvalkashtan@gmail.com>
in our env this will be done by cluster deployment
note: I tried to use ironic introspection data, but that is included only for workers ...
=> fix ptp labels to skip virtual machines

functests/test_suite_test.go, go.mod, go.sum, vendor/kubevirt.io/qe-tools/LICENSE, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go, vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go, vendor/modules.txt
This tool allows us to export results of testing to polarion.
For example, running this command will start tests and create polarion_results.xml file that can be imported to polarion:
GOFLAGS=-mod=vendor ginkgo functests -- -polarion-execution=true -polarion-custom-plannedin=OCP_4_4_Code_Freeze -polarion-project-id=OSE -polarion-report-file=/tmp/polarion_results.xml --test-id-prefix=CNF_4_4_Compute
=> Add Polarion reporter

hack/run-functests.sh
This is needed because when run from a different directory it is missing it's go.mod without which ginkgo might be missing.
added a pushd and cd
for the popd to always execute I've added an exit trap
Signed-off-by: Yuval Kashtan <yuvalkashtan@gmail.com>
=> add correct cwd to run functests

external-tests/sriov/test.sh
Sriov tests have been moved to the sriov operator repository.
This PR changes the way we consume them, fetching from the new place.
=> Consume sriov tests from the sriov-operator repository.

functests/utils/nodes/nodes.go, hack/feature-deploy.sh
We are running into 2 issues after OCP has been rebased on k8s 1.18:
1. `ocp apply -f` fails to deploy ANY resource if ONE of them has an unknown kind. So apply all one by one, else our loop-until-succeed deployment doesn't work (profile can't be deployed because CRD doesn't exist in 1st iteration(s). This is a known and fixed bug in kubectl, so a temporary workaround only until the fix landed in OCP. See [0].
2. `oc rsh` aka `kubectl exec` write a deprecation note now to stderr:
`kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.`
So let's add add "--". But it didn't work with "oc rsh", so also switch to "oc exec -i"
[0] https://github.com/kubernetes/kubernetes/pull/89539
=> Fix deployment and tests

cnf-tests/Dockerfile, cnf-tests/Dockerfile.openshift
Performance tests need to use the oc binary. This pr is to provide it inside the cnf-tests image.
=> Include the oc binary in the cnf-tests image

Makefile, cnf-tests/Dockerfile, cnf-tests/Dockerfile.openshift, cnf-tests/mirror/mirror.go, cnf-tests/testimages/cnftests-utils/Dockerfile, cnf-tests/testimages/cnftests-utils/Dockerfile.openshift, cnf-tests/testimages/images.json, cnf-tests/testimages/sctptester/Dockerfile, cnf-tests/testimages/sctptester/Dockerfile.openshift, cnf-tests/testimages/sctptester/main.go, cnf-tests/testimages/stresser/Dockerfile, cnf-tests/testimages/stresser/Dockerfile.openshift, cnf-tests/testimages/stresser/main.go, functests/sctp/sctp.go, functests/utils/images/images.go, functests/utils/pods/pods.go, go.sum, hack/build-test-bin.sh
Make the local tests registry configurable.
Add local dockerfiles for container to be used.
Add a mirror command that returns the list of images we use, and
their corresponding version to a custom registry.
It can be used in pipe with oc image mirror with something like 
`docker run cnf-tests /usr/bin/mirror -registry targetregistry:5000/ | oc image mirror -f -`
=> Add support for disconnected environment through mirroring

go.mod, go.sum, vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go, vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/client/clients.go, vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/images/images.go, vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/mcps/mcps.go, vendor/modules.txt
This is to update the performance operator tests to latest image.
Specifically, we need it to take advantage of the change that uses tests image hosted on the quay.io/openshift-kni org.
=> Update performance tests to the version that use images hosted on quay

go.mod, go.sum, vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/client/clients.go, vendor/modules.txt
We need to bump it up as the previous version did exit on init if kubeconfig was not valid.
=> Update the version of performance tests to enable dryRun

cnf-tests/Dockerfile, cnf-tests/Dockerfile.openshift, hack/build-test-bin.sh
This allows the make test-bin to succeed from a download, outside a git checkout.
=> Bump the git sha only in dockerfile, externally to make test-bin.

feature-configs/deploy/performance/operator_catalogsource.yaml, feature-configs/deploy/performance/operator_operatorgroup.yaml, feature-configs/deploy/performance/operator_subscription.yaml
See https://bugzilla.redhat.com/show_bug.cgi?id=1830031 and https://github.com/openshift-kni/performance-addon-operators/pull/203
Also includes channel name fix of https://github.com/openshift-kni/cnf-features-deploy/pull/170
=> Fix CI by using shorter names

feature-configs/demo/dpdk/scc.yaml
This commit fix the dpdk deployment using the demo environment.
Before this fix we had this error:
```
error: no objects passed to apply
error: error parsing STDIN: error converting YAML to JSON: yaml: line 14: did not find expected alphabetic or numeric character
```
That was because when we run the workaround for the kustomize apply we remove the `'`.
=> Fix dpdk demo env deployment

cnf-tests/mirror/mirror.go, cnf-tests/test-run.sh
This pr enforces the addition of / to the registry name, both when mirroring and when running the tests.
Users will tend to add the base url without the separator.
=> Make sure the registry terminates with /

functests/dpdk/dpdk.go, functests/test_suite_test.go, functests/utils/namespaces/namespaces.go, functests/utils/reporter.go
The side effect of this is that dpdk tests are running in all the suites.
This needs to move the namespace on a different package.
=> Remove the dependency to dpdk on the reporter.

functests/utils/k8sreporter/example/main.go, functests/utils/k8sreporter/reporter.go
Having the error while looking at tests output is misleading. With this we put it 
Rename the node section to "dump" to be consistent to the other sections.
Align the example to the full list of CRDS we dump in tests.
=> Dump failures of crds on log output instead of stderror.

feature-configs/deploy/performance/operator_catalogsource.yaml, feature-configs/deploy/performance/operator_subscription.yaml
Note: 4.6.0 channel does not exist yet
=> Update perf operator deployment to correct 4.6 image

Makefile, hack/run-functests.sh
Do not compile if running from container because this is not needed, adding time, adding complex prerequisits
=> compile test-bin only if tests are running locally

functests/dpdk/dpdk.go, go.mod, go.sum, vendor/github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1/sriovnetworknodepolicy_types.go, vendor/github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1/sriovoperatorconfig_types.go, vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go, vendor/modules.txt
Here we vendor the latest sr-iov tests with configurable (and longer) timeouts and we apply the same logic to the dpdk test.
=> Add longer sriov waiting time

hack/feature-deploy.sh
This reverts commit 2329e48d
/cherrypick release-4.5
=> Revert "Temporary workaround for buggy oc apply"

cnf-tests/README.md
* Remove blank on variable assignment
* Remove extra double quotes on $TOKEN as its value already contains them and avoids errors from parsing dockerauth.json
=> fix: two steps on cnf-test image disconnected

cnf-tests/README.md
Signed-off-by: Sergi Jimenez <tripledes@users.noreply.github.com>
* For mirroring into the OCP registry, the default-dockercfg secret does
not allow to push returning unauthorized
* Use $REGISTRY instead of the undefined $HOST
=> fix: cnf-test use builder-dockercfg secret

hack/run-functests.sh
This should save some space on CI
=> Compress the report output when running make functests

functests/utils/reporter.go
Because of a copy/paste error we dump the policy twice.
=> Dump SriovNetworkNodeState.

hack/run-functests.sh
tests can run from container image, in which case, no need for go.
build-test-bin alread take care of making sure go is available for builds.
=> will not search for go in run-functests

functests/dpdk/dpdk.go
This avoids races when calling CleanSriov.
If we only delete them, CleanSriov may still list them and fail deleting them.
=> Wait until deletion of sriov networks / policies is complete.

functests/sctp/sctp.go, functests/test_suite_test.go, functests/utils/namespaces/namespaces.go
Change the logic on how items to delete are identified. We add a common prefix and puntually delete only sctp related items.
=> Clean up sctp leftovers.

tools/s2i-dpdk/test/test-app/build.sh
This commit add the "-e" to the make command.
This will load the container environment variables to find the right RTE_SDK
=> Fix test-pmd build

cnf-tests/README.md
Running the tests on a production cluster may have undesired effect. Here we try to document what all the various tests are doing to the cluster, to let the users know in advance.
=> Document the impact tests have on the cluster.

functests/sctp/sctp.go
There are cases where the connection takes up to 30 seconds to establish.
This causes the sctp tests to be flaky.
=> Make the SCTP client server connection waiting time longer.

functests/ptp/ptp.go, functests/utils/nodes/nodes.go
By setting NODES_SELECTOR, it's possible to limit the nodes impacted by the ptp tests.
In that case, the configuration is applied to a subset of nodes only.
=> PTP Tests: limit the nodes impacted by the tests using the optional selector

functests/dpdk/dpdk.go, functests/utils/nodes/nodes.go
This PR adds discovery of performance profile in dpdk tests.
If discovery mode is enabled, the tests will attempt to reuse an existing performance profile.
Following PR's will add discovery of sriov policy.
=> Add discovery of performance profile in dpdk tests

functests/dpdk/dpdk.go
This commit fix the sriov policy creation on the dpdk test.
We need to use the vendor ID an not the Device ID.
This also fix a bug when the performance policy doesn't exist
=> Fix the dpdk sriov policy

functests/dpdk/dpdk.go
This commit fix the sriov policy creation on the dpdk test.
We need to use the vendor ID an not the Device ID.
=> [release 4.5] Bug 1858849: Use right driver for dpdk 4.5

README.md, feature-configs/deploy/dpdk/post_deploy.sh, hack/feature-deploy.sh
If the registry is not ready when downloading the dpdk image the
s2i build running only once and the whole CNF deployment will wait for a timeout.
Retry and build dpdk image until compelte, with a timeout.
This script is not in the Makefile beacuse it doesnt follow the blueprint (kustomize) approach.
Signed-off-by: Sabina Aledort <saledort@redhat.com>
=> Add dpdk s2i build script for dpdk deployment

cnf-tests/README.md
Deleting the profile means that we need to wait until the nodes are rebooted.
Also, when running a new test session, we need to re-create the profile and wait
(again). Here we document how to skip this phase as the profile will remain the
same.
=> Add a note about how to not to clean the performance profile after the test is finished.

functests/ptp/ptp.go
If we run in "configuration" mode, we configure a master on one of the nodes of the cluster.
This ends up in flaky offsets given the infrastructure is not reliable.
=> Disable PTP offset test when not running in discovery mode.

feature-configs/deploy/dpdk/post_deploy.sh
When deploying dpdk it takes few seconds before the build is created.
Therefore, we should wait before checking if a build exist.
=> Add sleep time before checking last dpdk s2i build

feature-configs/deploy/dpdk/post_deploy.sh
If a dpdk build status is failed, delete it before creating a new build.
=> Delete dpdk failed build

cnf-tests/README.md, feature-configs/demo/performance/performance_profile.yaml, feature-configs/integration-base/performance/performance_profile.yaml, feature-configs/integration-kni1/performance/performance_profile_patch.yaml, feature-configs/integration-u08/performance/performance_profile_patch.yaml, feature-configs/integration-vms/performance/performance_profile_patch.yaml, feature-configs/integration-wl4-d17u01b05/performance/performance_profile_patch.yaml, feature-configs/typical-baremetal/performance/performance_profile.patch.yaml, functests/dpdk/dpdk.go, functests/utils/discovery/discovery.go, functests/utils/k8sreporter/example/main.go, functests/utils/reporter.go
For 4.6, performance profile api is becoming stable, introducing v1.
Update everything to consume the stable API, which is also more
future proof.
Signed-off-by: Francesco Romani <fromani@redhat.com>
=> performance profile: consume api v1

feature-configs/typical-baremetal/performance/performance_profile.patch.yaml
The latency test requires additional kernel arguments to
be configured and to have sequency of the isolated CPUs
that the CPU manager can allocate for the pod.
=> Update the CI performance profile

functests/dpdk/dpdk.go
cherry-pick base on https://github.com/openshift-kni/cnf-features-deploy/pull/291
This commit fix the CPU set test.
The CPU list can contain multiple lists
example output:
```
NUMA node0 CPU(s):   0-19,40-59
NUMA node1 CPU(s):   20-39,60-79
```
=> [release 4.5] Fix the CPU set test

functests/dpdk/dpdk.go
cherry-pick from https://github.com/openshift-kni/cnf-features-deploy/pull/290
This PR change to dpdk test to create a policy when the test are not in discovery mode to find and use the default router and use that interface.
I make this change because on the default network there is always
traffic for the testpmd application to process, this makes the test stable.
=> [release 4.5] Use default network for dpdk test

functests/dpdk/dpdk.go
This commit fix the dpdk test running on an openshift cluster
with ovn-kubernetes on the new shared gateway mode.
we search for the default gateway interface and if the name is `br-ex`
we locate the interface connected to the ovs bridge using the `bridge link`
command
=> support dpdk tests with ovn-kubernetes share gw

functests/dpdk/dpdk.go
Example:
```
•! Panic [0.001 seconds]
dpdk
/remote-source/app/functests/dpdk/dpdk.go:88
Validate a DPDK workload running inside a pod
/remote-source/app/functests/dpdk/dpdk.go:155
Should forward and receive packets [It]
/remote-source/app/functests/dpdk/dpdk.go:156
Test Panicked
runtime error: invalid memory address or nil pointer dereference
/opt/rh/go-toolset-1.13/root/usr/lib/go-toolset-1.13-golang/src/runtime/panic.go:199
Full Stack Trace
github.com/openshift-kni/cnf-features-deploy/functests/dpdk.glob..func1.4.1()
/remote-source/app/functests/dpdk/dpdk.go:160 +0x93
github.com/openshift-kni/cnf-features-deploy/functests_test.TestTest(0xc0009ca900)
/remote-source/app/functests/test_suite_test.go:78 +0xf3
testing.tRunner(0xc0009ca900, 0x1a34cc0) …
```
=> Fix a nil pointer exception in the dpdk tests

tools/s2i-dpdk/Dockerfile
This change fix the error in build time for the s2i
```
error: build error: image "0" must specify a user that is numeric and within the range of allowed users
```
=> Fix the s2i build

feature-configs/deploy/performance/operator_subscription.yaml
On performance-operator side this happened in the PR
https://github.com/openshift-kni/performance-addon-operators/pull/344
The rename was needed to enable the Z-stream releases.
Signed-off-by: Francesco Romani <fromani@redhat.com>
=> deploy: fix channel rename

feature-configs/typical-baremetal/performance/performance_profile.patch.yaml
When having a cluster with virtual machines as workers, there is not enough memory for all the pods
and the disruption budget will not allow us to drain the baremetal machine.
=> Reduce performance profile hugepages from 8 to 4

functests/sctp/sctp_sriov.go
It's not getting cleaned if sctp-sriov runs before the sriov tests, and may affect its
execution.
=> Clean the policy and wait after the sctp-sriov test.

functests/utils/k8sreporter/reporter.go
Due to a bug, now all the pods are dumped many times, one for each pod available. We need to dump the list only once.
=> Dump single pod instead of pod list.

functests/sctp/sctp_sriov.go
Now that we only look at the status, we must ensure the resources are there.
=> Wait longer for resources to be available in sctp-sriov integration test

functests/sctp/sctp.go
In regular mode, we ask the behaviour to be defined from outside, but discovery mode is supposed
to inspect the cluster & skip instead of failing.
=> Skip the negative test if no nodes without sctp are available.

cnf-tests/test-run.sh
If discovery mode is enabled, it does not make sense to run any kind of configuration.
=> Skip setup if in discovery mode.

functests/test_suite_test.go
If performance clean function deletes the profile, even if it is the discovered one.
When running in discovery mode we want to make sure that the configuration of the cluster is not impacted.
=> Don't call performance clean if discovery mode is enabled.

go.mod, go.sum, vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go, vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/profiles/profiles.go, vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/utils.go, vendor/modules.txt
This version of tests ignore the output of oc on stderr unless the command returns an error, making
them compatible with the 4.5 version. The new CI based on multistep relies on the e2e workflow which
ships the 4.5 version of oc.
=> Update performance tests.

cnf-tests/README.md, functests/dpdk/dpdk.go
- In doc, make isolated and reserved not to overlap
- In doc & code: reduce the amount of hugepages. 4 is fine if a profile is found, so it's enough
to make dpdk work.
=> DPDK performance profile changes in doc / code.

functests/sctp/sctp.go, validationsuite/cluster/validation.go
There are some configurations where we only apply kernel arguments to machine configs.
In this case, the config section is empty and this makes the checks performed by sctp to fail.
=> Bug 1889275: When looking for the mc that enables sctp, skip if the raw config is empty

feature-configs/demo/xt_u32/kustomization.yaml, feature-configs/deploy/xt_u32/is_ready.sh, feature-configs/deploy/xt_u32/kustomization.yaml, feature-configs/deploy/xt_u32/xt_u32_module_mc.yaml, feature-configs/typical-baremetal/xt_u32/kustomization.yaml
xt_u32 is an iptables filtering kernel module.
The module was removed from RHEL8 and brought back to life becasue there are some important CNFs that relay upon it. It will be removed again for RHEL9,
but till then we wanna have a documented way of enabling it and attesting it works.
This is basically a copy of sctp feature (minus the unblacklisting which isnt required for xt_u32).
=> add xt_u32 as a feature

cnf-tests/README.md
Signed-off-by: Alberto Losada <alosadag@redhat.com>
Fixing a broken link in the documentation.
=> Fixed link to detailed list of cnf-tests

feature-configs/deploy/performance/operator_catalogsource.yaml
=> [release-4.6] Use index image instead of registry one to deploy PAO

functests/utils/discovery/discovery.go
When the discovery of sriov on one nodes of the cluster fails, the discovery function fails even when the discovery is performed successfully on at least one node.
=> Fix dpdk discovery mode.

feature-configs/deploy/performance/operator-namespace.yaml, feature-configs/deploy/performance/operator_operatorgroup.yaml, feature-configs/deploy/performance/operator_subscription.yaml, functests/dpdk/dpdk.go, functests/sctp/sctp_sriov.go, functests/utils/consts.go, functests/utils/namespaces/namespaces.go, functests/utils/reporter.go, go.mod, go.sum, validationsuite/cluster/validation.go, vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/consts.go, vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/namespaces/namespaces.go, vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/pods/pods.go, vendor/modules.txt
When installing an operator, the user can choose the namespace where to install it. The common behaviour is to use the one described in the docs, which is different for the one being used here.
On top of that, we are making the namespaces related to the other two operators (ptp, sriov) configurable for what is related to the tests implemented here.
The deploy part is updated to create and use the new default namespace for PAO.
We update the pao test to contain the fix.
=> Bug 1896798: Make it possible to override the namespace used by the operators, plus switch the pao default one.

feature-configs/demo/dpdk/deployment-config.yaml, functests/dpdk/dpdk.go
This commit add the NET_RAW capability that was removed
from the default list of capabilities as part of
https://access.redhat.com/security/cve/cve-2020-14386
=> Fix Mellanox DPDK issue

Makefile, cnf-tests/Dockerfile, cnf-tests/README.md, cnf-tests/TESTLIST.md, cnf-tests/docgen/e2e.json, cnf-tests/docgen/validation.json, feature-configs/deploy/xt_u32/is_ready.sh, functests/test_suite_test.go, functests/utils/namespaces/namespaces.go, functests/utils/reporter.go, functests/xt_u32/xt_u32.go, validationsuite/cluster/validation.go
xt_u32 is an iptables filtering kernel module.
This test is crearing a pod that has the xt_u32 module enbaled in it,
then running an iptable rule inside it to test the module works.
=> Add xt_u32 feature tests to the test suite.

feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/disable-chronyd.yaml, feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/kustomization.yaml, feature-configs/demo/ptp/disable-chronyd.yaml, feature-configs/demo/ptp/kustomization.yaml
This commit add a machine config to disable chronyd under the ptp kustomize
=> Disable chronyd when using ptp

functests/dpdk/dpdk.go
We are now running an extra pod and we need to allow pages for that too.
=> DPDK: Change the hugepages number from 4 to 5

feature-configs/deploy/ptp/01_namespace.yaml
run-level 1 is dangerous from security perspective
and seemingly ptp no longer require it
https://docs.openshift.com/container-platform/4.6/networking/multiple_networks/configuring-ptp.html#install-ptp-operator-cli_configuring-ptp
=> revert ptp namespace to default run-level

cnf-tests/docgen/cmd/generate.go
problem was caused because the sort happened before cleaning the string
https://github.com/openshift-kni/cnf-features-deploy/issues/373
=> Fix docgen shuffling order of markdown everytime

Makefile, cnf-tests/TESTLIST.md, hack/compare-gen-md.sh
Adds the ability to check if the docs(TESTLIST.md) are up to date with the tests.
Should not be merged before https://github.com/openshift-kni/cnf-features-deploy/pull/395.
=> Added to ci-job comparison of newly generated docs to existing docs

configsuite/test_suite_test.go, functests/test_suite_test.go, functests/utils/k8sreporter/example/main.go, functests/utils/k8sreporter/reporter.go, functests/utils/namespaces/namespaces.go, functests/utils/reporter.go, go.mod, go.sum, hack/run-functests.sh, validationsuite/test_suite_test.go, vendor/github.com/kennygrant/sanitize/.gitignore, vendor/github.com/kennygrant/sanitize/.travis.yml, vendor/github.com/kennygrant/sanitize/LICENSE, vendor/github.com/kennygrant/sanitize/README.md, vendor/github.com/kennygrant/sanitize/sanitize.go, vendor/modules.txt
Currently the reporter dumps all of the logs to a single file,
We want it to log in a more organized way:
* Create a folder for each failed test with logs for:
* Nodes
* CRs
* Pods specs by namespace
* Pods logs by namespace
=> Change custom reporter logs layout

feature-configs/demo/ptp/ptpconfig-grandmaster.yaml, feature-configs/demo/ptp/ptpconfig-slave.yaml, functests/ptp/ptp.go
This commit changes the transport for ptp tests and demo yamls
to L2 ethernet.
This is the telco prefer transport so we should use it and it will
allow the test also to run on interfaces that don't have an ip address
allocated.
=> Use Ethernet as the trasport layer for ptp tests

Makefile, cnf-tests/test-run.sh, hack/run-functests.sh
The reference layers (i.e. the ran overlays) require capabilities not available on cloud providers. However, deploying the manifests without errors and checking that the required operators are running has validation value. With this, we add a new validate-on-ci rule that runs only the validation suite.
=> Makefile rule: deploy and validate only

feature-configs/cn-ran-overlays/ran-profile/site.1.fqdn/networks/sriov-network-node-policy-dpdk-mh.yaml
The node-selector node-role.kubernetes.io/worker-cnf is currently also used,
meaning that nodes need both labels, which is inconsistent with documentation,
which only specifies node-role.kubernetes.io/worker-cnf.
=> Remove node-selector network-sriov.capable: "true" for ran profile

cnf-tests/testsuites/pkg/k8sreporter/reporter.go
Currently we dump logs only iterating the containers in a pod. Here we
also take the logs from init containers.
=> Kubernetes reporter: dump also the init containers

cnf-tests/Dockerfile, cnf-tests/Dockerfile.openshift
This commit add the pmc binary into the container so we can use it later for ptp testing
=> Add linuxptp package to have pmc command inside cnf-test container

Makefile, cnf-tests/testsuites/e2esuite/vrf/vrf.go
We are running the tests with priviledged pod, here we do what a user
would do, assigning the least permissions which are NET_RAW
=> VRF Test: reduce the permissions needed to use a VRF

feature-configs/deploy/sriov-fec/subscription.yaml
This commit continue the work on https://github.com/openshift-kni/cnf-features-deploy/pull/471
We need to allow the sriov-fec to also use the same custom-catalog
=> Change the sriov-fec catalogSource to the custom one

OWNERS_ALIASES, feature-configs/5g-ref-nw/OWNERS, feature-configs/cn-ran-overlays/OWNERS
This adds the RAN team members to the default 'reviewers' group, and also defines a new 'RAN-approver' alias, which will have approver access to both feature-configs/cn-ran-overlays and the forthcoming feature-configs/5g-ref-nw DU profile areas.
=> Configure RAN owners

feature-configs/5g-ref-nw/README.md
This commit is fixing a broken link in 5g-ref-nw main README.md
/assign @lack
=> Fix image link in main 5G README

OWNERS_ALIASES, ztp/OWNERS
This defines a ZTP approver alias as well as granting approver access to
feature-configs/ZTP for that alias.
=> Add approvers to the forthcoming ZTP profile area

ztp/ztp-playbooks/install-ai-operator/playbook.yml, ztp/ztp-playbooks/install-ai-operator/roles/expose-endpoints/tasks/main.yml, ztp/ztp-playbooks/install-ai-operator/roles/expose-endpoints/templates/create_haproxy.sh.j2
Run haproxy on the disconnecter vm, to expose
the cloud internal endpoints.
Signed-off-by: Yolanda Robla <yroblamo@redhat.com>
=> Add tasks for exposing endpoints

ztp/ztp-playbooks/install-ai-operator/roles/expose-endpoints/tasks/main.yml, ztp/ztp-playbooks/install-ai-operator/roles/install-assisted-installer/templates/ai_secrets.yaml.j2
The dockerconfigjson secret needs to be embedded into
single quotes, not double. Also, fix a hardcoded
name when exposing the endpoints.
Signed-off-by: Yolanda Robla <yroblamo@redhat.com>
=> Fix remaining issues on installation

ztp/ztp-ran-policy-generator/kustomize/plugin/ranPolicyGenerator/v1/ranpolicygenerator/policyGen/policyBuilder.go, ztp/ztp-ran-policy-generator/kustomize/plugin/ranPolicyGenerator/v1/ranpolicygenerator/policyGen/policyHelper.go, ztp/ztp-ran-policy-generator/kustomize/plugin/ranPolicyGenerator/v1/ranpolicygenerator/utils/utils.go, ztp/ztp-ran-policy-generator/ranGenTemplateExamples/common-ranGen.yaml, ztp/ztp-ran-policy-generator/ranGenTemplateExamples/group-du-ranGen.yaml, ztp/ztp-ran-policy-generator/ranGenTemplateExamples/group-du-sno-ranGen.yaml, ztp/ztp-ran-policy-generator/ranGenTemplateExamples/site-du-sno-1-ranGen.yaml, ztp/ztp-ran-policy-generator/ranGenTemplates/RanGenTemplate.yaml
Based on the ACM document at [0] the policy name must not exceed 63 chars.
- Adding policyName field to fix acm naming limitation
- Fix matchExpression struct
[0] https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html/security/governance-and-risk
=> Fix policy name exceeded allowed length

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
We need 5 hugepages for the tests so we configure 10 without specifying a NUMA node,
this way it will get spread equally 5 between the 2 default NUMAs to support any network devices on them
=> Add support for cards on secondary NUMA

feature-configs/5g-ref-nw/profile-base/du-dual/performance/kustomization.yaml, feature-configs/5g-ref-nw/profile-base/du-dual/performance/performance-profile.yaml, feature-configs/5g-ref-nw/profile-base/du-general/performance/kustomization.yaml, feature-configs/5g-ref-nw/profile-base/du-general/performance/performance-profile.yaml, feature-configs/5g-ref-nw/profile-base/du-single/performance/kustomization.yaml, feature-configs/5g-ref-nw/profile-base/du-single/performance/performance-profile.yaml
- add general performance profile to 5g reference
- add pci=realloc to ran-overlays
pci=realloc is needed on some BMs where BIOS fail to properly set BARs
=> improve du performance profile

cnf-tests/Dockerfile, cnf-tests/Dockerfile.openshift
iperf3 is needed for the ovs_qos tests
=> Add iperf3 to the Dockerfiles

cnf-tests/testsuites/e2esuite/vrf/vrf_sriov.go
VRF is not compatible with vfio device, hence we must set the right type
or the CNI plugin won't find the device created in the pod's namespace.
=> Bug 1956788: VRF SR-IOV integration: use netdevice type for vfs

hack/common.sh
There was a change in the openshift-ci the artifact location moved from /tmp/artifact to /log/artifact
=> Change the artifact location

ztp/source-policy-crs/PerformanceProfile.yaml
The PerformanceProfile needs to have the machineConfigPool and
userLevelNetworking set.
=> Add missing attributes to performance profile

feature-configs/typical-baremetal/performance/performance_profile.patch.yaml
dpdk test requires now at least 10 hugepages to work.
Done in favor of d/s as the typical baremetal performance profile is not used u/s.
=> Assign more hugepages for dpdk test

feature-configs/deploy/n3000/namespace.yaml, feature-configs/deploy/sriov-fec/namespace.yaml
This commit and the monitor annotation into the intel operators namespace so the monitor project(prometheus) will query the endpoints
=> Adding monitor label to the namespace

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go, cnf-tests/testsuites/pkg/nodes/nodes.go
Validates that the node picked is also configured by the performance profile.
Solves a problem where a node without hugepages is picked for the tests and pods
are stuck on pending
=> Validate sriov nodes are targeted by the performance profile

feature-configs/deploy/performance/operator-namespace.yaml, feature-configs/deploy/ptp/01_namespace.yaml, feature-configs/deploy/sriov/01-sriov-namespace.yaml, ztp/source-policy-crs/ClusterLogSubscription.yaml
Operator namespaces must be annotated to facilitate their
classification as management workload. This is related to workload
partitioning feature in OCP 4.8.
=> Add management workload annotations

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
The downward api test case has been disabled for discovery mode with the following code
if discovery.Enabled() {
Skip("Downward API test disabled for discovery mode")
}
=> Downward API disable Discovery Mode

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Ori found a sleep command which was used for testing.  Command was removed.
=> Removed sleep 900 from Downward API

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
This commit fix the hugepages dpdk test when the dpdk pod and the test pod
doesn't allocate hugepages from the same numa
=> Bug 1971274: Fix dpdk hugepages test

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
This commit extend the time we wait for the network attachment definition
to be created by the sriov operator from the sriov network CR
This is needed because after an SNO reboot it takes time for the net-attach-def webhook
to be available.
```
Internal error occurred: failed calling webhook \"multus-validating-config.k8s.io\": Post \"https://multus-admission-controller.openshift-multus.svc:443/validate?timeout=30s\": x509: certificate signed by unknown authority"
```
=> Fix dpdk test on SNO

cnf-tests/testsuites/e2esuite/ovs_qos/ovs_qos.go
This flag should stabilize results on upstream ci
=> Add --pacing-timer to iperf3 sender pod

cnf-tests/Dockerfile, cnf-tests/Dockerfile.openshift, cnf-tests/pod-utils/oslat-runner/main.go
We should align the version of the rt-test package between d/s and u/s.
=> Bug 1979554: Update the oslat version to 2.0

feature-configs/deploy/dpdk/build-config.yaml
This is needed as there was a change in dpdk and test-pmd
=> [release-4.8] Add a ref field to the dpdk build config

feature-configs/deploy/dpdk/build-config.yaml
This is needed as there was a change in dpdk and test-pmd
=> [release-4.6] Add a ref field to the dpdk build config

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go, cnf-tests/testsuites/e2esuite/sctp/sctp_sriov.go
This commit continue the work done in the sriov operator vendored tests
to support secure boot enabled environments.
=> Support running dpdk tests on secure boot environment

Makefile, README.md, hack/custom_rpms.sh
The custom RPMs script allows to install RPMs from an external source on a node.
One main use of this script is to install RT kernel on a node.
=> Add custom RPMs utility

hack/verify-commits.sh
the previous #540 was assuming CI normally clones github,
where infact, it have only the local master branch.
script now uses github APIs to get the right commit id.
(see commit msg for more info)
=> fix CI commit verifier (hack/verify-commits.sh)

ztp/source-cluster-crs/cluster-crs.yaml
This is needed to eliminate conflicting definitions with AI operator:
spec.provisioning: Forbidden: provisioning and clusterInstallRef cannot be set at the same time
=> ztp: remove provisioning from ClusterDeployment

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go, cnf-tests/testsuites/e2esuite/sctp/sctp_sriov.go, go.mod, go.sum, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/client/clients.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/cluster/cluster.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/pod/pod.go, vendor/modules.txt
This is a backport to allow cnf-test to run on secure-boot enabled environments
=> [release 4.8] Support secure boot in sriov and dpdk tests

.githooks/components.sh
the go.mod and sum is part of the vendor not cnf-test
=> infra: update the vendor list in the githooks

feature-configs/deploy/dpdk/build-config.yaml
This is needed as there was a change in dpdk and test-pmd
=> features: Add a ref field to the dpdk build config

feature-configs/deploy/n3000/catalogSource.yaml
The 4.8 redhat certified is not available yet so we need to use the 4.7 one
=> features: Bump the custom catalog for intel operator

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go, cnf-tests/testsuites/pkg/discovery/discovery.go
This commit also fix the hugepages test to support different
dpdk versions
=> cnf-test: Fix dpdk tests in discovery mode

feature-configs/deploy/performance/operator_catalogsource.yaml
This annotation is required for the index pod to be included in the
management partition.
=> Bug 1976243: Add partitioning annotation to  PAO CatalogSource.

validationsuite/cluster/validation.go
Two different variables shouldn't be named the same.
If they are named the same we can't compare between them.
Conflicts:
validationsuite/cluster/validation.go
=> Fix bug in cluster validation findMachineConfigPool function

ztp/source-policy-crs/ClusterLogOperGroup.yaml, ztp/source-policy-crs/ClusterLogSubscription.yaml, ztp/ztp-policy-generator/ranPolicyGenTempExamples/common-ranGen.yaml
PolicyGen needs one CR per file for updates.
Split ClusterLogging subscription from namespace/opergroup to allow update of channel.
=> ztp: Split CRs for policyGen

ztp/.gitignore
Add .gitignore file local to ztp directory.
It will allow us to ignore ztp build products and other
artifacts unwanted in the SCM without affecting any of the
parent directory objects
=> Add ztp local gitignore

ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/test-sno.yaml, ztp/source-crs/TunedPerformancePatch.yaml, ztp/ztp-policy-generator/testPolicyGenTemplate/site-du-sno-1-ranGen.yaml
When PAO generates a tuned profile, it takes the associated PAO policy
object name and prepends `openshift-node-performance-`.  This means that
because our examples have a PAO policy named
`openshift-node-performance-profile` the tuned performance patch needs
to refer to a tuned policy named
`openshift-node-performance-openshift-node-performance-profile`
=> bug 1999862: ztp: Ensure the tuned performance-patch matches the PAO policy name

ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/common-ranGen.yaml, ztp/source-crs/ReduceMonitoringFootprint.yaml, ztp/ztp-policy-generator/testPolicyGenTemplate/common-ranGen.yaml
Adds day-0 extra manifests disabling Grafana and alert manager. Required for SNO CPU footprint.
/cc @serngawy
/hold until tested
=> ztp: reduce sno monitoring footprint

ztp/source-crs/PerformanceProfile.yaml
Set kernel flags based on updated RT kernel. The
rcupdate.rcu_normal_after_boot=0 reduces contention on kernel locks
which improves reboot recovery time (reference BZ 1975356)
=> ztp: Update kernel args for performance

ztp/resource-generator/src/get-pre-sync-rv.sh
Fixes an issue discovered in scalability tests, where the
post-sync resource hook was failing due to the resource version being
expired.
The reason - the resource version number post-sync was comparing to
was initialized from config map resource version instead of its data.
/cc @serngawy
=> Bug 2000726: ztp: fix rv data name and path

ztp/source-crs/DisableSnoNetworkDiag.yaml, ztp/ztp-policy-generator/testPolicyGenTemplate/group-du-sno-ranGen.yaml
This commit disables network diagnostic pods in SNO,
reducing the number of pods by two
/cc @serngawy 
/hold (until tested with ACM)
=> ztp: disable SNO network diagnostics

ztp/ztp-policy-generator/testPolicyGenTemplate/group-du-ranGen.yaml, ztp/ztp-policy-generator/testPolicyGenTemplate/group-du-sno-ranGen.yaml
-  Fix increase policy name more than 63 chars     
=> ztp: Fix mc-accelerated-startup-policy-worker-du  policy name more than 63 chars

ztp/ztp-policy-generator/testSiteConfig/site1-sno-du.yaml, ztp/ztp-policy-generator/testSiteConfig/site2-sno-du.yaml, ztp/ztp-policy-generator/testSiteConfig/site2-standard-du.yaml
To deploy an standard cluster, api vip and ingress vip
are needed. And machine network needs to be removed.
Signed-off-by: Yolanda Robla <yroblamo@redhat.com>
=> ztp: fix sample for standard cluster

Makefile
The previous mechanism of disabling go modules for calling 'go vet'
doesn't work with go 1.16.  This changed mechanism works on developer
machines an also in the Github CI.
=> infra: fix our invocation of 'go vet' to run everywhere

ztp/gitops-subscriptions/argocd/deployment/argocd-openshift-gitops.yaml, ztp/gitops-subscriptions/argocd/deployment/kustomization.yaml
Ref to the issue is here https://issues.redhat.com/browse/GITOPS-1255
AND https://github.com/argoproj/argo-cd/issues/5505
=> ztp: Increase the gitOps controller pod memory

ztp/ran-crd/site-config-crd.yaml, ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/resources/cluster-crs.yaml, ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfig.go, ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfigBuilder.go
Users cannot choose which SDN plugin gets deployed via the SiteConfigs, they will always get OpenShiftSDN for IPv4 clusters and OVNKubernetes for IPv6 clusters.
This PR adds a new parameter inside the Cluster definitions named `networkType` that can be set to either "OVNKubernetes" or "OpenShiftSDN". If it's not set, by default OVNKubernetes will be used.
Example:
~~~yaml
<omitted>
clusters:
- clusterName: "mycluster1"
clusterType: "sno"
clusterProfile: "du"
clusterLabels:
group-du-sno: ""
common: true
sites : "westford-lab"
networkType: "OVNKubernetes"
<omitted>
~~~
I couldn't do something like this in the ACI yaml, it seems not possible to add a spec value and a string in the same line, that's why this modifies the CR inside the `getClusterCRs` function.
~~~
apiVersion: …
=> ztp: support networkType parametrization

ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/resources/cluster-crs.yaml
This fixes an issue when you already have a SiteConfig with some clusters deployed and you want to add a new cluster to that same SiteConfig. Without this change in the ClusterDeployment when the policygen tool renders the yaml files it will render the ClusterDeployments with `installed: false` that will cause a validation webhook from Hive to fail:
~~~sh
The ClusterDeployment "cnfdb1" is invalid: spec.installed: Invalid value: false: cannot make uninstalled once installed
Traceback (most recent call last):
File "watcher.py", line 100, in __init__
check=True)
File "/usr/lib64/python3.6/subprocess.py", line 438, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['oc', 'apply', '-f', '/tmp/tmpyjcaw7de/update/customResource/telco-5g-lab/cnfdb1.yaml']' returned …
=> ztp: fixes issue when adding more clusters to a siteconfig

ztp/resource-generator/src/get-pre-sync-rv.sh
This is a backport of the following fix:
ztp: Bug 2000726: fix rv data name and path
The post-sync resource hook was failing due to an expired resource version.
The reason: mistakenly initialized the resource RV from the config map RV
instead of its data.
Original commit: 8f962c4
=> ztp: Bug 2006035: Backport rv field jsonpath

ztp/source-crs/AcceleratorsNS.yaml, ztp/source-crs/AcceleratorsOperGroup.yaml, ztp/source-crs/AcceleratorsSubscription.yaml
Adds installation manifests for OpenNESS SR-IOV
Operator for Wireless FEC Accelerators.
The deployment is disabled by default (not added to
the DU policy generation template).
/cc @serngawy @lack @browsell
=> ztp: Add sriov-fec operator installation manifests

ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/group-du-sno-ranGen.yaml, ztp/source-crs/StorageLV.yaml, ztp/source-crs/StorageSubscription.yaml
Add LocalVolume provisioning manifest to source-crs.
Add an example of configuring a PersistentVolumeClaim
and using it from within a pod.
Bump operator to 4.9
/cc @serngawy @lack @browsell
=> ztp: add local volume provisioning

cnf-tests/mirror/images.json
images.json file is being used by the mirror.go program as a default value for mirroring the image version.
this PR updates the version written in the json from 4.8 to 4.9.
fix #761
=> cnf-tests: update image version in images.json

ztp/policygenerator/siteConfig/siteConfig.go, ztp/policygenerator/siteConfig/siteConfigBuilder.go, ztp/policygenerator/siteConfig/siteConfig_test.go
The SiteConfig CRD specifies default values for multiple fields. Ensure
that PolicyGen correctly handles these defaults when unmarshaling the
user CR.
=> Bug 2017547: ztp: Support SiteConfig default values

ztp/policygenerator/resources/acm-policy-du-platform-check-template.yaml
At the initial stage, this fixed inform policy is built to measure
some conditions that cannot be captured via the configuration policies
which are applied in the ztp pipeline. It should be used along with
configuration policies to determine if ztp of a cluster is completed
or not.
Jira: https://issues.redhat.com/browse/CNF-2959
=> ztp: Create a fixed ACM inform policy

cnf-tests/pod-utils/cyclictest-runner/main.go
It is recommended to run cyclictest with the --mlockall flag in order to lock current and future memory allocations to prevent being paged out.
Same done here:https://github.com/redhat-nfvpe/container-perf-tools/blob/f641d725ffa694b735561b837abc4219753c93d8/cyclictest/cmd.sh#L94
=> Bug 2009660:cnf-tests:add mlockall arg to cyclictest runner

cnf-tests/pod-utils/cyclictest-runner/main.go
Currently when running cyclictest we are passing -p 1 option while the recommended value is -p 95, so we changed it.
=> Bug 2009770:cnf-tests:run cyclictest using priority 95

cnf-tests/pod-utils/cyclictest-runner/main.go, cnf-tests/pod-utils/hwlatdetect-runner/main.go
All runners need to get the start delay argument as an integer value.
It makes more sense to get that arg as a Duration, but since oslat is already getting the start delay argument as an integer value, we prefer to keep on backward compatibility.
=> Bug 2006675:cnf-tests: cyclictest and hwlat recieve start delay arg as an integer

ztp/source-crs/PaoSubscriptionNS.yaml
The source CR PaoSubscriptionNS is included in pao-sub-policy policy.
Fix the issue in the source CR that causes the policy complaint status
to flip between Compliant and NonCompliant.
=> Fix the source CR PaoSubscriptionNS

ztp/source-crs/AmqInstance.yaml, ztp/source-crs/AmqSubscription.yaml, ztp/source-crs/AmqSubscriptionNS.yaml, ztp/source-crs/AmqSubscriptionOperGroup.yaml
Signed-off-by: Aneesh Puttur <aneeshputtur@gmail.com>
AMQ interconnect operator is a messaging router, required for PTP when the fast event publishing option is enabled in the ptp config.
This operator runs under its own namespace and allows event publisher's/consumer's to connect to transport hosts and produce/consume messages.
=> ztp: Add amq interconnect operator for ptp operator fast event requirement

ztp/source-crs/PtpOperatorConfigForEvent.yaml
Signed-off-by: Aneesh Puttur <aneeshputtur@gmail.com>
Adding PTP Operator Config policy to enable or disable fast events.
=> ztp:Add Ptp operator config to enable fast event

ztp/source-crs-builder/README.md
=> ztp: Fix typo in source-crs-builder README

feature-configs/deploy/gatekeeper/config.yaml
There is no need anymore to request a specific image.
Also the gatekeeper operator add a PDB and requesting 1 replica stuck the node from being drained because there is no other instance of the webhook deployment.
=> features: Fix gatekeeper deployment

cnf-tests/mirror/images.json
=> cnf-tests: bump image mirror to 4.10

Makefile
This will be enable again when backporting https://github.com/openshift-kni/cnf-features-deploy/pull/653
=> [release-4.8] disable gatekeeper tests

ztp/ran-crd/policy-gen-template-crd.yaml
ztp: add missing type for new boolean attribute 'wrapInPolicy'
=> ztp: add missing type for new boolean attribute 'wrapInPolicy'

ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/common-ranGen.yaml, ztp/policygenerator/policyGen/policyBuilder.go, ztp/policygenerator/policyGen/policyBuilder_test.go, ztp/policygenerator/policyGen/policyHelper.go, ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericNamespace.yaml, ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericOperatorGroup.yaml, ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericSubscription.yaml, ztp/policygenerator/utils/filesHandler.go, ztp/policygenerator/utils/utils.go, ztp/ran-crd/policy-gen-template-crd.yaml
Using a compliance type of "mustonlyhave" for Namespace CRs leads to
conflicts between the ACM policy governance engine and OLM. OLM updates
annotations and labels on operator namespaces which then get removed by
the "mustonlyhave" compliance type. This PR overrides complianceType on
Namespaces to "musthave".
=> Bug 2009233: ztp: Support complianceType override for CRs

ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/common-ranGen.yaml, ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/common-ranGen.yaml, ztp/ran-crd/policy-gen-template-ex.yaml, ztp/source-crs/PaoSubscription.yaml, ztp/source-crs/PaoSubscriptionCatalogSource.yaml
Updating source CR for PAO subscription to use redhat-operators
catalogsource where the operator is now located.
Leaving the PaoSubscriptionCatalogSource.yaml in place to avoid breaking
any deployments that are currently using it.
Signed-off-by: bartwensley <bwensley@redhat.com>
=> Bug 2019181: ztp: Update PAO subscription catalog source

ztp/source-crs/StorageLV.yaml
The extra separator "---" was causing PolicyGen to create an empty CR in
the corresponding policy. This empty CR kept the policy from going
compliant (ACM complains it is missing a "kind" attribute).
=> ztp: Remove extra CR separator from StorageLV

cnf-tests/testsuites/e2esuite/ovs_qos/ovs_qos.go
Printing some values as part of the tests will help
us debug failures, e.g knowing what was the rate limit
before the MachineConfig was deleted.
In addition, changing the names of the pod will make it
clear who is the sender/receiver.
Signed-off-by: Ori Braunshtein <obraunsh@redhat.com>
=> cnf-tests: Improve ovs_qos debuggability

ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/common-ranGen.yaml, ztp/policygenerator/policyGen/policyBuilder.go, ztp/policygenerator/policyGen/policyBuilder_test.go, ztp/policygenerator/policyGen/policyHelper.go, ztp/policygenerator/policyGenerator.go, ztp/policygenerator/utils/utils.go, ztp/ran-crd/policy-gen-template-crd.yaml, ztp/source-crs/ClusterLogNS.yaml, ztp/source-crs/ClusterLogOperGroup.yaml
Give the user control over the complianceType for all CRs in a
PolicyGenTemplate and change the default to "musthave". This ensures
that, by default, we realize the CPU savings on managed clusters,
but provide a path for users to choose "mustonlyhave" policies
when needed. The difference in CPU use for managing "mustonlyhave"
policies for the current feature set is ~0.8 cpu as measured by
the prometheus query:
```
sum(pod:container_cpu_usage:sum{namespace=~"openshift-logging|openshift-authentication-operator|openshift-kube-controller-manager|openshift-kube-apiserver|openshift-apiserver|open-cluster-management-agent|open-cluster-management-agent-addon"})
```
=> Bug 2009233: ztp: Support complianceType for full PGT

ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml, ztp/source-crs/PtpSubscription.yaml
Each CatalogSource incurs overhead in managing and checking the index
for updates. Use a single catalog source for all operators.
=> ztp: Use common CatalogSource for all subscriptions

tools/oot-driver/charts/iavf-driver-0.0.1/Dockerfile-driver.SRO, tools/oot-driver/charts/ice-driver-0.0.1/Dockerfile-driver.SRO
we need to remove the patch package install because in the CI
there is no access to the yum repos
error:
```
[1/2] STEP 15/22: RUN dnf install -y  make gcc patch cpio kmod
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
rhel-8-baseos                                   0.0  B/s |   0  B     00:00
Errors during downloading metadata for repository 'rhel-8-baseos':
- Curl error (6): Couldn't resolve host name for http://base-4-10-rhel8.ocp.svc/rhel-8-baseos/repodata/repomd.xml [Could not resolve host: base-4-10-rhel8.ocp.svc]
Error: Failed to download metadata for repo 'rhel-8-baseos': Cannot …
```
=> oot-driver: remove the patch package install

cnf-tests/testsuites/e2esuite/ptp/prometheus.go
This commit updates the label to find the prometheus pods in the openshift-monitoring namespace.
In OCP 4.10 they remove the `app: prometheus` label instead there is the `app.kubernetes.io/name=prometheus` label
=> cnf-tests: Fix ptp prometheus test

ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go, ztp/siteconfig-generator/siteConfig/testdata/role-templates/good.yaml.tmpl
For any templated MachineConfig, we need to replicate it for every role
in the cluster.
=> ztp: Add templated MC objects for every defined role

ztp/source-crs/PerformanceProfile.yaml
The current api version for PerformanceProfile is v2. 
=> ztp: Update PerformanceProfile source-cr to api v2

ztp/policygenerator/policyGen/policyBuilder.go, ztp/policygenerator/policyGen/policyBuilderOverlay_test.go, ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericCR.yaml, ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericDataCR.yaml
Users may supply additional fields/content which are not included in
the source-cr. This code allows the user content to be directly copied
into the generated CR.
=> Bug 2028881: ztp: Support for user content not in the source-cr

ztp/gitops-subscriptions/argocd/deployment/kustomization.yaml
Fix ArgoCD deployment kustomization.yaml to include the correct policies-app-project.yaml path.
=> ztp: fix ArgoCD deployment policies-app-project.yaml path

ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/ns.yaml
The labels will get created automatically as needed. Remove the
incorrect values.
=> ztp: Remove incorrect labels from reference PGT

cnf-tests/testsuites/e2esuite/ovs_qos/ovs_qos.go
Recently we're seeing 'Validate MCO removed egress/ingress'
tests flaking. From inspecting the logs the following
situation can happen in a test:
We delete the ingress MC, we see that the QoS is deleted from
the node, then we try to validate that the ingress limitation is
really deleted by creating the sender-receiver pods again.
Then we check that the traffic rate that arrives to the
receiver surpasses the ingressBitLimit that was set before.
This could be misleading, because if for some reason
the sender sends in a rate below what was set as the
ingressBitLimit, the test would fail thinking that
the ingress QoS still applies in the node.
Setting the limitMultiplier lower could significantly
reduce the chances of that happening.
Maybe TODO: redo how we check that the rate set by
the QoS …
=> cnf-tests: Fix ovs_qos flake

ztp/gitops-subscriptions/argocd/README.md
The repository configurations must be URLs that end in ".git". Make sure
the readme informs the users.
=> ztp: Update Readme with repo configuration details

ztp/ran-crd/site-config-crd.yaml, ztp/siteconfig-generator/siteConfig/clusterCRs.go, ztp/siteconfig-generator/siteConfig/siteConfig.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
This PR adds support for configuring specific OCP versions for specific clusters within the site. If cluster does not define specific OCP release, the OCP release specified at site level will be used. This is useful when you want to deploy clusters with different OCP releases in the same site, i.e: OCP 4.8.X and OCP 4.9.X. As of today, without this feature you're required to have two different SiteConfigs even if they're the same "physical" site.
Signed-off-by: Mario Vazquez <mavazque@redhat.com>
=> ztp: Added support for defining OCP release per cluster

ztp/policygenerator/Makefile, ztp/siteconfig-generator/Makefile
This makes the fmt command match what out github ci requires, and makes
"all" the default target.
=> ztp: Fix policygenerator and siteconfig Makefiles

ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
=> ztp: Set entire 3node group profile for 'master' and not 'worker'

ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/source-crs/StorageLV.yaml
This makes the example in source-crs for StorageLV a bit more generic,
with a group policy example that looks more like what customers would
likely be doing.
=> ztp: Clean up StorageLV source-crs and SNO example

ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
The current reference PolicyGenTemplates (common, group, and test-sno) result in ~20 policies being created for the cluster. Managing this number of policies per cluster results in increased CPU use on the spoke cluster and scaling issues in the hub.
The work of this story is to reduce the number of policies created by using a common policy name for all policies in each of the common-ranGen.yaml, group-du-sno-ranGen.yaml, and test-sno.yaml files. 
Naming convention --> 
```
subscriptions-policy -- Containing all the Namespace, OperatorGroup and Subscription CRs
config-policy -- Containing the rest (OperatorHub, ImageContentSourcePolicy, ReduceMonitoring, etc)
```
-----------------
Before -->
```
[root@jumphost1 ~]# kubectl get policy -n common
NAME …
```
=> ztp: CNF-3661 Reduce number of policies

ztp/policygenerator/policyGen/policyBuilder.go, ztp/policygenerator/policyGen/policyBuilderOverlay_test.go, ztp/policygenerator/policyGen/policyBuilder_test.go, ztp/policygenerator/policyGen/policyHelper.go, ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericCR.yaml, ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericConfig.yaml, ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericConfigWithoutWave.yaml, ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericNamespace.yaml, ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericOperatorGroup.yaml, ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericSubscription.yaml, ztp/policygenerator/utils/utils.go
In order to make ClusterGroupUpgrade operator determine the policies
deploy order, 'ran.openshift.io/ztp-deploy-wave' annotation is added
to each policy according to the sourceCRs wave annotation.
See, https://github.com/openshift-kni/cnf-features-deploy/pull/862
Resources have different waves means they need to be applied in order, so
one policy cannot have resources with different waves. PolicyGen will raise
error if it happens.
The wave annotation can be overwritten/added via PGT. 
Jira: https://issues.redhat.com/browse/CNF-3635
/cc @imiller0 @serngawy @browsell
=> ztp: Add ztp-deploy-wave annotation in generated policy

feature-configs/deploy/gatekeeper/config.yaml
Use the default gatekeeper operator config in the tests.
The additional properties are optional and are not required.
Using a replica count of one will cause issues with the PodDisruptionBudget when we try to move the pod to a different node (https://bugzilla.redhat.com/2033440)
=> Bug 2034974: cnf-tests: Update gatekeeper config definition

hack/build-test-bin.sh, openshift-ci/Dockerfile.tools
This is needed to fix
```
STEP 10/15: RUN mkdir ~/bin &&     curl -sL -o /usr/local/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme &&     chmod +x /usr/local/bin/gimme &&     eval "$(gimme $GOVERSION)" &&     cat $GIMME_ENV >> $HOME/.bashrc &&     go get github.com/onsi/ginkgo/ginkgo &&     go get github.com/onsi/gomega/... &&     go get -u golang.org/x/lint/golint &&     export latest_oc_client_version=$(curl https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/ 2>/dev/null | grep -o \"openshift-client-linux-4.*tar.gz\" | tr -d \") &&     curl -JL https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/${latest_oc_client_version} -o oc.tar.gz &&     tar -xzvf oc.tar.gz &&     mv oc /usr/local/bin/oc &&     ln -s /usr/local/bin/oc …
```
=> [Release 4.7] Bump to use go mod in the openshift CI image build

ztp/source-crs/ClusterVersion.yaml
added upstream field in the clusterVerion CR to enable upgrade_graph configuration.
=> bug 2035318: added upstream field in the clusterVerion CR

feature-configs/deploy/gatekeeper/config.yaml
Use the default gatekeeper operator config in the tests.
The additional properties are optional and are not required.
Using a replica count of one will cause issues with the PodDisruptionBudget when we try to move the pod to a different node (https://bugzilla.redhat.com/2033440)
=> Bug 2033440: cnf-tests: Update gatekeeper config definition

openshift-ci/Dockerfile.tools
This is commit is needed because it's not possible to install as part of CI run
```
hack/lint.sh
/go/src/github.com/openshift-kni/cnf-features-deploy /go/src/github.com/openshift-kni/cnf-features-deploy
which: no golint in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.gimme/versions/go1.15.2.linux.amd64/bin:/go/bin:/go/bin)
Downloading golint tool
go: writing go.mod cache: mkdir /go/pkg: permission denied
go: writing go.mod cache: mkdir /go/pkg: permission denied
go: writing go.mod cache: mkdir /go/pkg: permission denied
go: writing go.mod cache: mkdir /go/pkg: permission denied
go: writing go.mod cache: mkdir /go/pkg: permission denied
go: writing go.mod cache: mkdir /go/pkg: permission denied
```
=> [release 4.7] install golint as part of the ci image

openshift-ci/Dockerfile.tools
```
which: no ginkgo in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.gimme/versions/go1.15.2.linux.amd64/bin:/go/bin:/go/bin:/go/bin:/go/bin)
Downloading ginkgo tool
go: downloading github.com/onsi/ginkgo v1.14.1
go: downloading golang.org/x/sys v0.0.0-20200625212154-ddb9806d33ae
go: downloading github.com/nxadm/tail v1.4.4
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: downloading github.com/fsnotify/fsnotify v1.4.9
Compiling functests...
Failed to compile functests:
go: inconsistent vendoring in /go/src/github.com/openshift-kni/cnf-features-deploy:
github.com/coreos/go-systemd@v0.0.0-20191104093116-d3cd4ed1dbcf: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
github.com/coreos/ignition@v0.35.0: is …
```
=> [release-4.7] install ginkgo as part of the openshift-ci dockerfile

cnf-tests/hack/build-test-bin.sh, cnf-tests/hack/lint.sh
=> cnf-tests: use go install instead of go get for golint package

cnf-tests/hack/build-test-bin.sh, cnf-tests/hack/lint.sh
=> [release 4.9] cnf-tests: use go install instead of go get for golint

hack/setup-build-index-image.sh
The quay.io/openshift/origin-metallb-frr image is now public.
=> infra: remove temp use of metallb frr image from ci registry

ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/group-du-sno-ranGen.yaml, ztp/source-crs/StorageLV.yaml
Add LocalVolume provisioning manifest to source-crs.
Add an example of configuring a PersistentVolumeClaim
and using it from within a pod.
Bump the operator image to 4.9
=> Bug 2021077: ztp: add local volume provisioning

ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/source-crs/PerformanceProfile.yaml, ztp/source-crs/TunedPerformancePatch.yaml
Performance profiles will generally apply to an entire group of machines, so let's model this.
=> ztp: move sno PerformanceProfile to group

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
example output:
```
++ cat /sys/fs/cgroup/cpuset/cpuset.cpus
+ export CPU=8,10,48,50
+ CPU=8,10,48,50
+ echo 8,10,48,50
8,10,48,50
+ echo 0000:3b:00.4
0000:3b:00.4
/bin/bash: line 29: warning: here-document at line 5 delimited by end-of-file (wanted `EOF')
+ cat
```
=> cnf-tests: fix the dpdk command indentation

tools/oot-driver/Makefile, tools/oot-driver/hack/create-special-resource.sh
This commit adds environment variable USE_DOCKER_IMAGE. Setting this environment variable replaces ImageStreamTag with DockerImage. 
Also changes tag of the oot-source-driver and removed the nested namespace. This allows us to use quay which doesn't support nested namespaces.
=> oot-driver: use DockerImage insted of ImageStreamTag for the driverContainer

ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/group-du-sno-ranGen.yaml, ztp/source-crs/StorageLV.yaml, ztp/source-crs/StorageSubscription.yaml
Add LocalVolume provisioning manifest to source-crs.
Add an example of configuring a PersistentVolumeClaim
and using it from within a pod.
Bump the operator image to 4.9
=> Bug 2002376: add local volume provisioning

ztp/source-crs/TunedPerformancePatch.yaml
By fixing the MCP alignment of the TunedPerformancePatch, masters in
standard clusters no longer get this unexpected configuration change.
=> Bug 2039981: ztp: Ensure standard cluster masters do not get stalld

ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml, ztp/source-crs/validatorCRs/informDuValidator.yaml
- ztp: ztp-done policy: Do not rely on specific node counts
- ztp: ztp-done policy: Ensure MCP degradedMachineCount == 0
- ztp: ztp-done policy: remove day-0 MachineConfig checks
- ztp: ztp-done policy: Check for the PAO MachineConfig in any MCP pool
- ztp: ztp-done policy: Remove any kube-apiserver checks
- ztp: ztp-done policy: Remove redundant PAO checks
- ztp: ztp-done policy: Remove redundant SRIOV checks
- ztp: ztp-done policy: Check PTP daemonset, not PTP deployment
- ztp: ztp-done policy: Check for the 50-nto-[worker|master] MachineConfig
=> Bug 2036990: Adjust ztp-done policy to work with multi-node clusters (plus 50-nto-* MC)

ztp/source-crs/ClusterLogForwarder.yaml
Because any openshift namespaces are silently dropped when the CR is
applied, there will be an inconsistency between the 'inform' policy and
the actual CR that can never be resolved, resulting in infinite
reconciliations.
Removing these ensures the applied CR matches the policy, and all will
be well.
/cc @imiller0
/hold for testing
=> Bug 2035015: ztp: Do not specify openshift namespaces in the ClusterLogForwarder CR

feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml, feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml
The ptp-operator has a new validating webhook which ensures that the
parameters in the PTP config are valid. The parameters used in CI don't
conform so CI fails. In specific the summary_interval and
logSyncInterval need to be set to the same value. The CI is being
updated to use -4 to match the "right" setting when "fast event
notification" is being used.
Validator:
https://github.com/openshift/ptp-operator/blob/master/api/v1/ptpconfig_webhook.go#L122-L124
=> features: Update PTP config to pass validations

tools/oot-driver/files/script/oot-driver
addresses known problems experienced with a partner, where reboot cycles leave podman containers resident.  the resident containers can go to 2048, and then it stops working for the partner.  this cleans them up and prevents an infrequent problem with iptables forwarding chains, when switching to the out-of-tree ice driver.
=> oot-driver: address lingering containers during reboot cycles

ztp/policygenerator/policyGen/policyHelper.go
Adding the actual wave numbers in question can help accelerate
troubleshooting when this error is encountered.
=> Bug 2037554: ztp: Add detail to error message for policy wave mis-match

ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/group-du-sno-ranGen.yaml, ztp/ztp-policy-generator/testPolicyGenTemplate/group-du-sno-ranGen.yaml
This is a back port of the fix in master branch that is missing in release-4.9
=> Bug 2041639: ztp: Add DisableSnoNetworkDiag to group-du-sno PolicyGenTemplate

ztp/policygenerator/policyGen/policyBuilder_test.go, ztp/policygenerator/policyGen/policyTemplate.go, ztp/policygenerator/utils/utils.go, ztp/ran-crd/policy-gen-template-crd.yaml
By changing the default in the tool, we ensure that users upgrading for
4.9 to 4.10 do not accidentally regenerate new enforce policies that
affect preexitsing clusters.  Likewise no action needs to be taken to
update existing common or group policies from older versions of the
tool (at least not to update the remediationAction part), minimizing the
number of manual actions a user needs to take when upgrading from 4.9 to
4.10.
/hold until the approach is decided (between this and #909)
=> Bug 2040791: ztp: Change the default PolicyGenerator to generate inform, not enforce policies

ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
This isn't needed for those platforms since all nodes are masters and
all nodes should want the PTP daemon running.  It's only critical for
standard clusters where we want to restrict PTP to workers only.  So
moving this simplifies things for users especially when upgrading from
4.9 to 4.10.
/cc @imiller0
=> ztp: Remove PtpOperatorConfig from SNO and 3node example PGTs

ztp/source-crs/StorageClass.yaml, ztp/source-crs/StorageLocalVolume.yaml
Existing customers use StorageLocalVolume rather than StorageLV. Add
symlink to allow either naming for this file for backwards
compatibility.
Some customers want to annotate a StorageClass as the default class. We
need to provide the StorageClass CR to allow this annotation (rather
than relying on its implicit creation along with the LocalVolume).
=> ztp: Support existing customer Storage config

go.mod, go.sum, vendor/github.com/metallb/metallb-operator/api/v1beta1/bgppeer_types.go, vendor/github.com/metallb/metallb-operator/api/v1beta1/bgppeer_webhook.go, vendor/github.com/metallb/metallb-operator/test/e2e/functional/tests/e2e.go, vendor/github.com/metallb/metallb-operator/test/e2e/metallb/metallb.go, vendor/modules.txt
The current metallb-operator commit id is not updated to main
causing CI failure.
This PR updates the MetalLB dependencies.
=> vendor: update MetalLB dependencies

ztp/gitops-subscriptions/argocd/README.md, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-validator-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-validator-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-validator-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml, ztp/policygenerator/policyGen/policyBuilder.go, ztp/policygenerator/policyGen/policyBuilder_test.go, ztp/policygenerator/policyGen/policyHelper.go, ztp/policygenerator/utils/utils.go, ztp/ran-crd/policy-gen-template-crd.yaml, ztp/source-crs/validatorCRs/informDuValidator.yaml
This commit includes the changes:
- Add bindingExcludedRules in PGT crd to support selecting clusters
which do not contain a label
- Update PGT examples and move validator policy to three new PGTs
corresponding to each type of cluster. The policy binds to the
group types and to the clusters without "ztp-done" label.
- Add a very large wave in validator source CR so validator policy
will be added at the end of policies in generated UOCR by TALO
=> Bug 2038253: ztp: Add bindingExcludedRules in PGT

ztp/gitops-subscriptions/argocd/README.md, ztp/gitops-subscriptions/argocd/Upgrade.md
The stranding of policy CRs due to policyName changes is not unique to
the upgrade process. Move the discussion to the README to make this more
clear and add reference from the upgrade documentation.
=> ztp: Move obsolete policy handling to README

ztp/source-crs/AcceleratorsSubscription.yaml, ztp/source-crs/AmqSubscription.yaml, ztp/source-crs/ClusterLogSubscription.yaml, ztp/source-crs/PaoSubscription.yaml, ztp/source-crs/PtpSubscription.yaml, ztp/source-crs/SriovSubscription.yaml, ztp/source-crs/StorageSubscription.yaml
Update each subscription CR with default "installPlanApproval"
set to Manual. With this configuration, installPlan will not be
installed automatically. TALO needs to find the right installPlan
and approve it.
Also add check of "AtLatestKnown" status in subscriptions, so
a new version of z-stream operator pushed to the registry will
cause the sub policy to be non-compliant then TALO is able to
know when to start upgrade and trigger upgrade.
Jira: https://issues.redhat.com/browse/CNF-4073
=> ztp: update default subscription CRs

ztp/source-crs/ImageRegistryConfig.yaml, ztp/source-crs/MachineConfigGeneric.yaml, ztp/source-crs/StoragePVC.yaml
A local registry is needed to cache container images and reduce the need
to pull images across a potentially slow link at system startup.
The Generic MachineConfig template is needed to support customer
specific tuning.
=> Bug 2050393: ztp: Add support for customer features

feature-configs/deploy/container-mount-namespace/container-private-mounts/mc-container-mount-namespace.yaml
There is a collision with a drop-in owned by MCO which also edits crio's
commandline by replacing ExecStart.  It turns out that the drop-in is
redundant with the environment variable that's already being set, so it
is safe for us to move our ExecStart later in the drop-in order and
simply replace the incompatible one.
=> features: Move our mount namespace execstart last

ztp/gitops-subscriptions/argocd/example/siteconfig/KlusterletAddonConfigOverride.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml, ztp/siteconfig-generator/siteConfig/clusterCRs.go, ztp/siteconfig-generator/siteConfig/siteConfig.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badAnnotation.yaml, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badName.yaml, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badNamespace.yaml, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride.yaml, ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride.yaml
While this does not cut over to go templates yet, it does refactor the
templating language we use to be more future-proof and forward-facing,
given that customers can now override these templates.
=> ztp: Update the SiteConfig template language to be more go-template compatible

ztp/source-crs/ClusterVersion.yaml
- remove desiredUpdate.force as the default value in CVO is false
- comment out desiredUpdate.version to allow to update the CV with
channel or(and) upstream only
- change the upstream value
=> Bug 2044339 ztp: update ClusterVersion source CR

ztp/policygenerator-kustomize-plugin/Makefile, ztp/resource-generator/Containerfile, ztp/resource-generator/Makefile, ztp/resource-generator/entrypoints/extract, ztp/siteconfig-generator-kustomize-plugin/Makefile
This removes the reliance on an external tarball so the Prow CI image
builder can build this for us.
It also simplifies the build process a lot, relying on the existing
makefiles in our source control to set up the kustomize plugin directory
structure rather than duplicating it, and removing a lot of extra
copying.
/hold until the master branch is 4.11; and until we do some more rigorous testing to make sure the results are compatible.
=> ztp: Redo the ContainerFile for ztp-site-generator

feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-grandmaster.yaml, feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-slave.yaml, feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml, feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml, ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml, ztp/policygenerator/testData/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml, ztp/policygenerator/testData/TestPtpConfig/templates/TestPtpConfig.yaml, ztp/source-crs/PtpConfigMaster.yaml, ztp/source-crs/PtpConfigSlave.yaml, ztp/source-crs/PtpConfigSlaveCvl.yaml
Required that summary_interval == logSyncInterval.
Set to default of 0, which should be changed to -4 events are configured
=> Bug 2040799: Set summary_interval and logSyncInterval to 0

ztp/source-crs/SriovFecClusterConfig.yaml
Including the Accelerators configuration. In the source-crs folders there are manifests to install the sriovFec operator but there is not configuration that can be applied and managed using ZTP.
Some telco 5G vRAN DU come with a FEC accelerator, mainly ACC100 which is the only supported one in OpenShift. Previously it was supported the N3000 as well.
The source-cr I am including contains:
* wave set to 10 as any other configuration manifest
* drainskip set to optional. It must be true if SNO
* bbDevConfig set to optional. This is the configuration that mainly differs between the FPGA managed by the CRD.
More information about configuration examples can be found here:
* [N3000](https://github.com/smart-edge-open/openshift-operator/blob/main/spec/openshift-sriov-fec-operator.md#sample-cr-for …
=> ztp: Adding SriovFec configuration 

ztp/resource-generator/Containerfile, ztp/resource-generator/Makefile, ztp/resource-generator/README.md, ztp/resource-generator/tools/patchImageReference.sh
The argocd deployment files refer to the upstream container images by
default. But downstream builds (or other special-purposw builds) need to
have a facility to override that internal reference. This is that
facility. Setting the IMAGE_REF build argument will patch any internal
references to that argument's value verbatim.
=> Bug 2047871: ztp: Add mechanism to patch inner container references at build

ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/resources/cluster-crs.yaml
Backport fix to include proxy settings in AgentClusterInstall. BZ
2057721.
=> Bug 2058630: ztp: Add proxy definition for AgentClusterInstall

ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfig.go, ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfigBuilder.go, ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfigBuilder_test.go
If the user does not supply any networking data in the nodeNetwork field
for a given node we should not generate the NMStateConfig CR. The
resultant NMStateConfig CR would be empty (no config/interfaces) and
causes the install to not complete (crash noted in infraenv). This patch
detects the empty nodeNetwork configuration in the user supplied
SiteConfig and suppresses the generation of NMStateConfig for that node.
=> Bug 2059663: ztp: Suppress NMStateConfig when nodeNetwork empty

ztp/resource-generator/Containerfile, ztp/resource-generator/Makefile, ztp/resource-generator/README.md, ztp/resource-generator/tools/patchImageReference.sh
The argocd deployment files refer to the upstream container images by
default. But downstream builds (or other special-purpose builds) need to
have a facility to override that internal reference. This is that
facility. Setting the IMAGE_REF build argument will patch any internal
references to that argument's value verbatim.
- Manual cherry-pick of #985 to release-4.10
=> Bug 2061782: ztp: Add mechanism to patch inner container references at build 

ztp/source-crs/ClusterVersion.yaml, ztp/source-crs/ClusterVersionUpgradeGraph.yaml
- remove ClusterVersionUpgradeGraph.yml from sourceCRs
- remove spec.desiredUpdate and status sections to be added in using PGT overlays
=> ztp: cleanup sourceCRs to be used for platform upgrade using PGT 

ztp/resource-generator/src/post-sync-entrypoint.sh, ztp/resource-generator/src/pre-sync-entrypoint.sh
Adds mutex lock causing all concurrent ArgoCD apps
in a given namespace to execute serially.
This addresses an issue happenning when a concurrent
application deletes and re-creates the resource version
configmap, corrupting the ongoing application data.
The lock is realized with a configmap, created
in the pre-sync hook and deleted just before the post-sync
hook exits. All concurrent pre-sync hooks will block
until the configmap is deleted
=> ztp: Bug 2021688: add mutex lock for ArgoCD apps

ztp/policygenerator/README.md, ztp/policygenerator/policyGen/policyBuilder_test.go, ztp/policygenerator/policyGen/policyHelper.go, ztp/source-crs/README.md
Strip the wave annotation from the built CR after the wave is
assigned to the policy.
=> Bug 2050391: ztp: delete wave annotation from the policy-wrapped CRs

cnf-tests/pod-utils/cyclictest-runner/main.go, cnf-tests/pod-utils/pkg/node/node.go
=> Bug 2051540: cnf-tests: filter main CPU's thread siblings under the cyclic test

ztp/policygenerator/policyGen/policyBuilder.go, ztp/policygenerator/policyGen/policyBuilderOverlay_test.go, ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericCR.yaml, ztp/policygenerator/utils/utils.go, ztp/ran-crd/policy-gen-template-crd.yaml, ztp/source-crs/ImageSignature.yaml
1. add configmap source-cr for image signature
2. support binaryData overlay in PGT
=> Bug 2062917: ztp: support adding configmap for image signature

ztp/resource-generator/Containerfile, ztp/resource-generator/Makefile, ztp/resource-generator/README.md, ztp/resource-generator/tools/patchImageReference.sh
The argocd deployment files refer to the upstream container images by
default. But downstream builds (or other special-purpose builds) need to
have a facility to override that internal reference. This is that
facility. Setting the IMAGE_REF build argument will patch any internal
references to that argument's value verbatim.
Manual cherry-pick of #1000
=> [release-4.9] ztp: Add mechanism to patch inner container references at build

ztp/source-crs/PaoSubscription.yaml, ztp/source-crs/PtpSubscription.yaml, ztp/source-crs/SriovSubscription.yaml, ztp/source-crs/StorageSubscription.yaml
Update subscriptions to point to the latest channel. In most cases this
is the "stable" channel, however Performance Addon Operator does not
have "stable" and is pointed to 4.10.
=> ztp: Update subscription channels to latest

ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/post-sync.yaml, ztp/gitops-subscriptions/argocd/resource-hook-example/siteconfig/post-sync.yaml
Adds an additional SyncFail annotation to the post-sync resource-hook
for cleaning up the sync lock mutex.
The hook run on the sync failure will process all the partially
synchronized resources and release the lock for the next attempt.
=> ztp: bug 2065713: remove sync lock on sync fail

ztp/policygenerator/policyGen/policyBuilder.go, ztp/policygenerator/policyGen/policyBuilder_test.go, ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericCRWithTrailingSeparators.yaml
When a source CR for policyGen contains a trailing "---" separator, the generated policy contains an empty object. ACM complains that this object does not have a "kind" attribute and the policy never goes compliant.
This commit checks that the decoded YAML objects are not null prior to appending them for further processing.
Signed-off-by: Sharat Akhoury sakhoury@redhat.com
/cc @imiller0 @lack
=> Bug 2026130: fix creation of empty policy objects

README.md
When replacing a regular kernel with a different regular kernel or a RT kernel with a different RT kernel there is no need to specify the removed packages.
=> docs: Update Custom RPMs info

ztp/gitops-subscriptions/argocd/SecureBoot.md, ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml, ztp/ran-crd/site-config-crd.yaml, ztp/source-crs/PerformanceProfile.yaml
Upstream doc secure boot. Includes instruction on how to use mokutil 
CNF-[4157](https://issues.redhat.com/browse/CNF-4157)
CNF-[3096](https://issues.redhat.com/browse/CNF-3096)
=> ztp: secure boot doc for ZTP 

go.mod, go.sum, vendor/github.com/lack/mcmaker/pkg/mcmaker.go, vendor/github.com/lack/yamltrim/README.md, vendor/github.com/lack/yamltrim/yamltrim.go, vendor/modules.txt
This update to mcmaker splits out part of the shared functionality into
a new 'yamltrim' package that will soon be reused in ztp/policygenerator and
ztp/siteconfig-generator.
=> vendor: Bump mcmaker dependency to v0.0.6

ztp/siteconfig-generator/siteConfig/filesHandler.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
The siteConfig generator currently only accepts a relative path for the manifest path argument.
This commit enables both relative and absolute paths to be accepted by first checking if the path provided is an absolute path, if not, it defaults to the relative path.
Signed-off-by: Sharat Akhoury sakhoury@redhat.com
/cc @imiller0 @lack
=> Bug 2044400: enable siteConfig generator to accept both relative and absolute manifest paths

ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go, ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingArgocdAnnotation.yaml, ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingMetadata.yaml, ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingMetadataAnnotations.yaml
The clusters app panics when klusterletaddonconfig via siteconfig has missing attributes / components such as the argocd sync-wave annotation.
This commit adds sanity checks to verify the existence of these attributes prior to instantiating the CR to avoid the application from panicking. If there are missing attributes, an appropriate error is returned instead!
Signed-off-by: Sharat Akhoury [sakhoury@redhat.com](mailto:sakhoury@redhat.com)
/cc @imiller0 @lack
=> Bug 2064825: add sanity checks prior to instantiating CR

ztp/source-crs/AmqSubscriptionNS.yaml
AMQ interconnect operators are not pinned to platform cores, and the AMQ namespace has an annotation to manage workload.
So removing workload management annotations from the namespace
=> [release-4.9] ztp: bug 2068098: Remove workload management annotation from AMQ namespace

ztp/gitops-subscriptions/argocd/README.md, ztp/resource-generator/Makefile, ztp/resource-generator/entrypoints/entrypoints, ztp/resource-generator/entrypoints/extract
As described in https://github.com/containers/podman/issues/13779,
podman by default logs all of a container's stdout in order to retain
info to make 'podman logs' work. But this extra copy of stdout can be
overrun and cause hangs when shipping large amounts of data through
stdout (as in the case when piping out a tar stream).  Changing the
instructions and documentation to add '--log-driver=none' to the podman
commandline disables this extra unneeded logging and prevents hangs.
=> Bug 2073439: ztp: Disable podman logging when extracting container data

ztp/gitops-subscriptions/argocd/README.md, ztp/resource-generator/Makefile, ztp/resource-generator/entrypoints/entrypoints, ztp/resource-generator/entrypoints/extract
As described in https://github.com/containers/podman/issues/13779,
podman by default logs all of a container's stdout in order to retain
info to make 'podman logs' work. But this extra copy of stdout can be
overrun and cause hangs when shipping large amounts of data through
stdout (as in the case when piping out a tar stream).  Changing the
instructions and documentation to add '--log-driver=none' to the podman
commandline disables this extra unneeded logging and prevents hangs.
(cherry picked from commit a2124e068a72c5f21a3ef874a8cb872ba086993d)
=> Bug 2073498: ztp: Disable podman logging when extracting container data

cnf-tests/pod-utils/cyclictest-runner/main.go
cyclictest does not yet support the --smi option for newer processors (e.g. ice lake).
This will require an update to the rt-tests package to support newer processor models.
Until that is done, the change to add must be backed out, or this test won't work on ice lake processors.
A NOTE: this change is not temporary - it probaly would never be safe to add --smi option here, because of the way cyclictest is written, it is always going to fail on new processor models.
=> Bug 2051540: cnf-tests:cyclictest: remove smi option

ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml, ztp/source-crs/PaoSubscription.yaml, ztp/source-crs/PaoSubscriptionCatalogSource.yaml, ztp/source-crs/PaoSubscriptionNS.yaml, ztp/source-crs/PaoSubscriptionOperGroup.yaml
The PAO subscription source-cr needs to remain available in the source-crs directory to support deployment of 4.10- clusters using the GitOps ZTP 4.11+ solution. However the subscription is removed from the reference PolicyGenTemplates so that future deployed clusters (running 4.11+) will not include PAO.
=> Remove PAO subscription from DU profile

Makefile
This commit will remove the SRO from the list of features we test on the CI
This is needed because there is no update method for the driverToolkit image
inside the CI cluster.
The outcome is that everytime there is a new kernel version for RHCOS the SRO lanes
start failing
There is an open RFE to the testplatform team to implement the auto rebuild.
We will be able to reintroduce this lane after that feature is implemented
=> infra: Disable SRO tests on CI

ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml, ztp/source-crs/extra-manifest/image-registry-partition-mc.yaml.tmpl
systemd unit file's path was broken, causing SNO installation failure. 
/cc @lack
=> ztp: fix broken systemd unit file path used for disk paritioning

hack/setup-test-cluster.sh
`node-role.kubernetes.io/worker-cnf` labeled nodes are used in many tests and it can be useful to stop the script with an error code in case it is impossible to label them for some reason (maybe there isn't any node at all).
=> infra: Stop setup cluster if zero worker-cnf nodes

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
DPDK tests need to deploy workloads on nodes with a
performance profile configured on them.
=> cnf-tests: use worker-cnf nodes in dpdk tests

ztp/gitops-subscriptions/argocd/ImageRegistry.md, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
update docs for disk partitioning to include use of rootDeviceHints and other warnings. also add the source crs file entries  in examples files
/cc @lack
=> ztp: update disk partitioning docs to include use of rootDeviceHint

feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-grandmaster.yaml, feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-slave.yaml, feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml, feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml, ztp/policygenerator/testData/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml, ztp/source-crs/PtpConfigMaster.yaml, ztp/source-crs/PtpConfigSlave.yaml, ztp/source-crs/PtpConfigSlaveCvl.yaml
Currently, only L2 as network_transport is supported.
Example yamls currently set network_transport UDPv4, and then override
with -2 command-line option.
Update to set network_transport to L2 in yaml.
=> Bug 2060492: ztp: Update network_transport to L2

hack/verify-commits.sh
in recent git versions, CVE-2022-24765 was mitigated, causing us
problems when trying to use git commands as part of prow pipelines. This
commit work around the issue by copying the git repository to a
directory owned by the running user.
=> infra: fix verify script to avoid git security check

ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml, ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-1-ranGen.yaml, ztp/source-crs/PerformanceProfile.yaml, ztp/source-crs/TunedPerformancePatch.yaml, ztp/source-crs/validatorCRs/informDuValidator.yaml
To avoid mistakes from the end user we hardcode the PerformanceProfile
name to match the value of informDuValidator
=> Bug 2066701: ztp: Match PerformanceProfile name with informDuValidator

cnf-tests/testsuites/e2esuite/ptp/ptp.go
The metrics substring for PTP offset was not found in 4.10, fixed it to correct the metrics name.
Signed-off-by: Aneesh Puttur <aneeshputtur@gmail.com>
=> Bug 2074070: cnf-tests:PTP time diff between GM and Slave metrics error fix

cnf-tests/Dockerfile, cnf-tests/Dockerfile.openshift
`nc` comes in handy when implement tests for multi-networkpolicy, in order to check if
a host/port is reachable from specific pods.
I'm filing this PR because images should be already available on quay.io prior to filing the PR that uses them.
=> Add netcat to cnftests image

cnf-tests/pod-utils/cyclictest-runner/main.go
The cyclictest binary which is called by the runner doesn't have the support for the mainaffinity flag in its current release.
Hence, we should remove the arg entirely
=> [release-4.10] Bug 2064585: cnf-tests: remove mainaffinity option

ztp/policygenerator/policyGen/policyBuilder.go, ztp/policygenerator/policyGen/policyBuilderOverlay_test.go, ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericMultiYaml.yaml
=> Bug 2087208 - informDuValidator (multi-yaml) policy fails when overlay status in multi yaml file

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
This change is needed because `-w` option in dpdk-testpmd was removed.
instead we need to use the new option `-a`
=> cnf-tests: Fix dpdk tests

functests/dpdk/dpdk.go
This change is needed because `-w` option in dpdk-testpmd was removed.
instead we need to use the new option `-a`
=> cnf-tests: [release-4.7] Fix dpdk tests

feature-configs/deploy/metallb/operator_operatorgroup.yaml
metallb-operator is now deployed in all Namespaces to support its conversion webhooks.
=> features: MetalLB: remove targetNamespaces

cnf-tests/testsuites/e2esuite/ptp/ptp.go
Recent change to check for master offset narrows down to find only one metrics for master offset.
The fix will check count of master offset to one
signed-off-by: Aneesh Puttur <aneeshputtur@gmail.com>
=> Bug 2098156: ptp offset metrics for master count should be one

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
This change is needed because `-w` option in dpdk-testpmd was removed.
instead we need to use the new option `-a`
=> Bug 2093969: cnf-tests: [release 4.9] Fix dpdk tests

cnf-tests/testsuites/e2esuite/bond/bond.go, cnf-tests/testsuites/e2esuite/security/tuning_sriov.go, cnf-tests/testsuites/pkg/networks/network.go
Adding an mtu parameter to the nad builder.
Note that mtu is a mandatory parameter, to avoid issues
with leaving the deafult value, which causes issues in
some test environments.
=> cnf-tests: add mtu to nad builder

cnf-tests/testsuites/pkg/networks/network.go
Backport of #1119 
The original PR just refactor the NetworkAttachmentDefinitionBuilder, which was introduced with tuning-cni tests.
We do not want to backport the tuning-cni tests, therefore the PR will have not just the refactoring but all of the network.go code.
=> cnf-tests: NetworkAttachmentDefinitionBuilder refactoring

cnf-tests/TESTLIST.md, cnf-tests/docgen/e2e.json, cnf-tests/testsuites/e2esuite/bond/bond.go, cnf-tests/testsuites/e2esuite/test_suite_test.go
Adding test verifying that a pod with a bond interface
over two macvlan interfaces is created correctly
depends on: #1175
=> cnf-tests: bond cni on macvlan test

cnf-tests/testsuites/e2esuite/test_suite_test.go, hack/run-functests.sh, hack/setup-test-cluster.sh
Doing this to allow running more than one instance of the tests in parallel on the same cluster, per feature, under different namespaces.
=> Allow running cnf-tests in parallel 

ztp/source-crs/SriovSubscriptionNS.yaml
The `openshift.io/run-level: "1"` label was replaced by a privileged SCC in the openshift/sriov-network-operator [commit](https://github.com/openshift/sriov-network-operator/commit/119c20587f169446481b27ce543766034f319f58). This change was introduced in OCP 4.5.
This PR contains the commit which removes the `openshift.io/run-level: "1"` label from `ztp/source-crs/SriovSubscriptionNS.yaml`.
A manual validation exercise was performed to verify this change. The exercise comprised of the following steps:
1. Build new ztp-site-generator image containing the changes in this commit (https://quay.io/repository/sakhoury/ztp-site-generator)
2. Update hub cluster (`ran-vcl02`) with new ztp-site-generator image
3. Deploy a spoke cluster (`cnfocto1`) with SriovNetwork policies
4. Verify that the …
=> ztp: Remove `run-level: "1"` annotation from the SR-IOV Namespace source CR

ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/common-ranGen.yaml, ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-1-ranGen.yaml, ztp/source-crs/BareMetalEventRelaySubscription.yaml, ztp/source-crs/BareMetalEventRelaySubscriptionNS.yaml, ztp/source-crs/BareMetalEventRelaySubscriptionOperGroup.yaml, ztp/source-crs/HardwareEvent.yaml
The baremetal-hardware-event-proxy-operator is renamed to bare-metal-event-relay. This PR implements this change in ztp.
Amq Interconnect is required for Bare Metal Event Relay to work, therefore add amq deployment in the examples.
Signed-off-by: Jack Ding <jacding@redhat.com>
=> rename Bare Metal Event Relay feature

go.mod, go.sum, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go, vendor/modules.txt
Dependency has been updated with commands:
```
github.com/openshift/sriov-network-operator@release-4.12
go mod tidy
go mod vendor
```
=> Bug 2097488 cnf-tests: bump `sriov-network-operator` commit

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Backport both #1117 and #1095 to release-4.9 as changes are about the same code and we get a clearer conflict resolution.
This fix should address cnf-tests errors mentioned in [BZ2104611](https://bugzilla.redhat.com/show_bug.cgi?id=2104611) and [BZ2104604](https://bugzilla.redhat.com/show_bug.cgi?id=2104604)
=> Bug 2104611: Bug 2104604: [release-4.9] Backport #1117, #1095

feature-configs/deploy/s2i/post_deploy.sh
We were missing few states. Exit with error if didn't match to Complete state.
=> features: dpdk build: Check for more states in post deploy script

ztp/siteconfig-generator-kustomize-plugin/kustomization.yaml, ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-expansion.yaml, ztp/siteconfig-generator/siteConfig/siteConfig.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go, ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml, ztp/source-crs/extra-manifest/workload/03-workload-partitioning.yaml
SNO expansion scenario occurs when initially a SNO
is deployed into production, and at a later date the
cluster size is increased by the addition of a worker node.
The resulting cluster will contain two nodes:
1. Original SNO serving as the control plane for itself and the additional node
2. One additional node without any control plane components (controlled by the SNO).
The additional worker is running the same type of workload as the original SNO,
so all the DU related configurations and optimizations apply to the worker
node as well. This includes workload partitioning.
This commit allows generation of workload partitioning
manifests on the additional worker node described above.
Signed-off-by: Vitaly <vgrinber@redhat.com>
/cc @lack @serngawy
=> ztp: Enable workload partitioning on SNO worker

cnf-tests/testsuites/e2esuite/test_suite_test.go, cnf-tests/testsuites/pkg/namespaces/namespaces.go
OCP >= 4.12 wants to have stricter podsecurity rules.
In our e2e tests we do a bunch of stuff, including running privileged pods. We just annotate the test namespace(s) to signal we need top privileges. Since e2e tests run in very controlled envs (CI mostly), and since test namespace should be gone anyway once the e2e tests are finished.
=> cnf-tests: Add support for PSA on test namespaces

feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-grandmaster.yaml, feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-slave.yaml, feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml, feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml, ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml, ztp/policygenerator/testData/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml, ztp/policygenerator/testData/TestPtpConfig/templates/TestPtpConfig.yaml, ztp/source-crs/PtpConfigMaster.yaml, ztp/source-crs/PtpConfigSlave.yaml, ztp/source-crs/PtpConfigSlaveCvl.yaml
The underlying reason to align the summary_interval and logSyncInterval
was due to a validating webhook in the PTP operator. This validation has
been removed and the values no longer need to be aligned. This commit is
being reverted because the change to the source CRs would cause an
update to the customer's configurations on upgrade which is no longer
required. To avoid this update and potential disruption the change is
being reverted. The customer can supply whatever values are appropriate
for their use case in the PolicyGenTemplate override.
=> Bug 2110015: Revert ptp interval changes

cnf-tests/testsuites/e2esuite/bond/bond.go, cnf-tests/testsuites/e2esuite/bond/bond_sriov.go, cnf-tests/testsuites/e2esuite/dpdk/dpdk.go, cnf-tests/testsuites/e2esuite/s2i/s2i.go, cnf-tests/testsuites/e2esuite/security/tuning.go, cnf-tests/testsuites/e2esuite/security/tuning_sriov.go, cnf-tests/testsuites/e2esuite/vrf/vrf.go, cnf-tests/testsuites/e2esuite/vrf/vrf_sriov.go, cnf-tests/testsuites/pkg/namespaces/namespaces.go, cnf-tests/testsuites/pkg/networks/sriov.go
This PR should fix the following test error:
```
/remote-source/app/cnf-tests/testsuites/e2esuite/bond/bond_sriov.go:64
Unexpected error:
<*errors.StatusError | 0xc0021d4c80>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "admission webhook \"network-resources-injector-config.k8s.io\" denied the request: could not find network attachment definition 'bond-testing/bond': could not get Network Attachment Definition bond-testing/bond: the server could not find the requested resource",
Reason: "",
Details: nil,
Code: 400,
},
}
admission webhook "network-resources-injector-config.k8s.io" denied the request: could not find network attachment definition 'bond-testing/bond': …
```
=> fix `[sriov] Bond CNI integration bond cni over sriov` test

ztp/policygenerator/policyGen/policyBuilder.go, ztp/policygenerator/policyGen/policyBuilderOverlay_test.go, ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericCR.yaml
This PR fixes the issue where the generated CR has missing content when user provided overrides for a list have more elements than the ones in the source-cr.
=> Bug 2049306: ztp: Fix the user overrides for a list

ztp/siteconfig-generator/siteConfig/siteConfig.go
This change allows deploying additional SNO workers with ZTP.
When adding a worker to an existing SNO, user
adds an additional node to the existing SiteConfig.
The Generator is processing the modified siteconfig
and adds an additional line in AgentClusterInstall:
workerAgents: 1
However, agentclusterinstall is immutable.There is an
admission webhook that declines the change,
and the sync fails:
Attempted to change AgentClusterInstall.Spec which is
immutable after install started, except for ClusterMetadata
fields. Unsupported change: ProvisionRequirements.WorkerAgents: (0 => 1)
/cc @lack @serngawy
=> ztp: Prevent changing immutable objects on sno expansion

ztp/source-crs/PtpOperatorConfig.yaml, ztp/source-crs/PtpOperatorConfigForEvent.yaml
ZTP DU workflow provisions PtpOperatorConfig resource in case there
is a need for ptpEventConfig setting, and for standard clusters regardless
of ptp event needs.
For SNOs, the PtpOperatorConfig resource includes daemonsetNodeSelector
set to "master".
If at a later time SNO is expanded with one or more workers, PTP operator
would not create linuxptp-daemon containers on the worker node(s). Any
attempt to change the daemonsetNodeSelector will result in ptp daemon
restart and time synchronization loss.
This commit sets daemonNodeSelector to "worker" unconditionally. It fits
all the deployment types known so far (both SNO and 3NC nodes have the
"worker" label, and will be selected. For the standard clusters we only
want to deploy PTP on workers)
/cc @lack @serngawy @aneeshkp
=> ztp: OCPBUGS-217: run PTP daemons on worker nodes only

ztp/source-crs/SriovOperatorConfig.yaml
ZTP DU workflow provisions SriovOperatorConfig resource.
For SNOs, the SriovOperatorConfig resource includes
configDaemonNodeSelector set to "master".
If at a later time SNO is expanded with one or more workers,
SRIOV operator would not create sriov-device-plugin and
sriov-network-config-daemon pods on the worker node(s).
Any attempt to change the configDaemonNodeSelector will
result in sriov-device-plugin and
sriov-network-config-daemon pods restart and possible
network connectivity loss.
This commit sets configDaemonNodeSelector to "worker"
unconditionally. This fits all the deployment types known so far
(both SNO and 3NC nodes have the "worker" label, and therefore will
be selected, and on the standard clusters we only want to deploy
the daemons on workers)
/cc @lack @serngawy …
=> ztp: OCPBUGS-239: run SR-IOV daemons on workers

cnf-tests/testsuites/e2esuite/sctp/sctp_sriov.go, cnf-tests/testsuites/e2esuite/vrf/vrf_sriov.go
Cleaning resources in `AfterEach(...)` ginkgo blocks inhibits
the k8sreporter to collect debug information in case of
failures.
=> cnf-tests: Avoid clean SR-IOV resources

hack/run-functests.sh
We are using that variable for tests configuration setup here:
https://github.com/openshift-kni/cnf-features-deploy/blob/55a8db917ac11c4bfe12ccaaac5f1850deb0e009/cnf-tests/testsuites/e2esuite/test_suite_test.go#L73
=> cnf-tests: Set FEATURES env var for running tests in container

cnf-tests/TESTLIST.md, cnf-tests/docgen/e2e.json, cnf-tests/testsuites/e2esuite/s2i/s2i.go
=> cnf-tests: rename s2i so it will not run on dpdk focus

hack/run-functests.sh
Setting FEATURES env var to a single string containing all features (features will be separated with pipes instead of spaces) to avoid bash passing it as a multi word string.
=> cnf-tests: tests in container: set FEATURES to a single string

hack/run-functests.sh
We need to use the openshift MetalLB Namespace for running the tests.
=> cnf-tests: Set MetalLB Namespace env var for running tests in container

tools/s2i-dpdk/Dockerfile
the following error:
```
ERROR: This system does not support "VPCLMULQDQ".
Please check that RTE_MACHINE is set correctly.
EAL: FATAL: unsupported cpu type.
EAL: unsupported cpu type.
EAL: Error - exiting with code: 1
Cause: Cannot init EAL: Operation not supported
```
switching to the general platform in dpdk
=> s2i: switch to generic platform dpdk

ztp/source-crs/SriovOperatorConfig.yaml
Reverts openshift-kni/cnf-features-deploy#1214
The reason for creating the original PR was to make the SR-IOV
potentially disruptive update to the customer's cluster upon upgrade. 
/cc @imiller0
=> ztp: OCPBUGS-239: run SR-IOV daemons on workers - Revert

ztp/source-crs/PtpOperatorConfig.yaml, ztp/source-crs/PtpOperatorConfigForEvent.yaml
Reverts openshift-kni/cnf-features-deploy#1213
The reason for creating the original PR was to make the PTP
potentially disruptive update to the customer's cluster upon upgrade.
/cc @imiller0
=> ztp: OCPBUGS-217: run PTP daemons on worker nodes only - Revert

ztp/source-crs/SriovOperatorConfig.yaml
Reverts openshift-kni/cnf-features-deploy#1225
The reason for creating the original PR was to make the SR-IOV
potentially disruptive update to the customer's cluster upon upgrade.
/cc @imiller0
=> ztp: OCPBUGS-495: run SR-IOV daemons on workers revert

ztp/source-crs/PtpOperatorConfig.yaml, ztp/source-crs/PtpOperatorConfigForEvent.yaml
Reverts openshift-kni/cnf-features-deploy#1226
The reason for creating the original PR was to make the PTP
potentially disruptive update to the customer's cluster upon upgrade.
/cc @imiller0
=> [release-4.11] ztp: OCPBUGS-496: run PTP daemons on worker nodes only - Revert

ztp/source-crs/PtpOperatorConfig.yaml, ztp/source-crs/PtpOperatorConfigForEvent.yaml
Reverts openshift-kni/cnf-features-deploy#1227
The reason for creating the original PR was to make the PTP
potentially disruptive update to the customer's cluster upon upgrade.
/cc @imiller0
=> Revert "[release-4.10] ztp: OCPBUGS-502: run PTP daemons on worker nodes only"

cnf-tests/testsuites/e2esuite/sctp/sctp.go, cnf-tests/testsuites/e2esuite/sctp/sctp_sriov.go, cnf-tests/testsuites/pkg/features/features.go, cnf-tests/testsuites/pkg/namespaces/namespaces.go
This is needed because the sctp tests use the default namespace
=> cnf-tests: add PSA labels to the default namespace

ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
This commit provides reference for overriding PTP daemonsetNodeSelector to "worker" instead of the default "master" predefined in the source-crs. The change is recommended on SNOs configured with PTP event notification for forward compatibility with possible SNO expansion. When the default setting is left intact, then in case of an SNO expansion with one or more workers, PTP operator
would not create linuxptp-daemon containers on the worker node(s). Any attempt to change the daemonsetNodeSelector will result in ptp daemon restart and time synchronization loss.
/cc @serngawy
=> ztp: OCPBUGS-217: set PTP daemonsetNodeSelector

ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
This commit provides reference for overriding SR-IOV configDaemonNodeSelector to "worker" instead of the default "master" predefined in the source-crs. The change is recommended on SNOs for forward compatibility with possible SNO expansion. When the default setting is left intact, then in case of an SNO expansion with one or more workers, SR-IOV operator would not create daemon containers on the worker node(s). Any attempt to change the configDaemonNodeSelector will result in daemon restart and possible downtime.
/cc @serngawy
=> ztp: OCPBUGS-239: set SR-IOV node selector

ztp/policygenerator/policyGen/policyBuilder.go, ztp/policygenerator/policyGen/policyBuilder_test.go, ztp/policygenerator/policyGen/policyHelper.go, ztp/policygenerator/utils/utils.go
This update adds a validation routine to prevent users entering an invalid
time duration string in PGT.
Signed-off-by: tliu2021 <tali@redhat.com>
=> OCPBUGS-467: ztp: Validate policy evaluation intervals

cnf-tests/testsuites/pkg/features/features.go
Add missing blank import to make sure to register the types needed by the NUMAResources suite.
Fixes instances of this error:
```
/remote-source/app/cnf-tests/testsuites/e2esuite/test_suite_test.go:106
Unexpected error:
<*meta.NoKindMatchError | 0xc001c6c1c0>: {
GroupKind: {
Group: "topology.node.k8s.io",
Kind: "NodeResourceTopology",
},
SearchedVersions: ["v1alpha1"],
}
no matches for kind "NodeResourceTopology" in version "topology.node.k8s.io/v1alpha1"
occurred
/remote-source/app/cnf-tests/testsuites/e2esuite/test_suite_test.go:109
```
Signed-off-by: Francesco Romani <fromani@redhat.com>
=> cnf-tests: intentionally ignore NROP setup errors 

ztp/gitops-subscriptions/argocd/SNOExpansion.md
This commit fixes a copy-paste error in the tuned patch manifest for sno expansion.
=> ztp: fix sno expansion tuned include directive

cnf-tests/testsuites/e2esuite/multinetworkpolicy/multinetworkpolicy_sriov.go, cnf-tests/testsuites/pkg/networkpolicy/multinetworkpolicy.go, cnf-tests/testsuites/validationsuite/cluster/validation.go
Running tests with `FEATURE=sriov` triggers tests in multinetworkpolicy_sriov.go, even if the multinet policy feature is not enable. A guard on the feature present is therefore needed.
=> cnf-tests: Skip test if multinetpolicy CRD is not present

cnf-tests/testsuites/e2esuite/fec/fec.go
Discovery mode skips the tests, so we should not try to delete any config in case discovery mode is enabled.
=> OCPBUGS-1594: Fec tests: do not clean in discovery mode

cnf-tests/TESTLIST.md, cnf-tests/docgen/e2e.json, cnf-tests/testsuites/e2esuite/multinetworkpolicy/multinetworkpolicy_sriov.go, hack/run-functests.sh
Adding brackets to focus on tests by feature. If FEATURES var is used for ginkgo focus we should do the filtering by suites ([feature]). Without the brackets we may run tests that have a feature name in their description while they belong to a feature suite that we don't want to currently test.
=> cnf-tests: Filter tests by features suites

cnf-tests/pod-utils/cyclictest-runner/main.go
We should handle the amount of minimal CPUs for cyclictest test more carefully. When HT disabled cyclictest needs 2 CPUs.
But when HT enabled oslat needs at least 4 CPUs:
One CPU should be used to run cyclictest's main thread. The second is the sibling of the first one, which should be excluded from the list of the tested CPUs, Because it might cause to false spikes (noisy-neighbor issue). The third one is the actual CPU to be tested, but due to SMT alignment restriction we need its sibling too. Four in total.
=> Bug 2094046: cnf-tests: verify minimal CPUs requirement for cyclictest test

OWNERS_ALIASES
Adding imiller0 for infrastructure/CI
Removing davidvossel and yrobla (not active in this project)
=> owners: Update owners aliases

go.mod, go.sum, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/groupversion_info.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/helper.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/client/clientset/versioned/scheme/register.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/test_sriov_operator.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/clean/clean.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/namespaces/namespaces.go, vendor/modules.txt
```
go mod edit -replace\
github.com/openshift/sriov-network-operator@release-4.12
go mod tidy
go mod vendor
```
=> cnf-tests: sriov-network-operator bump 4.12

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go, cnf-tests/testsuites/pkg/networks/sriov.go, go.mod, go.sum, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/cluster/cluster.go, vendor/modules.txt
this commit add a check to be sure for intel nics that we enable sriov in the bios. if that is not the case the totalvf variabel will be 0 so we skip that nic
=> cnf-tests: improve sriov nic selector

go.mod, go.sum, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/helper.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodestate_types.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go, vendor/modules.txt
```
github.com/openshift/sriov-network-operator@release-4.10
go mod tidy
go mod vendor
```
This PR should fix:
```
[Fail] [sriov] operator Generic SriovNetworkNodePolicy Virtual Functions [It] should release the VFs once the pod deleted and same VFs can be used by the new created pods
/remote-source/app/vendor/[github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go:892](http://github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go:892)
```
=> cnf-tests: sriov-network-operator bump 4.10

ztp/source-crs/StorageLVMCluster.yaml, ztp/source-crs/StorageLVMOSubscription.yaml, ztp/source-crs/StorageLVMOSubscriptionNS.yaml, ztp/source-crs/StorageLVMOSubscriptionOperGroup.yaml
Adds all the required manifests to install and configure the LVM Operator. Basically the subscription, operatorgroup and namespace (install) and the lvmcluster (configuration).
Signed-off-by: Alberto Losada <alosadag@redhat.com>
cc/ @imiller0
=> ztp: Adds LVM operator source crs for ZTP

feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-grandmaster.yaml, feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-slave.yaml, feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml, feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml, ztp/policygenerator/testData/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml, ztp/source-crs/PtpConfigMaster.yaml, ztp/source-crs/PtpConfigSlave.yaml, ztp/source-crs/PtpConfigSlaveCvl.yaml
This change is to allow faster reconciliation when a slave goes out of sync, for example from receiving invalid time from GM.
Closes-Bug: OCPBUGS-3005
=> ztp: OCPBUGS-3005: set step_threshold to 2.0

go.mod, go.sum, vendor/github.com/test-network-function/l2discovery-lib/l2lib.go, vendor/modules.txt
This is to fix a failure with the ptp node device interface test due to Virtual functions not removed from the list of potential PTP interfaces
=> fix for ptp interfaces test failure

cnf-tests/testsuites/pkg/namespaces/namespaces.go
The performance testing are running privileged pods, hence we need to annotate the performance testing namespace, to signal we need higher privileges.
The risk is minimal, since this is a controled environment and the namespace will get deleted at the end of the test anyway.
=> cnf-tests: add PSA for performance tests` NS

Makefile
One of jobs will need to deploy features, but not to run functest. It will run origin tests probably. Add a task that prepare for it.
=> infra: Add feature-deploy-on-ci task to Makefile for U/S CI

ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
installConfigOverrides is the generic way of passing install-config parameters through the siteConfig.
This change adds a sample installConfigOverrides that configures the composable openshift feature with the 'capabilities' field.  It removes all but the marketplace component from the optional set of components.  The resulting 'capabilities' in the install-config will be:
capabilities:
baselineCapabilitySet: None
additionalEnabledCapabilities:
- marketplace
=> ztp: example config of composable Openshift

ztp/extra-manifests-builder/01-container-mount-ns-and-kubelet-conf/build.sh, ztp/source-crs/extra-manifest/01-container-mount-ns-and-kubelet-conf-master.yaml, ztp/source-crs/extra-manifest/01-container-mount-ns-and-kubelet-conf-worker.yaml
The unit doesn't need to be enabled as it's set up as a dependency of
crio and kubelet.  Removing the 'enabled' flag from the MachineConfig
will remove an ignition warning message that could be concerning to
users.
/hold until testing is completed
=> Bug 2111108: ztp: Remove container-mount-namespace.service installation warnings

ztp/source-crs/PerformanceProfile.yaml
This commit updates source-crs/PerformanceProfile with workloadHints for powerstate configurations. The default configuration is set to performance mode.
Tests have been performed to validate that no reboot on SNO upgrade will be triggered as a result of this change.
Signed-off-by: Sharat Akhoury <sakhoury@redhat.com>
/assign @bartwensley @browsell @imiller0
=> ztp: Add workloadHints to source-crs/PerformanceProfile

ztp/gitops-subscriptions/argocd/PowerConfiguration.md
This PR adds documentation to the ztp repo for configuring power modes.
Signed-off-by: Sharat Akhoury <sakhoury@redhat.com>
/assign @bartwensley @imiller0
=> ztp: Add documentation for configuring power modes with ztp

cnf-tests/testsuites/e2esuite/multinetworkpolicy/reachmatcher.go, cnf-tests/testsuites/e2esuite/ovs_qos/ovs_qos.go, cnf-tests/testsuites/pkg/pods/pods.go, ztp/policygenerator/policyGen/policyHelper.go
`make ci-job` is broken after golang version update
This PR should fix the formatting errors
=> ztp: Make formatting compatible with golang1.19

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
The regression has been introduced in
- https://github.com/openshift-kni/cnf-features-deploy/pull/1209
`vhostnet` and `VFS allocated for dpdk` suites require that the NIC is configured with 5 `dpdknic` resources.
`createSriovPolicyAndNetworkShared()` allocates 2 `dpdknic` and 3 `regularnic` (netdevice) resources.
=> cnf-tests: allocate more dpdknic res in vhostnet

hack/setup-build-index-image.sh
Set +x before login so it's not leaked in logs, set -x back after a login.
=> infra: Hide podman login in logs to prevent password leaks

ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
In 4.13, Node Tuning Operator is now an optional part of compososable
OpenShift, and we need to make sure it's there.
=> ztp: Add NodeTuning operator to installConfigOverrides for 4.13

cnf-tests/TESTLIST.md, cnf-tests/docgen/e2e.json, cnf-tests/docgen/validation.json, cnf-tests/hack/build-test-bin.sh, cnf-tests/testsuites/configsuite/test_suite_test.go, cnf-tests/testsuites/e2esuite/test_suite_test.go, cnf-tests/testsuites/validationsuite/test_suite_test.go, go.mod, go.sum, openshift-ci/Dockerfile.tools, vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md, vendor/github.com/onsi/ginkgo/v2/core_dsl.go, vendor/github.com/onsi/ginkgo/v2/ginkgo_cli_dependencies.go, vendor/github.com/onsi/ginkgo/v2/reporters/junit_report.go, vendor/github.com/onsi/ginkgo/v2/types/version.go, vendor/github.com/onsi/gomega/CHANGELOG.md, vendor/github.com/onsi/gomega/gomega_dsl.go, vendor/github.com/onsi/gomega/matchers.go, vendor/github.com/onsi/gomega/matchers/have_exact_elements.go, vendor/golang.org/x/net/html/token.go, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/hpack/hpack.go, vendor/golang.org/x/net/http2/server.go, vendor/modules.txt
This PR bumps Ginkgo to the latest v2.8.4 that includes a new feature that enables it to
omit setup nodes from the JUnit report.
This will omit the extra empty testcase entry in the docs.
=> cnf-tests: Fix the JUnit reporter

ztp/ran-crd/site-config-crd.yaml, ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site2-sno-du.yaml, ztp/siteconfig-generator/siteConfig/clusterCRs.go, ztp/siteconfig-generator/siteConfig/siteConfig.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go, ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml
As of OCP 4.12, the `apiVIP` and `ingressVIP` install parameters are deprecated[1]
This change adds support for the new array-based `apiVIPs` and `ingressVIPs`. The examples were updated to use the new syntax, though the old syntax is still supported.
[1]https://docs.openshift.com/container-platform/4.12/release_notes/ocp-4-12-release-notes.html#ocp-4-12-nw-api-ingress-ipv6-support
=> OCPBUGS-8313: Add support for apiVIPs and ingressVIPs

ztp/gitops-subscriptions/argocd/SNOExpansion.md, ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml, ztp/ran-crd/site-config-cr-ex.yaml, ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml, ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-expansion.yaml, ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site2-sno-du.yaml, ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site2-standard-du.yaml, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go, ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
The macAddress field under
spec.clusters[].nodes[].nodeNetwork.config.interfaces[] is not needed. The network configuration is matched to interfaces based on the macAddress under the spec.clusters[].nodes[].nodeNetwork.interfaces[]. In addition, if the config.interfaces field is included it needs to be mac-addresses. Since it is not necessary this PR simply removes it.
=> OCPBUGS-8238: ztp: Remove incorrect macAddress field

ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml, ztp/source-crs/PerformanceProfile.yaml
A new `workloadHints` object was added to 4.13 PerformanceProfile source-crs specification which does not exist in previous ZTP versions. This results in an installation failure for earlier releases.
This commit comments out the workloadHints object and adds it to the example files. When ZTP becomes version-aware, the `workloadHints` object will be uncommented.
Signed-off-by: Sharat Akhoury <sakhoury@redhat.com>
/cc @browsell @imiller0 @bartwensley
=> OCPBUGS 7464: ztp: Comment out workloadHints in ZTP 4.13

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go, cnf-tests/testsuites/e2esuite/multinetworkpolicy/reachmatcher.go
Annotation `k8s.v1.cni.cncf.io/networks-status` has been changed to `k8s.v1.cni.cncf.io/network-status` and the former is no longer supported. Use the new key in e2e tests utilities.
Refs:
k8snetworkplumbingwg/network-attachment-definition-client/pull/45
=> Update references to `networks-status`

go.mod, go.sum, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/helper.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodepolicy_types.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodestate_types.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/test_sriov_operator.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/client/clients.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/discovery/discovery.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/namespaces/namespaces.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/network/network.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/nodes/nodes.go, vendor/modules.txt
```
github.com/openshift/sriov-network-operator@release-4.14
go mod tidy
go mod vendor
```
=> cnf-tests: sriov-network-operator bump 4.14

ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-validator-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-validator-ranGen.yaml, ztp/policygenerator-kustomize-plugin/kustomization.yaml, ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/example-group-du-sno-validator-ranGen.yaml
first time TALM observes a policy with this annotation as compliant, it won't move on. In future reconcilations if the specified number of seconds has passed since the first compliancy time and policy is still compliant, then TALM will move on from this policy.
=> OCPBUGS-7540: ztp: Add `soakSeconds` annotation to informDUValidator

go.mod, go.sum, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/helper.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodepolicy_types.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodestate_types.go, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/network/network.go, vendor/modules.txt
```
github.com/openshift/sriov-network-operator@release-4.13
go mod tidy
go mod vendor
```
=> OCPBUGS-11065: [release-4.13] cnf-tests: sriov-network-operator bump 4.13

cnf-tests/testsuites/e2esuite/xt_u32/xt_u32.go
A patch [1] in iptables v1.8.8 changed the expected output of a negative xt_u32 cnf-test. This patch was backported in RHEL 8.7 (which cnf-tests container image is based on currently) in iptables-1.8.4-23 RPM.
```
/remote-source/app/cnf-tests/testsuites/e2esuite/xt_u32/xt_u32.go:95
Expected
<string>: Warning: Extension u32 revision 0 not supported, missing kernel module?
iptables v1.8.4 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain INPUT
to contain substring
<string>: Couldn't load match `u32':No such file or directory
/remote-source/app/cnf-tests/testsuites/e2esuite/xt_u32/xt_u32.go:113
```
[1] https://git.netfilter.org/iptables/commit/?id=17534cb18ed0a5052dc45c117401251359dba6aa
=> OCPBUGS-5121: cnf-tests: fix xt_u32 negative test

ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml, ztp/source-crs/optional-extra-manifest/enable-crun-master.yaml, ztp/source-crs/optional-extra-manifest/enable-crun-worker.yaml
This is a manual cherry-pick of #1457
=> [release-4.13] ztp: config crun as the default container runtime for 4.13+

cnf-tests/pod-utils/hwlatdetect-runner/main.go
The window length and width determine how often will hwlat detector check for cpu time unaccounted for.
Our opinionated default should be 95% of every second.
There was a typo in the code that reduced that to 9.5% as it was scanning for 0.95 s every 10 s. This patch fixes that.
=> OCPBUGS-4378: Fix the hwlatdetect default window duration

ztp/gitops-subscriptions/argocd/example/policygentemplates/example-multinode-site.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml
We should use the default config as mentioned in the official doc. See [this](https://docs.openshift.com/container-platform/4.12/networking/hardware_networks/configuring-sriov-device.html) for the latest.
=> OCPBUGS-12965: ztp: update isRdma to false to match default value suggested in SriovNetworkNodePolicy doc

ztp/source-crs/LVMOperatorStatus.yaml, ztp/source-crs/StorageLVMCluster.yaml, ztp/source-crs/StorageLVMSubscription.yaml, ztp/source-crs/StorageLVMSubscriptionNS.yaml, ztp/source-crs/StorageLVMSubscriptionOperGroup.yaml
Notice that in OCP 4.12+ the odf-lvmo operator was replaced by lvms operator. The source-crs were included in 4.11, this means that several overrides to those need to be made in order to install the LVMS operator in 4.12+.
This PR wants to ease the process of installing LVMS in OCP 4.12+. Therefore:
* New source-crs were included for LVMS. The old ones were not replaced by the new ones,  they are foreseen to be removed in 4.14. So the docs are still valid.
* The LVM cluster source-cr name was modified. This does not change anything in 4.11 or 4.12+.
* A new source-cr to validate the proper installation of the LVMS is included. If you want to use in 4.11 a name override must be added.
Documentation needs to be modified accordingly cc/ @amolnar-rh
cc/ @imiller0
=> ztp: [CNF-8046] Replacing LVMS source-crs instead of LVMO 

hack/feature-deploy.sh
Use the built-in `oc kustomize` instead of downloading from github.
This change is required to resolve the following error:
Downloading the Kustomize tool
/tmp/shared/cnf/cnf-features-deploy /shared/cnf/cnf-features-deploy
Github rate-limiter failed the request.
Either authenticate or wait a couple of minutes.
=> cnf-tests: Use the built-in oc kustomize

OWNERS_ALIASES
@zeeke has been actively contributing to cnf-features-deploy in the form of code (24 PRs / 28 commits) and review contributions.
=> owners: add zeeke in cnf-features-approvers

cnf-tests/testsuites/e2esuite/security/tuning.go, cnf-tests/testsuites/e2esuite/security/tuning_sriov.go, cnf-tests/testsuites/pkg/features/features.go, cnf-tests/testsuites/pkg/namespaces/namespaces.go, cnf-tests/testsuites/pkg/utils/reporter.go
Cleaning resources in AfterEach decorator makes the reporter not collect test resources. It's preferable to do it in the clean section and at the end of the suite (i.e. in *Fixtures in features.go)
=> cnf-tests: Avoid clean pods after test in tuningcni tests

hack/feature-deploy.sh
Use the built-in `oc kustomize` instead of downloading from github. This change is required to resolve the following error:
Downloading the Kustomize tool
/tmp/shared/cnf/cnf-features-deploy /shared/cnf/cnf-features-deploy Github rate-limiter failed the request.
Either authenticate or wait a couple of minutes.
=> cnf-tests: Use the built-in oc kustomize (4.13 backport)

ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml, ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml, ztp/policygenerator/README.md, ztp/ran-crd/policy-gen-template-ex.yaml, ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml, ztp/source-crs/SriovOperatorConfig.yaml, ztp/source-crs/TunedPerformancePatch.yaml
- 'nohz_full=${isolated_cores}' is removed from TunedPerformancePatch.yaml as it's covered in the auto-created tuned patch for the performanceProfile already.
- The reference to ConsoleOperatorDisable.yaml is removed from the PGT example as the console operator is not installed in the first place when disabling baselineCapabilitySet via SiteConfig
- 'disableDrain: false' is removed from SriovOperatorConfig.yaml as it's set automatically by the operator. It's marked to true when the cluster is SNO and false for other types
=> OCPBUGS-6763: ztp: Cleanup some source CRs

ztp/gitops-subscriptions/argocd/deployment/argocd-openshift-gitops-patch.json
See argoCD operator [apis](https://github.com/argoproj-labs/argocd-operator/blob/9fefa311208ed0e39f41a6c72c4834dba943b2f5/api/v1alpha1/argocd_types.go#L449). It a standard `[]corev1.Volume` which expects a `name` and `VolumeSource` e.g emptyDir/AzureDisk/hostPath. 
If not specified, the Volume is implied to be an EmptyDir. Which is why there was warning but everything worked as expected. 
/cc @imiller0 
/cc @lack
=> OCPBUGS-12966: ztp: fix argocd patch volume keys

feature-configs/5g-ref-nw/clusters/otwaon34567sno/nw-config/logging/README.md, feature-configs/5g-ref-nw/profile-base/sno-general/cluster-logging.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml, ztp/policygenerator/README.md, ztp/ran-crd/policy-gen-template-ex.yaml, ztp/source-crs/ClusterLogging.yaml
The curation section is now completely deprecated in cluster logging 5.7 which can be safely cleaned up. Removing it shouldn't have any impact on users who currently have it configured.
=> OCPBUGS-9413: ztp: remove the deprecated curation section from ClusterLogging CR

ztp/ran-crd/site-config-crd.yaml, ztp/siteconfig-generator/siteConfig/clusterCRs.go, ztp/siteconfig-generator/siteConfig/siteConfig.go, ztp/siteconfig-generator/siteConfig/siteConfigHelper_test.go, ztp/siteconfig-generator/siteConfig/siteConfig_test.go, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badAnnotation.yaml, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badName.yaml, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badNamespace.yaml, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride.yaml
- add the automatedCleaningMode field to the SiteConfig CRD and by default set it to "disabled" (path to the new field is SiteConfig.Spec.Cluster.Node.automatedCleaningMode)
- the automatedCleaningMode field from a SiteConfig CR will be translated into the spec.automatedCleaningMode field in the generated BareMetalHost CR(s)
- update testcases to reflect this new field
=> ztp: Expose disk cleaning option through SiteConfig

tools/s2i-dpdk/Dockerfile
This adds the sys_resource, ipc_lock and net_raw (for mellanox) on the testpmd and testbbdev binaries for unpriviledged pods.
=> s2i: add capabilities on testpmd and testbbdev bins

ztp/policygenerator-kustomize-plugin/Makefile
- Makefile under policygen plugin earlier copied source-crs in the executable path
- Due to git first search, now the source-crs are copied under current working directory 
- to mimic source-crs directory being in the git
/assign @serngawy @imiller0 @lack
=> ztp: copy source-crs in current working directory to mimic git behavior in Makefile

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
DPDK workloads get multiple environment variables injected by the device plugin, e.g:
```
PCIDEVICE_OPENSHIFT_IO_DU_FH=0000:1a:03.4
PCIDEVICE_OPENSHIFT_IO_DU_FH_INFO={"0000:1a:03.4":{"generic":
{"deviceID":"0000:1a:03.4"},
"vfio":{"dev-mount":"/dev/vfio/206","mount":"/dev/vfio/vfio"}}}
```
`findNUMAForSRIOV` had chances to read the
`PCIDEVICE_OPENSHIFT_IO_*_INFO` variable, as listing them has no predictable order.
=> OCPBUGS-15470: Fix PCI addr calculation in DPDK tests

ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-3node-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-standard-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml, ztp/source-crs/PerformanceProfile-SetSelector.yaml, ztp/source-crs/PerformanceProfile.yaml
The is PR re-introduces the `workloadHints` object in the PerformanceProfile source-crs. It was initially added in 4.13, however it had to be commented out because at that point QE was experiencing issues deploying tests as ZTP was version unaware.
Now, with ZTP version awareness - it can be safely added back.
/cc @imiller0 @bartwensley  @serngawy @sabbir-47
=> CNF-7818: ztp: Uncomment workloadHints object in PerformanceProfile

ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-common-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml, ztp/source-crs/AmqSubscription.yaml, ztp/source-crs/BareMetalEventRelaySubscription.yaml, ztp/source-crs/ClusterLogSubscription.yaml, ztp/source-crs/PaoSubscription.yaml, ztp/source-crs/PtpSubscription.yaml, ztp/source-crs/SriovSubscription.yaml, ztp/source-crs/StorageLVMOSubscription.yaml, ztp/source-crs/StorageLVMSubscription.yaml, ztp/source-crs/StorageSubscription.yaml
CNF-8305. Using DefaultCatsrc CR means we are using disconnected env.
/cc @imiller0 
/cc @sabbir-47
=> ztp: rename DefaultCatsrc to inform that CR is for disconnected env and update all subscriptions

ztp/siteconfig-generator/siteConfig/clusterCRs.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go, ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml, ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
Reverts openshift-kni/cnf-features-deploy#1526
see: https://issues.redhat.com/browse/OCPBUGS-16094 
/cc @lack 
/cc @imiller0
=> OCPBUGS-16094: Revert "OCPBUGS-3513: use manifestsConfigMapRefs "

ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml, ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml, ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml, ztp/source-crs/HardwareEvent.yaml, ztp/source-crs/PtpOperatorConfigForEvent-SetSelector.yaml, ztp/source-crs/PtpOperatorConfigForEvent.yaml
Replace PVC with ConfigMap to persist subscriber data for HTTP transport
=> Bug OCPBUGS-14921: ztp: Use HTTP as default transport for cloud events 

cnf-tests/TESTLIST.md, cnf-tests/docgen/e2e.json, cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go, cnf-tests/testsuites/pkg/performanceprofile/performanceprofile.go, cnf-tests/testsuites/pkg/pods/pods.go
This PR contains a version bump for the sriov-network-operator to use the new API field `SriovNetworkNodePolicy.Spec.ExcludeTopology`.
Tests leverage two devices on different numa nodes and guaranteed pods.
cc @SchSeba , @gregkopels
=> SRIOV ExcludeTopology tests

ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml, ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml, ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml, ztp/source-crs/HardwareEvent.yaml, ztp/source-crs/PtpOperatorConfigForEvent.yaml
Replace PVC with ConfigMap to persist subscriber data for HTTP transport
=> [release-4.13] Bug OCPBUGS-16627: ztp: Use HTTP as default transport for cloud events

ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml, ztp/source-crs/HardwareEvent.yaml, ztp/source-crs/PtpOperatorConfigForEvent.yaml
Replace PVC with ConfigMap to persist subscriber data for HTTP transport
=> [release-4.12] Bug OCPBUGS-16782: ztp: Use HTTP as default transport for cloud events

cnf-tests/testsuites/e2esuite/sctp/sctp.go, cnf-tests/testsuites/e2esuite/security/tuning.go, cnf-tests/testsuites/e2esuite/vrf/vrf.go, cnf-tests/testsuites/pkg/pods/pods.go
Add a print to the test pod's events on test failure, to help with troubleshooting.
Example for the output of GetStringEventsForPod:
`2023-07-23 14:14:54 +0300 IDT: Successfully assigned l2-6521/external-local-lb-lgwgg to kind-worker 2023-07-23 14:14:55 +0300 IDT: Container image "registry.k8s.io/e2e-test-images/agnhost:2.43" already present on machine 2023-07-23 14:14:55 +0300 IDT: Created container netexec 2023-07-23 14:14:55 +0300 IDT: Started container netexec`
=> cnf-tests: log test pod events on failure

ztp/source-crs/PerformanceProfile-SetSelector.yaml, ztp/source-crs/PerformanceProfile.yaml
load the vfio-pci driver on boot with the parameters needed by the sriov-fec
=> ztp: update performance profile to load vfio-pci

tools/s2i-dpdk/Dockerfile
In a non-priviledged pod, user 1001 needs to be part of group 801 to be able to access the vfio device.
=> s2i: add supplementary group 801 to 1001 user

go.mod, go.sum, vendor/github.com/metallb/metallb-operator/pkg/status/status.go, vendor/github.com/metallb/metallb-operator/test/e2e/functional/tests/e2e.go, vendor/github.com/metallb/metallb-operator/test/e2e/metallb/metallb.go, vendor/modules.txt
Bump metallb vendor to latest commit on release-4.11
This is so we include a fix that extends a timeout for a flaky test case.
=> [release-4.11] Bump metallb vendor

go.mod, go.sum, vendor/github.com/Masterminds/semver/v3/.golangci.yml, vendor/github.com/Masterminds/semver/v3/CHANGELOG.md, vendor/github.com/Masterminds/semver/v3/constraints.go, vendor/github.com/Masterminds/semver/v3/doc.go, vendor/github.com/Masterminds/semver/v3/version.go, vendor/github.com/Masterminds/sprig/v3/CHANGELOG.md, vendor/github.com/Masterminds/sprig/v3/README.md, vendor/github.com/metallb/metallb-operator/pkg/status/status.go, vendor/github.com/metallb/metallb-operator/test/e2e/functional/tests/e2e.go, vendor/github.com/metallb/metallb-operator/test/e2e/metallb/metallb.go, vendor/modules.txt
Bump metallb vendor to latest commit on release-4.13 
This is so we include a fix that extends a timeout for a flaky test case.
=> [release-4.13] Bump metallb vendor

ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml, ztp/policygenerator/README.md
CNF-9132 Align the reference PolicyGenTemplates with use of vector for log collection. The PGT simply use the source CR to align with default collector. Update test code and README to align.
=> ztp: Align reference PGT with vector

go.mod, go.sum, vendor/github.com/Masterminds/semver/v3/.golangci.yml, vendor/github.com/Masterminds/semver/v3/CHANGELOG.md, vendor/github.com/Masterminds/semver/v3/constraints.go, vendor/github.com/Masterminds/semver/v3/doc.go, vendor/github.com/Masterminds/semver/v3/version.go, vendor/github.com/Masterminds/sprig/v3/CHANGELOG.md, vendor/github.com/Masterminds/sprig/v3/README.md, vendor/github.com/metallb/metallb-operator/api/v1beta1/metallb_types.go, vendor/github.com/metallb/metallb-operator/pkg/status/status.go, vendor/github.com/metallb/metallb-operator/test/e2e/functional/tests/e2e.go, vendor/github.com/metallb/metallb-operator/test/e2e/metallb/metallb.go, vendor/modules.txt
Bump metallb vendor to latest commit (release-4.14) This is so we include a fix that extends a timeout for a flaky test case.
=> [release-4.14] Bump metallb vendor

ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go, ztp/siteconfig-generator/siteConfig/siteConfigHelper.go, ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningWarningTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
We incorrectly merged in messaging that stated this feature was available in 4.13, this is a 4.14 feature. Updated logic to allow users to use it as a TechPreview flag in 4.13 as originally intended but with correct wording
/assign @imiller0
=> OCPBUGS-13313: fix: error in messaging for cpu partitioning

ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-3node-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-standard-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
The overlay content for the tuned patch in the group profile is identical to the content in the base source-cr. There is no need to maintain (or recommend to the user) the overlay content.
=> ztp: Remove redundant overlay content

cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go, cnf-tests/testsuites/pkg/machineconfigpool/machineconfigpool.go, cnf-tests/testsuites/pkg/nodes/nodes.go
Make NUMA/SR-IOV integration tests creating their own PerformanceProfile that sets single-numa-node policy and reserve an enitre NUMA node as Isolated.
Add functions to manipulate `node-role.kubernetes.io/x` labels on node to apply the performacen profile to arbitrary nodes.
cc @gregkopels
=> cnf-tests: dynamically created KubeletConfig

ztp/gitops-subscriptions/argocd/README.md
Updated upstream doc explaining the behavior of `extramnifests.searchPaths`
=> ztp: extramnifests searchPath section is re-written

ztp/source-crs/PtpConfigGmWpc.yaml
Pins should be configured in their entirety
Add required changes to ubxtool commands
=> OCPBUGS-17699: Update WPC GM config

cnf-tests/testsuites/e2esuite/security/tuning.go, cnf-tests/testsuites/pkg/pods/pods.go
Tuning CNI test cases leverage multus macvlan networks, so
pods must be located in the same host to ping each other.
Previuous way to ensure pods are co-located was not good, as the field
`pod.Spec.NodeName` is not populated when the pod is created.
Use `pod.Spec.Affinity.podAffinity` using pod labels to ensure
client and server pods run on the same host.
cc @liornoy 
thanks to [1] I could identify the flake:
```go
podDefinition2.Spec.NodeName = pod.Spec.NodeName
```
- [1] https://github.com/openshift-kni/cnf-features-deploy/pull/1617
Fixes
```
[FAIL] [tuningcni] tuningcni over macvlan [It] pods with sysctl's over macvlan should be able to ping each other
/go/src/github.com/openshift-kni/cnf-features-deploy/cnf-tests/testsuites/e2esuite/security/tuning.go:93
[FAIL] [tuningcni] tuningcni …
```
=> cnf-tests: Fix flaky tuningcni tests

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go, cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go, cnf-tests/testsuites/pkg/numa/numa.go, cnf-tests/testsuites/pkg/numa/numa_test.go
If a node has many CPUs, `lscpu` command output may split over multiple lines, making it hard to get the list of CPUs per NUMA node.
Switching to `lscpu --parse=cpu,node` simplifies the parsing logic.
cc @SchSeba
=> OCPBUGS-15790, OCPBUGS-15791: cnf-tests: Use `lspcu --parse` to get NUMA  node

Makefile
Run the unit tets for the utility functions
on cnf-tests as part of the `ci-job` Makefile
rule.
First unit tests have been introduced in:
- https://github.com/openshift-kni/cnf-features-deploy/pull/1622
cc @SchSeba
=> cnf-tests: Run unit tests during CI

ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml, ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-expansion.yaml
The current examples about using InstallerArgs, to
interact with the AI Service, seems not been
working correctly.
Using: {"args": ["--append-karg", "nameserver=8.8.8.8", "-n"]} makes the AI agent to fail to unmarshall
```
- lastTransitionTime: "2023-09-08T07:58:00Z"
message: 'The Spec could not be synced due to an input error: Fail to unmarshal
installer args for host 00000000-0000-0000-0000-000000000008 in infraEnv 0e7b3463-b7a5-4fc7-ae68-e249d52760e3:
json: cannot unmarshal object into Go value of type []string'
reason: InputError
status: "False"
type: SpecSynced
```
Just using:  ["--append-karg", "nameserver=8.8.8.8", "-n"] seems to be working.
=> ztp: correct examples using InstallerArgs

go.mod, go.sum, vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/performance.go, vendor/modules.txt
We improved the logging in the RPS test https://github.com/openshift/cluster-node-tuning-operator/pull/787 in order to find out why the test failed upstream.
=> vendor: bump nto deps

cnf-tests/testsuites/configsuite/test_suite_test.go, cnf-tests/testsuites/e2esuite/test_suite_test.go, cnf-tests/testsuites/validationsuite/test_suite_test.go
Custom ginkgo FailHanlder adds an item in the call stack when handling a failure and ginkgo uses `panic(...)` to get the stacktrace and to infer the user code location of the failing assertion.
This commit ensure the `callerSkip ...int` parameter is incremented.
Prior to this commit, failing messages appeared as
```
In [It] at: /tmp/cnf-jc658/cnf-features-deploy/vendor/github.com/onsi/gomega/internal/assertion.go:62 @ 09/11/23 20:31:50.623
```
(the failing line is always inside `vendor/github.com/onsi/gomega/internal/...`)
Example [here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g-cnftests/1701302792343261184/artifacts/e2e-telco5g-cnftests/telco5g-cnf-tests/artifacts/test_results.html)
Ref:
- …
=> cnf-tests: Dump correct code line on failure

cnf-tests/Dockerfile, cnf-tests/Dockerfile.openshift
This commit bumps the image version of origin-oc-rpms that we use as part of the cnf-tests container Dockerfile.
=> cnf-tests: Bump origin-oc-rpms version

cnf-tests/testsuites/pkg/pods/pods.go, tools/s2i-dpdk/Dockerfile
The directory /mnt/huge couldn't be accessed by the 1001 user. fsGroup mounts the volume with 1001 group permissions.
=> cnf-tests: Add fsGroup for rootless dpdk pod

cnf-tests/testsuites/e2esuite/sctp/sctp.go, cnf-tests/testsuites/e2esuite/vrf/vrf.go, cnf-tests/testsuites/pkg/pods/pods.go
When the `Eventually(...)` call fails, the variables inside its block can be nil and they should not be passed to
`pods.GetStringEventsForPodFn()`, as they would cause a `nil pointer dereference` error.
Improve the information returned by `GetStringEventsForPodFn` when the pod retrieval raises errors.
Sample errors in:
- https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-cnftests/1709932352127373312/artifacts/e2e-telco5g-cnftests/telco5g-cnf-tests/artifacts/saved-cnf-tests-run.log
cc @liornoy 
```
[0m[vrf] [38;5;243m [0mIntegration: NAD, IPAM: static, Interfaces: 1, Scheme: 2 Pods 2 VRFs OCP Primary network overlap [38;5;13m[1m[It] {"IPStack":"ipv4"}[0m …
```
=> cnf-tests: Avoid passing nil to `GetStringEventsForPodFn`

ztp/source-crs/ReduceMonitoringFootprint.yaml
- Grafana field is deprecated since version 4.11
- This change must be backported till 4.11
/assign @imiller0 @serngawy
=> ztp: CNF-10131 remove deprecated grafana field from reduce footprint CR

cnf-tests/testsuites/pkg/networks/sriov.go
When creating SriovNetworkNodePolicy, the delay before seeing an SriovNetworkNodeState going to `InProgress` can be a little longer than 5 seconds. e.g. `[multinetworkpolicy]` test suite showed falky failures in this sense [1]:
```
// sriov-network-operator
2023-10-23T21:04:41.069865775Z	INFO	SriovNetworkNodePolicy	Enqueuing sync for create event	{"resource": "test-policy-d2q2g"}
...
2023-10-23T21:04:42.080418658Z	INFO	syncAllSriovNetworkNodeStates	Sync SriovNetworkNodeState CR	{"name": "cnfdu3"}
// cnfdu3 sriov-config-daemon
I1023 21:04:42.113860  148878 daemon.go:536] nodeStateSyncHandler(): calling OnNodeStateChange for an updated node state
...
I1023 21:04:46.605306  148878 writer.go:170] setNodeStateStatus(): syncStatus: InProgress, lastSyncError:
```
[1] …
=> cnf-tests: Increase delay in WaitStable

Makefile
Currently, the "test-bin" target invokes the "init-git-submodules".
This is, in his turn, invoke "fetch -all" which creates connection
to the public github repo. However, in Red Hat's mid-stream container
image builder, we are creating the image in a disconnected environment.
So here we remove the call to the "init-git-submodules" target,
and instead only invoke "git submodule update --init --force".
Also because we only care about the latest commit of the NTO.
=> Fix cnf-tests container build

ztp/ran-crd/site-config-crd.yaml
Description:
- as this is not a CRD that lives on an actual cluster and it's not (yet) generated as customary operator CRDs, the CRD yaml schema was manually modified to include the v2 version.
- both versiones are served, but just v2 has 'storage: true' to show that v2 is the recommended version.
=> ztp: Add V2 to the SiteConfig CRD

ztp/extra-manifests-builder/99-sync-time-once/build.sh, ztp/source-crs/extra-manifest/99-sync-time-once-master.yaml, ztp/source-crs/extra-manifest/99-sync-time-once-worker.yaml
This PR fixes a contention between chronyd sync-time-once services on boot. The latter service is needed for systems with PTP enabled, so it should only run on hosts with chronyd.service disabled. This fix adds an execution condition for sync-time-once, so it will only start when chronyd is disabled.
/cc @lack @sabbir-47 @imiller0
=> ztp: OCPBUGS-21740: fix sync-time-once / chronyd contention

ztp/extra-manifests-builder/99-sync-time-once/build.sh, ztp/source-crs/extra-manifest/99-sync-time-once-master.yaml, ztp/source-crs/extra-manifest/99-sync-time-once-worker.yaml
The `sleep 30` in ExecCondition was left by mistake
=> ztp: remove chrony sync ExecCondition sleep

cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go
If the first node in the list returned by
`sriovcluster.DiscoverSriov(...)` doesn't have devices
on multiple NUMA nodes, check if the other nodes can
be used for the test suite.
Fixes
- https://github.com/openshift-kni/cnf-features-deploy/issues/1688
cc @evgenLevin, @gregkopels
=> cnf-tests: look for suitable node for SRIOV/NUMA

cnf-tests/testsuites/e2esuite/multinetworkpolicy/multinetworkpolicy_sriov.go
IPv6 is now supported by MultiNetwork Policy Iptables implementation [1]
[1] https://github.com/k8snetworkplumbingwg/multi-networkpolicy-iptables/issues/22
=> cnf-tests: Multinetwork Policy IPv6

ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-3node-ranGen-templated.yaml, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-sno-ranGen-templated.yaml, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-standard-ranGen-templated.yaml, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/kustomization.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-3node-ranGen-templated.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-sno-ranGen-templated.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-standard-ranGen-templated.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml
- Create all the group policies in the ztp-group namespace
- Comment out all the source files that are also commented out in the non templated PG(T)s
- Comment out templated policies from the kustomization file, but leave comments about using either the templated or the non templated policies. This makes the examples usable as is without further action needed by users. If the hub templated policies are desired, they should be uncommented and the non templated policies should be commented out to avoid overlaps.
=> ztp: Cleanup hub templating to better match non templated examples

cnf-tests/testsuites/e2esuite/multinetworkpolicy/reachmatcher.go
Since v7.92, ncat timeout error message has changed from
```
Ncat: Connection timed out
```
to
```
Ncat: TIMEOUT
```
See
https://github.com/nmap/nmap/commit/4824a5a0742a77f92c43eb5c9d9c420d56dbadcc
This commit makes the ReachMatcher, used by the
`[multinetworkpolicy]` suite, able to work with both version of ncat.
This problem first appeared in `v4.12.7-2`:
```
docker run registry-proxy.engineering.redhat.com/rh-osbs/openshift4-cnf-tests:v4.12.7-1 ncat -version -w 1 192.168.2.2 
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection timed out.
docker run registry-proxy.engineering.redhat.com/rh-osbs/openshift4-cnf-tests:v4.12.7-2 ncat -version -w 1 192.168.2.2
Ncat: Version 7.92 ( https://nmap.org/ncat )
Ncat: TIMEOUT.
```
See brew builds …
=> cnf-test: Fix `ncat` timeout error message

hack/run-functests.sh
Ginkgo V2 decreased the default suite timeout from `24h` to `1h`. This commit sets the default value to 6h, as cnf-tests suite is likely to run for more than 1h.
https://onsi.github.io/ginkgo/MIGRATING_TO_V2#timeout-behavior
cc @evgenLevin, @gregkopels
=> cnf-tests: Increase `ginkgo.timeout`

ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-3node-ranGen-templated.yaml, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-sno-ranGen-templated.yaml, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-standard-ranGen-templated.yaml, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/configMaps/group-hardware-types-configmap.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/configMaps/group-hardware-types-configmap.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-3node-ranGen-templated.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-sno-ranGen-templated.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-standard-ranGen-templated.yaml
Description:
- make the hardware type platform agnostic
- update the MachineConfig examples to match their own CPU values and those under PerformanceProfile
=> ztp: Make PG examples more general consistent

hack/common.sh
Remove the NTO's 4_latency test suite from the `TESTS_PATHS` variable, to prevent the functests from running this test suite.
We need that because we want to remove the "LATENCY_TEST_RUN" variable, which always skipped this suite during the conformance tests.
For clarity - the "LATENCY_TEST_RUN" was necessary when we compiled all of the suites together in the cnf-tests container image, but now it's redundant.
=> cnf-tests: Remove NTO's 4_latency test suite

ztp/ran-crd/site-config-crd.yaml
Adds `cpuPartitioningMode` description to the siteConfig CRD, allowing users looking to write their siteconfigs to know the supported field name and the possible values that can be specified.
=> ztp: Add cpuPartitioningMode to site-config-crd

cnf-tests/entrypoint/test-run.sh
Modify the 'test-run.sh' script, which serves as the entry point for the latency tests, and set the DISCOVERY_MODE variable to true. This adjustment eliminates the need for users to set it manually. However, users still have the option to override the variable and set it to 'false' if desired.
=> cnf-tests: Set DISCOVERY_MODE to true by default

hack/setup-build-index-image.sh
When wget prints Github link there is an AWS key in the output, which make Prow to remove all build logs (because of removing everything that similar to AWS keys).
Make wget non-verbose to hide this info and prevent Prow to delete build logs.
=> infra: Reduce wget verbosity to unhide tests logs in Prow

cnf-tests/Dockerfile, cnf-tests/Dockerfile.openshift
Binaries built in RHEL9 are not compatible with RHEL8 runtime image.
This commit should fix failing test cases:
```
[It] [sctp] Test Connectivity Connectivity between client and server  ...
```
refs:
- https://github.com/openshift-kni/cnf-features-deploy/pull/1736
This PR is an alternative to:
- https://github.com/openshift-kni/cnf-features-deploy/pull/1749
until we find a substitution for libhugetlbfs
=> cnf-tests: revert test image to rhel8

.snyk
Add a '.snyk' file to exclude the vendor directory for
the snyk code analysis.
=> Add .snyk file for static code analysis

ztp/resource-generator/Containerfile
Revert base image to rhel-8 in the ztp's Containerfile, due to failures building the new ztp image.
=> ztp: revert base image to RHEL8

cnf-tests/entrypoint/test-run.sh
Flags that passed to shell script, are now drilled down to latency-e2e.test executable. This resolves an issue when running latency tests by using cnf tests container with command line arguments had no effect and these arguments were ignored.
More info here:
https://issues.redhat.com/browse/OCPBUGS-27158
=> cnf-tests: Pass command line arguments to latency-e2e.test

ztp/siteconfig-generator/siteConfig/siteConfig.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go, ztp/siteconfig-generator/siteConfig/testdata/nmstateconfig.yaml
If the user ommits the NodeNetwork details from the siteConfig but includes it in an crTemplate over-ride of NMStateConfig, we end up not generating the NMStateConfig because we think the network is empty. Check if the user did not include an over-ride before skiping the NMStateConfig generation.
=> OCPBUGS-27031: Don't skip a NMStateConfig over-ride

ztp/gitops-subscriptions/Makefile
Latest version of policygenerator breaks CI with the error message:
go: open-cluster-management.io/policy-generator-plugin/cmd/PolicyGenerator@latest (in open-cluster-management.io/policy-generator-plugin@v1.13.0):
The go.mod file for the module providing named packages contains one or
more replace directives. It must not contain directives that would cause
it to be interpreted differently than if it were the main module.
make: *** [Makefile:27: build] Error 1
=> ztp: [4.15] pin policygenerator version to v1.12.4

cnf-tests/entrypoint/test-run.sh
This PR cherry-picks both commits:
638c6c2: cnf-tests: Set DISCOVERY_MODE to true by default
and
ed12344: cnf-tests: Pass command line arguments to latency-e2e.test
Please note: the declared bug, is fixed by the second commit and the first one
is a fix we merged to latest and wasn't backported from some reason.
=> OCPBUGS-27158: Pass command line arguments to latency-e2e.test

.snyk
Currently the SAST workflow that we are adding to cnf-features-deploy repo fails for the following reason: Could not parse ignore rules to glob { path: '/go/src/github.com/openshift-kni/cnf-features-deploy/.snyk' } Please make sure ignore file follows correct syntax The failure occurs in "snyk code test" command that is used in the security workflow. By changing the current .snyk file content to a new one the parsing of the file is successful and so is the security scanning.
=> cnf-tests: Fixes snyk file content

cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go
Add a step to clean the configuration after the `sriov/NUMA` test suite has been finished.
This is important because other test suites could expect to find a clean and stable cluster state.
=> cnf-tests: `sriov/numa` clean configuration

ztp/gitops-subscriptions/Makefile
Latest version of policygenerator breaks CI with the error message:
go: open-cluster-management.io/policy-generator-plugin/cmd/PolicyGenerator@latest (in open-cluster-management.io/policy-generator-plugin@v1.13.0):
The go.mod file for the module providing named packages contains one or
more replace directives. It must not contain directives that would cause
it to be interpreted differently than if it were the main module.
make: *** [Makefile:27: build] Error 1
=> ztp: pin policygenerator version to v1.12.4

Makefile
This commit modifies the Makefile, creating a distinct Makefile target for the ZTP CI job. This adjustment aims to prevent conflicts in case of issues on the ZTP side, effectively blocking merges for the CNF-Tests component.
Alongside this commit, we will introduce a new Prow job in the openshift/release repository. This job will activate the new target but exclude it for changes exclusive to CNF-Tests.
For the release repo part see: https://github.com/openshift/release/pull/47936
=> Separate ZTP and CNF-Tests CI Jobs

ztp/gitops-subscriptions/argocd/example/README.md, ztp/gitops-subscriptions/argocd/example/image-based-upgrades/README.md, ztp/gitops-subscriptions/argocd/example/image-based-upgrades/example-oadp-policy.yaml, ztp/gitops-subscriptions/argocd/example/image-based-upgrades/kustomization.yaml, ztp/source-crs/ibu/PlatformBackupRestore.yaml
The required OpenShift platform-related OADP backup and restore CRs for performing image based upgrades (IBU) is added under the `source-crs` directory. Specifically, a new `ibu` sub-directory is created to house all IBU related content.
The example directory is also updated to provide reference deployment samples to the user.
=> ztp: CNF-9622: Create IBU platform OADP backup and restore CRs

cnf-tests/testsuites/e2esuite/fec/fec.go
Adding dynamic secureBoot verification.
If secure boot enabled SriovFecClusterConfig resources gets updated with the correct pfDriver configuration vfio-pci
=> cnf-tests: Fix fec secure boot test case

ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go, ztp/siteconfig-generator/siteConfig/siteConfigHelper_test.go, ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml, ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml, ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/01-predefined-mc-master.yaml, ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/01-predefined-mc-worker.yaml, ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/image-registry-partition-mc.yaml.tmpl, ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/workload/03-workload-partitioning.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigV2TestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/01-container-mount-ns-and-kubelet-conf-master.yaml, ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/01-container-mount-ns-and-kubelet-conf-worker.yaml, ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/04-accelerated-container-startup-master.yaml, ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/04-accelerated-container-startup-worker.yaml, ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/06-kdump-master.yaml, ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/06-kdump-worker.yaml, ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/disk-encryption.yaml.tmpl, ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/image-registry-partition-mc.yaml.tmpl, ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/workload/03-workload-partitioning.yaml
This version bump in the test cases is needed because the machine-config-operator version bumped the coreos/ignition depededency.
Fixes `ci/prow/ztp-ci`
refs:
- https://github.com/openshift/machine-config-operator/commit/79286c5dbd07169eb93a66e7d8f196cb81a7636d
/cc @jzding
=> ztp: Bump ignition testdata version from `3.2.0` to `3.4.0`

ztp/siteconfig-generator/main.go, ztp/siteconfig-generator/siteConfig/siteConfigHelper.go
Description:
- When there is an error in SiteConfig, add the error as a field in the SiteConfig that's printed out.
Example:
```
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
labels:
app.kubernetes.io/instance: clusters
name: mgmt-spoke1
namespace: mgmt-spoke1
siteConfigError: >-Error: could not build the entire SiteConfig defined by/tmp/kust-plugin-config-2679372: stat custom-manifests/: no such file or directory spec: ...
```
- Include a new parameter to the siteconfig-generator utility, stopOnError. When this field is set to true, the siteconfig-generator completely halts and does not continue if an error is detected. If the field is set to false, the siteconfig-generator prints the SiteConfig with the error included and then continues to processing the next SiteConfig …
=> ztp: OCPBUGS-25820: Include SiteConfig error in SiteConfig Content

ztp/siteconfig-generator/siteConfig/clusterCRsV2.go, ztp/siteconfig-generator/siteConfig/siteConfig.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go, ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutputWithZap.yaml
This commit adds ZTP site-generator capabilities needed for ZAP (ZTP Accelerated Provisioning):
- allow multiple `manifestsConfigMapRefs` in ACI, instead of the deprecated `manifestsConfigMapRef`
- add second configmap reference to ACI and label the `managedCluster` when `ztp-accelerated-provisioning` label 
is added to siteConfig `clusterLabels` and has one of the two predefined values
/cc @imiller0 @lack
=> ztp: CNF-9748: Add ZAP labelling

cnf-tests/mirror/mirror.go, cnf-tests/pod-utils/pkg/node/node.go, cnf-tests/pod-utils/stresser/main.go, cnf-tests/testsuites/e2esuite/sctp/sctp.go, ztp/policygenerator/testSource/TestAssertions.go, ztp/policygenerator/testSource/TestGetters.go, ztp/policygenerator/testSource/TestHelpers.go, ztp/siteconfig-generator/siteConfig/filesHandler.go, ztp/tools/policy-object-template-diff/main.go
`ioutil` was deprecated back in [Go 1.16](https://go.dev/doc/go1.16).
=> cnf-tests: Deprecate ioutil

hack/setup-build-index-image.sh
This commit modifies the setup-build-index-image.sh script to print the logs of the Podman pod before checking if the index build succeeded. This improvement enhances debuggability because, currently, if the build fails, it does not display the logs, forcing us to consult the must-gather report.
=> cnf-tests: Print podman logs before the check

cnf-tests/testsuites/e2esuite/sctp/sctp.go, cnf-tests/testsuites/e2esuite/vrf/vrf.go, cnf-tests/testsuites/pkg/namespaces/namespaces.go
Similar to: https://github.com/openshift-kni/eco-goinfra/pull/239
Match references across the repo to make them uniform.
`k8sv1` --> `corev1`
`corev1` is used everywhere else in the project.
=> cnf-tests: Import consistency

go.mod, go.sum, vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/cluster/cluster.go, vendor/modules.txt
```
go mod download github.com/openshift/sriov-network-operator@release-4.14
github.com/openshift/sriov-network-operator@release-4.14
go mod tidy
go mod vendor
```
=> OCPBUGS-25794: cnf-tests: sriov-network-operator bump 4.14

hack/run-functests.sh
MetalLB now allows two modes of running, frr and frr-k8s. The test suite contains both and the expectation is to have the test runner picking one set of tests or the other. Here we enforce skipping frr-k8s from the run-functests.sh script.
=> infra: always skip frr-k8s tests

ztp/gitops-subscriptions/argocd/README.md, ztp/gitops-subscriptions/argocd/example/policygentemplates/common-mno-ranGen.yaml, ztp/policygenerator-kustomize-plugin/kustomization.yaml, ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/common-mno-ranGen.yaml, ztp/source-crs/OperatorHub.yaml
**Context:**
In 4.15 release, we removed [Openshift-market place operator](https://github.com/openshift-kni/cnf-features-deploy/commit/e21269dfa9915b195a79619ff23f1caeff1d95cb), which is not needed for SNO if a customer is manager its own catalog source. But, for MNO clusters will still require openshift-market place capability
**What changed?**
- Added a common-mno-ranGen.yaml file targeting MNO cluster
- OperatorHub.yaml file added back, and this is only require for MNO cluster
/assign @lack @imiller0
=> ztp: OCPBUGS-27893: OperatorHub.yaml is missing from the ztp source-crs

feature-configs/deploy/sriov/04-sriov-operator-config.yaml, feature-configs/deploy/sriov/kustomization.yaml
To align CI to PR
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/617
an `SriovOperatorConfig/default` needs to be created to make the SR-IOV network operator start working.
=> infra: Create `SriovOperatorConfig` while deploying

ztp/siteconfig-generator/main.go, ztp/siteconfig-generator/siteConfig/siteConfigHelper.go
This is a manual cherry-pick of #1818
Description:
- When there is an error in SiteConfig, add the error as a field in the SiteConfig that's printed out.
- Include a new parameter to the siteconfig-generator utility, stopOnError. When this field is set to true, the siteconfig-generator completely halts and does not continue if an error is detected. If the field is set to false, the siteconfig-generator prints the SiteConfig with the error included and then continues to processing the next SiteConfig file. stopOnError defaults to false.
=> [release-4.14] ztp: OCPBUGS-30886: Include SiteConfig error in SiteConfig Content

ztp/source-crs/PtpConfigSlaveCvl.yaml
This PR adds deprecated message to PtpConfigSlaveCvl.yaml file since   PtpConfigSlave.yaml and PtpConfigSlaveCvl.yaml are identical.
=> OCPBUGS-29706: PtpConfigSlave.yaml and PtpConfigSlaveCvl.yaml are identical

ztp/extra-manifests-builder/99-sync-time-once/build.sh, ztp/source-crs/extra-manifest/99-sync-time-once-master.yaml, ztp/source-crs/extra-manifest/99-sync-time-once-worker.yaml
This commit fixes a bug where a single-shot chronyd service starts too early, before the network is fully online, and fails on timeout.
/cc @sabbir-47 @lack
=> OCPBUGS-31496: ztp: start chrony after network online

cnf-tests/testsuites/pkg/execute/ginkgo.go
When the BeforeEach inside BeforeAll fails with a Ginkgo exception, subsequent tests (or retries of the first test) fail because the initial setup (code inside this BeforeEach) has not being executed. This change forces the BeforeEach to run again in case of failure.
=> Retry BeforeAll when initial setup fails

ztp/source-crs/extra-manifest/enable-cgroups-v1.yaml
Installations will have cgroups v2 enabled as the openshift default.
Performance profile no longer sets the cluster to cgroups v1 for 4.16 and above , see https://github.com/openshift/cluster-node-tuning-operator/pull/1010 .
Reverts https://github.com/openshift-kni/cnf-features-deploy/pull/1763 .
=> ztp: CNF-10965: Remove cgroups v1 enablement

ztp/source-crs/TunedPerformancePatch.yaml
For DU-profile, realTime workloadHint is set to true. When it is set to true, from the NTO operator side [kernel](https://github.com/openshift/cluster-node-tuning-operator/blob/master/assets/performanceprofile/tuned/openshift-node-performance#L73-L86) migration timer is already set. Therefore removing the redundant sysctl directive.
=> ztp: CNF-11960: remove kernel timer migration

ztp/siteconfig-generator/siteConfig/siteConfig.go, ztp/siteconfig-generator/siteConfig/siteConfig_test.go
- checking the number of master node to be greater than 1
- otherwise it blocks replacing faulty master nodes where master nodes can be less than 3 and for high availability case when it is more than 3 nodes.
=> ztp: OCPBUGS-32039: Siteconfig blocks MNO cluster deployment for more or less than 3 master nodes

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go, cnf-tests/testsuites/e2esuite/vrf/vrf.go, cnf-tests/testsuites/pkg/namespaces/namespaces.go, cnf-tests/testsuites/pkg/pods/pods.go
Doc: https://pkg.go.dev/k8s.io/utils@v0.0.0-20240102154912-e7106e64919e/pointer
`k8s.io/utils/pointer` has been deprecated and replaced with `k8s.io/utils/ptr`.
Bonus: `ztp/tools/policy-object-template-diff/main.go` was adjusted by `go fmt`.
=> cnf-tests: Deprecate k8s.io/utils pointer function

ztp/gitops-subscriptions/argocd/deployment/app-project.yaml
Allow the ztp-app-project AppProject to be able to sync ClusterImageSet CRs from git onto the hub cluster.
The ClusterImageSet is a cluster wide CR so we add its Group and Kind to the ClusterResourceWhitelist.
=> ztp: cnf-7840: Allow ClusterImageSet to be synced

ztp/gitops-subscriptions/argocd/example/image-based-upgrades/README.md, ztp/source-crs/ibu/PlatformBackupRestoreLvms.yaml
When LVMS is configured as the storage solution in the cluster, IBU will need to backup and restore the corresponding objects in order to properly preserve the PV's contents after pivoting. 
/cc @browsell @Missxiaoguo @sakhoury @sabbir-47 
Signed-off-by: Leonardo Ochoa-Aday <lochoa@redhat.com>
=> ztp: Add IBU platform OADP backup and restore CRs for LVMS

ztp/gitops-subscriptions/argocd/README.md
This is to add a note about using the reference argocd-openshift-gitops-patch.json ( [link](ztp/gitops-subscriptions/argocd/deployment/argocd-openshift-gitops-patch.json)) in disconnected environments where the image urls contained in the file may need to be adpated.
=> OCPBUGS-32756: Add documentation to explain how to select the multicluster-operators-subscription image

ztp/siteconfig-generator/siteConfig/siteConfigHelper_test.go
Enabling fips in site-config requires setting fips=true as a boolean in the installConfigOverrides, which means no quotes around the `true`. Having it quoted means it is read as a string and fails to install.
This update has no functional change, it just fixes the test case that includes fips in the installConfigOverrides string, removing the quotes around `true`.
=> ztp: Fix fips=true tag in siteconfig-generator test code

ztp/gitops-subscriptions/argocd/example/image-based-upgrades/README.md, ztp/gitops-subscriptions/argocd/example/image-based-upgrades/acm-ibu-upgrade-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/image-based-upgrades/ibu-upgrade-ranGen.yaml, ztp/source-crs/ibu/ImageBasedUpgrade.yaml, ztp/source-crs/ibu/ImageBasedUpgradeStatus.yaml
- since the IBU apiVersion is changed to v1 in https://github.com/openshift-kni/lifecycle-agent/pull/497, update the source cr in ztp repo
- typo fix in doc
- small update in prep policy for adding message field in status condition
/cc @leo8a @pixelsoccupied @sabbir-47
=> ztp: change IBU source cr to v1

ztp/source-crs/StorageLVMSubscriptionNS.yaml
This adds a namespace annotation so that the LVMS workloads will be scheduled into the management core set instead of the isolated cores.
=> CNF-12277: chore: move LVMS to mgmt cores

ztp/source-crs/PtpConfigDualCardGmWpc.yaml, ztp/source-crs/PtpConfigGmWpc.yaml
This commit enables NAV-TIMELS indications on WPC T-GM
configurations. This is required to enable automatic
leap seconds file update.
The phc2sys options are also changed to obtain the leap
seconds from phc instead of passing  them as the command
line argument
/cc @josephdrichard @jzding @aneeshkp @nishant-parekh
=> OCPBUGS-33597: Add TIMELS indication on T-GMs

ztp/source-crs/TunedPerformancePatch.yaml
fix typo 
s/ice-dppls/ice-dplls/
=> OCPBUGS-34064: ZTP tuned patch typo: s/ice-dppls/ice-dplls/ 

ztp/source-crs/PtpConfigBoundaryForEvent.yaml, ztp/source-crs/PtpConfigForHAForEvent.yaml, ztp/source-crs/PtpConfigMasterForEvent.yaml, ztp/source-crs/PtpConfigSlaveForEvent.yaml
Current source crs PTP doesn't have any reference config for events .
This PR  copies non event PTPConfig  as new file with 'ForEvent' prefix and adds events required ptp  options to the config .
ztp/source-crs/PtpConfigBoundaryForEvent.yaml
ztp/source-crs/PtpConfigForHAForEvent.yaml
ztp/source-crs/PtpConfigMasterForEvent.yaml
ztp/source-crs/PtpConfigSlaveForEvent.yaml
=> OCPBUGS-34603:  Add a new set of PTP configurations for events in source CRs with additional PTP options

ztp/source-crs/PtpConfigForHA.yaml
In linuxPTPDaemon, a string containing a space character (" ") is not considered nil, whereas an empty string ("") is considered nil. The nil value determines whether to execute the processes related to the configured Opts.
For an example 
1. ptp4lOpts: " "  will run the ptp4l process with empty options 
2. ptp4lOpts:  ""  will not  run the ptp4l process
=> OCPBUGS-33524: change ptp4lOpts from empty spaced string to null

ztp/source-crs/PtpConfigDualCardGmWpc.yaml, ztp/source-crs/PtpConfigGmWpc.yaml
This PR Updates ptpconfig to configure the hardware plugin to periodically send the u-blox command NAV-TIMELS via the UBX-CFG-MSG message. NAV-TIMELS carries information about leap dates and offsets.
Required for T-WPC leap events cc @vitus133
=> OCPBUGS-35105: Update ptpconfig to configure NAV-TIMELS to be periodically sent via the UBX-CFG-MSG message

ztp/gitops-subscriptions/argocd/example/optional-extra-manifest/ipsec/enable-ipsec.yaml
For IPsec support for encrypting traffic to external hosts OVN-Kubernetes network plugin must be configured in local gateway mode
=> OCPBUGS-33573: ztp: IPsec: configure local gateway mode

ztp/gitops-subscriptions/argocd/deployment/policies-app-project.yaml
We are managing the ClusterImageSets through the policies, as a result we need this in the whitelist of policies-app-project, otherwise the sync will fail due to error below:
`time="2024-06-11T17:44:46Z" level=info msg="Adding resource result, status: 'SyncFailed', phase: '', message: 'resource hive.openshift.io:ClusterImageSet is not permitted in project policy-app-project'" application=openshift-gitops/policies kind=ClusterImageSet name=cluster-image-set-4-14-25-20240606 namespace=policies-sub phase=Sync syncId=00006-pQxCU`
Similar PR for app-project: https://github.com/openshift-kni/cnf-features-deploy/pull/1880
=> Add ClusterImageSet CR in the whitelist of policies-app-project

README.md, cnf-tests/README.md
This commit updates the CNF-tests README to reflect the changes introduced in the CNF-tests split modification.
All the previous details about the latency tests have been removed, and a reference to the official documentation has been provided.
=> cnf-tests: Update README.md

ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-common-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-example-sno-site.yaml, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-sno-ranGen-templated.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-sno-ranGen-templated.yaml, ztp/source-crs/LcaOperatorStatus.yaml, ztp/source-crs/LcaSubscription.yaml, ztp/source-crs/LcaSubscriptionNS.yaml, ztp/source-crs/LcaSubscriptionOperGroup.yaml, ztp/source-crs/OadpBackupStorageLocationStatus.yaml, ztp/source-crs/OadpDataProtectionApplication.yaml, ztp/source-crs/OadpOperatorStatus.yaml, ztp/source-crs/OadpSecret.yaml, ztp/source-crs/OadpSubscription.yaml, ztp/source-crs/OadpSubscriptionNS.yaml, ztp/source-crs/OadpSubscriptionOperGroup.yaml
- Include source crs for LCA and OADP operators used for image based upgrade
- Provide reference examples in the policygentemplates and acmpolicygenerator
For EPIC: https://issues.redhat.com/browse/CNF-10498
/cc @browsell @pixelsoccupied @imiller0
=> ztp: add install and config CRs for LCA and OADP operators

hack/verify-commits.sh
These commits were merged in 4.16 and skipped the syntax verification:
1ccd7824 Revert "Add ClusterImageSet CR in the whitelist of policies-app-project"
c8187edc Add ClusterImageSet CR in the whitelist of policies-app-project
They don't respect the component syntax defined on .githooks/components.sh so any posterior syntax verification makes commits fail Prow tests.
We need this hack to skip the syntax checking.
=> infra: fixes branch to build the list of commits

cnf-tests/Dockerfile, cnf-tests/Dockerfile.openshift, openshift-ci/Dockerfile.tools
Prow jobs like `e2e-aws-ci-tests` uses runs using the `openshift-ci/Dockerfile.tools` iamge. (See https://github.com/openshift/release/blob/0a257490e7c4aba7c6164bd79626791ed3dae819/ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master.yaml#L21, where the job has `from: src` and the file has
```
build_root:
project_image:
dockerfile_path: openshift-ci/Dockerfile.tools
```)
This bump is needed because a submodule (cluster-node-tuning-operator in this case) bumped to go1.22 and jobs are reporting the error:
```
go: errors parsing go.mod:
/go/src/github.com/openshift-kni/cnf-features-deploy/cnf-tests/submodules/cluster-node-tuning-operator/go.mod:3: invalid go version '1.22.0': must match format 1.23 …
```
=> infra: Bump go v1.22 in CI jobs

cnf-tests/testsuites/e2esuite/dpdk/dpdk.go, cnf-tests/testsuites/e2esuite/s2i/s2i.go, tools/s2i-dpdk/test/test-app/run.sh
Guaranteed workload pods can be in a different cgroup if on the node there has been applied a PerformanceProfile.
The Cluster Node Tuning Operator configures the cpuset cgroup on specific condition and it doesn't come back to the original configuration when the node is moved to a differenent MachineConfigPool.
Update the DPDK test cases' logic to retrieve the list of dedicated CPUs.
Refs:
- https://github.com/openshift/cluster-node-tuning-operator/blob/a4c70abb71036341dfaf0cac30dab0d166e55cbd/assets/performanceprofile/scripts/cpuset-configure.sh#L9
- https://github.com/openshift-kni/cnf-features-deploy/pull/1592/commits/d2e763a91476a8891bfdd55c0add46a610c6da7f
- https://github.com/openshift-kni/cnf-features-deploy/issues/1902
cc @gregkopels , @ffromani
=> cnf-tests: Read guaranteed CPU list for cgroupv2

feature-configs/hypershift-ci/metallb/kustomization.yaml, feature-configs/hypershift-ci/metallb/operator_subscription.yaml, feature-configs/hypershift-ci/multinetworkpolicy/kustomization.yaml, feature-configs/hypershift-ci/ptp/kustomization.yaml, feature-configs/hypershift-ci/ptp/subscription.yaml, feature-configs/hypershift-ci/s2i/kustomization.yaml, feature-configs/hypershift-ci/s2i/post_deploy.sh, feature-configs/hypershift-ci/sriov/kustomization.yaml, feature-configs/hypershift-ci/sriov/sriov-subscription.yaml, hack/common.sh, hack/setup-test-cluster.sh
Create a feature-config for Hypershift which doesn't include
anything not supported like MachineConfigs for example.
Add a special variable for setting hypershift environment to avoid
setting MachineConfigs in the script.
=> infra: Create a special hypershift-ci feature config

ztp/source-crs/PtpConfigForHAForEvent.yaml
The ptp4lOpts should be set to an empty string without any spaces for setting up the HA profile in PTP. This PR addresses the issue by removing the unintended empty space.
=> OCPBUGS-36695: remove space from ptp4lopts for PTP HA

cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go, cnf-tests/testsuites/pkg/nodes/nodes.go, cnf-tests/testsuites/pkg/utils/consts.go
for env like hypershift we don't have MCO so we need to use the sriov-config-daemon that is running on the cluster
=> cnf-tests: use sriov config daemon for exec instead of mco

ztp/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml, ztp/kube-compare-reference/required/ptp-operator/PtpConfigGmWpc.yaml
Match the PTP config to the source crs (source of truth) and set the realtime kernel as allowable variation (though RT is recommended)
=> ztp: Fix diffs between ref and source-crs

ztp/siteconfig-generator/siteConfig/siteConfig.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
Accelerated ZTP relies on ZTP adding a second ConfigMap reference in the AgentClusterInstall CR.  However, SiteConfig v1 only supports adding a single ConfigMap reference through the manifestsConfigMapRef field of the AgentClusterInstall CR.
This fix changes manifestsConfigMapRef to manifestsConfigMapRefs and allows adding the second ConfigMap reference.  It only does that if SiteConfig v1 is used and the "accelerated-ztp" label is found on the SiteConfig to be backward compatible.
Also changed the unit-test to test with v1 siteConfig
=> ztp: OCPBUGS-37572: Fix aZTP for SiteConfig v1

Makefile
Makefile rule `init-git-submodules` reads environment variables `METALLB_OPERATOR_TARGET_COMMIT`, `SRIOV_NETWORK_OPERATOR_TARGET_COMMIT`, `CLUSTER_NODE_TUNING_OPERATOR_TARGET_COMMIT` to
checkout the right branch for each submodules.
Though we need to find a better way to manage these dependency, this commit prevents Prow jobs to checkout master branch in 4.16 jobs.
=> [release-4.16] infra: Updated submodules refs

ztp/kube-compare-reference/metadata.yaml, ztp/kube-compare-reference/optional/local-storage-operator/StorageLV.yaml, ztp/kube-compare-reference/optional/local-storage-operator/StorageOperGroup.yaml, ztp/kube-compare-reference/optional/sriov-fec-operator/AcceleratorsOperGroup.yaml, ztp/kube-compare-reference/optional/storage/StorageLVMSubscriptionOperGroup.yaml, ztp/kube-compare-reference/required/cluster-logging/ClusterLogOperGroup.yaml, ztp/kube-compare-reference/required/cluster-tuning/operator-hub/DisconnectedICSP.yaml, ztp/kube-compare-reference/required/lca/LcaSubscriptionOperGroup.yaml, ztp/kube-compare-reference/required/ptp-operator/PtpSubscriptionOperGroup.yaml, ztp/kube-compare-reference/required/sriov-operator/SriovSubscriptionOperGroup.yaml
Assert default upgradeStrategy for OperatorGroup (the operator adds/prints the default value and we want to be explicit about requiring the default value)
Allow flexibility in storage operator (allowable 4.15+).
Fix handling of ICSP.
=> Minor cleanup of annotated reference config

ztp/gitops-subscriptions/argocd/deployment/app-project.yaml
CNF-12633 Add ClusterInstance to the set of allowable CR types to be synchronized via gitops. This CR is part of the SiteConfig operator which will allow cluster deployment from a ClusterInstance CR.
=> ztp: Add ClusterInstance to allowable CR types

ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
In the 4.17 RAN RDS, we want to have secure boot enabled as the recommended default boot mode, which is the mode that our System Test enables in their testing of the RAN RDS (this can optionally be disabled by changing bootMode back to just "UEFI").
=> ztp: make UEFISecureBoot default in 4.17 example yamls

ztp/gitops-subscriptions/argocd/deployment/clusters-app.yaml
after some investigations, ArgoCD deletion by
default is done in foreground mode. The opposite
than Kubernetes/Openshif that deletes on
background.
this seems to be creating issues deleting
ManagedClusters with observability enabled, and
not all the resources are cleaned correctly.
solves [CNF-13673)](https://issues.redhat.com/browse/CNF-13673)
=> ztp: Change ArgoCD apps default deletion behavior

ztp/siteconfig-generator/siteConfig/siteConfig.go, ztp/siteconfig-generator/siteConfig/siteConfig_test.go
- checking the number of master node to be greater than 1
=> [release-4.15] ztp: OCPBUGS-32918: Siteconfig blocks MNO cluster deployment for more or less than 3 master nodes

ztp/gitops-subscriptions/argocd/README.md, ztp/gitops-subscriptions/argocd/deployment/allow-acm-managedcluster-control.json, ztp/gitops-subscriptions/argocd/deployment/clusters-app.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/KlusterletAddonConfigOverride.yaml, ztp/siteconfig-generator/siteConfig/clusterCRsV1.go, ztp/siteconfig-generator/siteConfig/clusterCRsV2.go, ztp/siteconfig-generator/siteConfig/siteConfig.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go, ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingArgocdAnnotation.yaml, ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingMetadata.yaml, ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingMetadataAnnotations.yaml, ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-NotTemplated.yaml, ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride.yaml, ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml, ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutputWithZap.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigV2TestOutput.yaml
- Starting acm 2.4 `KlusterletAddonConfig` no longer supports `clusterLabels` in spec. 
- Removed all the instance of it from code.
- Starting acm 2.10 `Managecluster` CR requires `vendor` label for observability stack to work correctly.
- if user provides `vendor` and/or `cloud` label through Siteconfig we will respect it
- otherwise we will add `vendor` and `cloud` with the value `auto-detect`
- Because `auto-detect` will get replace by ACM (e.g with `OpenShift` for `vendor` key and `Other` for the key `cloud`)...we have to configure argoCD app to allow this change using `RespectIgnoreDifferences`
The change needed for argoCD app may have impact on performance.
An equivalent change will be in Siteconfig operator 
/cc @imiller0 
/cc @irinamihai 
/cc @sabbir-47
=> OCPBUGS-38489: ztp: remove unsupported KlusterletAddonConfig clusterLabels and update managecluster CR to include cloud and vendor label

ztp/kube-compare-reference/metadata.yaml
This is not a required part of the DU RDS, but an optional component.
=> OCPBUGS-39095: ztp: DU reference should mark LCA operator as optional

ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHA.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHAForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigMaster.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlave.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveCvl.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveForEvent.yaml, ztp/kube-compare-reference/optional/storage/StoragePV.yaml, ztp/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml, ztp/kube-compare-reference/validate_node_selector.tmpl
This is needed both for templates where the node selector is a value and
not a yaml key:value mapping, as well as for forthcoming efforts to
introduce tooling to keep the reference config and source-crs in sync.
=> ztp: Reference: Replace the node selector reference logic with something more flexible

ztp/kube-compare-reference/metadata.yaml
=> OCPBUGS-39104: ztp: Reference: Make OperatorHub and DisableOLMPprof optional

ztp/source-crs/PtpConfigDualCardGmWpc.yaml, ztp/source-crs/PtpConfigGmWpc.yaml, ztp/source-crs/TunedPerformancePatch.yaml
This commit enables NAV-TIMELS indications on WPC T-GM configurations. This is required to enable automatic leap seconds file update.
The phc2sys options are also changed to obtain the leap seconds from phc instead of passing  them as the command line argument.
In addition, it fixes a typo in Tuned patch allowing correct ice dpll scheduling
This is is a manual cherry-pick of #1931, #1943, #1922 and #1975
=> OCPBUGS-38670: ztp: enable automatic leap second handlling

ztp/gitops-subscriptions/argocd/README.md
- The link in the README has to be relative to its own directory to link correctly
- Previously the link would direct you to the non existant path "https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/gitops-subscriptions/argocd/ztp/gitops-subscriptions/argocd/deployment/argocd-openshift-gitops-patch.json"
- Now it should direct you correctly to "https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/gitops-subscriptions/argocd/deployment/argocd-openshift-gitops-patch.json"
=> ztp: Fix link to argocd patch in README

ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
This includes a fix for the ZTP siteconfig-generator panic if an empty file exists in the extra-manifest directory.
The condition checks and ignores empty files silently.
Also includes a unit test for testing the scenario with empty file.
/cc @sabbir-47
=> OCPBUGS-39149: ztp: ignore empty file in siteconfig extra manifests

ztp/gitops-subscriptions/argocd/example/optional-extra-manifest/ipsec/README.md
The files names in this section are incorrect.
=> ztp: IPsec: fix wrong files names

ztp/source-crs/ibu/PlatformBackupRestoreWithIBGU.yaml
When using ibgu,
`rbac.authorization.k8s.io/v1/clusterroles/open-cluster-management:klusterlet-work:ibu-role` should be added to apply-label annotation. This ClusterRole is needed to be resotred after pivot so that cgu can see the status of IBU.
=> ztp: Add PlatformBackupRestoreWithIBGU to source-crs

ztp/Makefile, ztp/kube-compare-reference/.gitignore, ztp/kube-compare-reference/Makefile
This doesn't make sure we are in sync with source-crs yet, but at least
it ensures our metadata.yaml isn't accidentally broken.
=> ztp: reference: Add a CI check to ensure the reference metadata syntax is okay

ztp/kube-compare-reference/required/cluster-logging/ClusterLogServiceAccountAuditBinding.yaml, ztp/kube-compare-reference/required/cluster-logging/ClusterLogServiceAccountInfrastructureBinding.yaml, ztp/source-crs/ClusterLogServiceAccountAuditBinding.yaml, ztp/source-crs/ClusterLogServiceAccountInfrastructureBinding.yaml
- ClusterRoleBindings do not have namespaces, and it is currently being ignored when the resources are created
=> ztp: CNF-14458: Remove namespace from ClusterLogServiceAccount ClusterRoleBindings

ztp/kube-compare-reference/metadata.yaml, ztp/kube-compare-reference/optional/image-registry/ImageRegistryConfig.yaml
=> OCPBUGS-39093: ztp: reference: Fix ImageRegistryConfig.yaml to not show differences for null values

ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
This MR includes a check to safely ignore empty file in testUserExtraManifest consumed by siteconfig-generator-kustomize-plugin, which caused addZTPAnnotationToManifest to panic.
This is an additional MR for addressing a missed scenario from 
https://github.com/openshift-kni/cnf-features-deploy/pull/2022
=> OCPBUGS-39149: ztp: empty file in sitegen kustomize plugin

ztp/kube-compare-reference/Makefile, ztp/kube-compare-reference/compare.sh, ztp/kube-compare-reference/default_value.yaml
This PR includes the following changes:
1. The helm-convert tool is used to generate helm chart from reference files and default_value.yaml;
2. The helm template cmd is used to render chart to CR files;
3. Using script compare.sh to compare the rendered CR files with source-crs.
=> ztp: Added compare script to compare rendered CRs with source-crs

ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-standard-ranGen.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
This is to fix a typo in ptp templates using interface ens6f0 instead of interface enf5f0 and phc2sysOpts: "-a -r -n 25" instead of phc2sysOpts: "-a -r -n 24"
=> CNF-14780: fix ptp templates

ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/README.md, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-clo5-cleanup.yaml, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/kustomization.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-clo5-cleanup-policy.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-sno-ranGen-templated.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml, ztp/kube-compare-reference/required/cluster-logging/ClusterLogForwarder.yaml, ztp/kube-compare-reference/required/cluster-logging/ClusterLogServiceAccount.yaml, ztp/kube-compare-reference/required/cluster-logging/ClusterLogServiceAccountAuditBinding.yaml, ztp/kube-compare-reference/required/cluster-logging/ClusterLogServiceAccountInfrastructureBinding.yaml, ztp/source-crs/ClusterLogForwarder.yaml, ztp/source-crs/ClusterLogServiceAccount.yaml, ztp/source-crs/ClusterLogServiceAccountAuditBinding.yaml, ztp/source-crs/ClusterLogServiceAccountInfrastructureBinding.yaml, ztp/source-crs/ClusterLogging5Cleanup.yaml, ztp/source-crs/ClusterLogging5Cleaup.yaml
The service account "logcollector" is owned by the Cluster Logging Operator version 5.x. If we use the same name for our user-created SA the upgrade from 5.x to 6.0 will delete the SA resulting in a loss of logging. Use log6collector to make it unique.
=> OCPBUGS-42750: Support upgrade from Cluster Logging 5.x to 6.0

ztp/source-crs/SriovFecClusterConfig.yaml, ztp/source-crs/SriovVrbClusterConfig.yaml
This PR:
- Adds support for the Intel vRAN Boost v2 (vrb2) accelerator in ZTP via a new source CR called SriovVrbClusterConfig.  This is necessary to support changes in the Intel authored SR-IOV FEC Operator to support this accelerator.
- Updates documentation links for Intel's ACC100 and ACC200 accelerators, as the links were no longer correct and giving 404s.  Note that the Intel N3000 FPGA is a discontinued product, so I have removed references to it: https://www.intel.com/content/www/us/en/content-details/724231/product-discontinuance-notification-pdn2211.html
The source Custom Resource I am including contains:
- wave set to 10 as any other configuration manifest
- drainskip set to optional. 
- bbDevConfig is referenced and it is expected that the user will provide the appropriate …
=> ztp: CNF-14762: add vrb2 and update refs

ztp/resource-generator/Containerfile
We should include the reference in the container so customers don't have to go upstream for the reference.
=> Build-in the RAN reference to the ZTP container

openshift-ci/Dockerfile.tools
Fixes failing CI job after golang was updated to 1.21 for release-4.16
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-openshift-kni-cnf-features-deploy-release-4.16-images/1846645209954258944
=> CNF-14990: Fix gimme golang install for go > 1.20

openshift-ci/Dockerfile.tools
- By using .x previously, it would cause the $PATH to not be set correctly and thus the go binaries were not being found
- A more permanent fix it being worked (CNF-14990) but this will fix 4.16 for now
=> infra: Fix gimme version (again...)

ztp/kube-compare-reference/unordered_list.tmpl
The unordered list handler needs to preserve all values from the expected list when comparing. This fix orders the "expected" keys to match any entries in the list being tested and then appends any remaining expected entries to the end.
=> OCPBUGS-43574: ztp: Fix kube compare unordered list

ztp/kube-compare-reference/Makefile, ztp/kube-compare-reference/README.md, ztp/kube-compare-reference/compare.sh
- **ztp: reference: enforce source-cr and reference alignment in CI**
- **ztp: Introduce 'make sync' to synchronize reference -> source-crs**
=> CNF-14823: Enforce reference and source-crs synchronization via CI

ztp/source-crs/validatorCRs/informDuValidatorMaster.yaml, ztp/source-crs/validatorCRs/informDuValidatorWorker.yaml
informDuValidatorMaster.yaml and informDuValidatorWorker.yaml were created for use in AGM PGs only, so the wave numbers added in the crs are unccessary and useless. For auto-created CGU that pick up the policy, the wave number should be added directly in the PG , as shown in the example (https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-validator-ranGen.yaml#L40).
With the O-Cloud manager orchestrating the lifecycle of cluster provisioning, CGU is not part of the process for cluster configuration.  Enforce policies are generated directly for configurations, along with an inform validator policy to validate completion. The ztp-deploy-wave number in the validator source crs causes the validator policy …
=> CNF-15050: ztp: Remove ztp-deploy-wave number from validator source crs for ACM PGs

ztp/tools/pgt2acmpg/.gitignore, ztp/tools/pgt2acmpg/scripts/build-acmpg-plugin.sh
- Specifically check for and use the exact policy-generator-plugin version used by ACM
- When used in older branches the ACM_BRANCH value can be updated to match the appropriate ACM version in use in that release
- Fixed tmp dir not getting cleaned up due to incorrect working directory when rm was called
- Add .gitignore entry for built kustomize files
=> ztp: CNF-14991: Fix instability in policy-generator-plugin usage

ztp/kube-compare-reference/Makefile
=> CNF-14178: ztp: reference: Use binary realease of helm-convert instead of go install [release-4.16]

ztp/kube-compare-reference/Makefile
=> CNF-15048: ztp: reference: Use binary release of helm-convert instead of go install [release-4.17]

go.mod, ztp/resource-generator/Containerfile
- Should match the golang and ocp versions used in current release
=> ztp: CNF-14990: Fix golang ocp builder image in resource generator

ztp/kube-compare-reference/Makefile
=> CNF-15059: ztp: reference: Use binary realease of helm-convert instead of go install [master]

ztp/gitops-subscriptions/argocd/README.md, ztp/gitops-subscriptions/argocd/deployment/allow-acm-managedcluster-control.json, ztp/gitops-subscriptions/argocd/deployment/clusters-app.yaml, ztp/gitops-subscriptions/argocd/example/siteconfig/KlusterletAddonConfigOverride.yaml, ztp/siteconfig-generator/siteConfig/clusterCRsV1.go, ztp/siteconfig-generator/siteConfig/clusterCRsV2.go, ztp/siteconfig-generator/siteConfig/siteConfig.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go, ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingArgocdAnnotation.yaml, ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingMetadata.yaml, ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingMetadataAnnotations.yaml, ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-NotTemplated.yaml, ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride.yaml, ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml, ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigV2TestOutput.yaml
Manual cherry pick of https://github.com/openshift-kni/cnf-features-deploy/pull/2005 
/cc @sabbir-47
=> [release-4.15] ztp: remove unsupported KlusterletAddonConfig clusterLabels and update managecluster CR to include cloud and vendor label

cnf-tests/testsuites/pkg/machineconfigpool/machineconfigpool.go
In the context of the test case
```
[It] [sriov] NUMA node alignment Utilize all available VFs then create a pod with guaranteed CPU and excludeTopology set to True
```
a flake might happen when restoring the original MCP takes more than 10 minutes. This behavior can be spotted by looking the sample failure [1]:
```
Enter [DeferCleanup (All) [sriov] NUMA node alignment @ 11/16/24 10:25:34.562
I1116 10:25:34.715725   35799 machineconfigpool.go:311] Moved back node role from [test-sriov-numa] to [worker-cnf] on cnfdu1
I1116 10:25:40.875535   35799 machineconfigpool.go:143] MCP worker-cnf is updating
I1116 10:25:40.928764   35799 machineconfigpool.go:28] Waiting for MCP master: Updating == False
I1116 10:25:40.972478   35799 machineconfigpool.go:36] Condition met for MCP master: Updating == …
```
=> cnf-tests: increase `WaitForAllMCPStable` timeout

cnf-tests/Dockerfile, cnf-tests/Dockerfile.openshift
Container image size of `quay.io/openshift-kni/cnf-tests:4.18` is 1.85GB:
```
$  docker images quay.io/openshift-kni/cnf-tests:4.18
REPOSITORY                        TAG       IMAGE ID       CREATED        SIZE
quay.io/openshift-kni/cnf-tests   4.18      a58152e3611a   22 hours ago   1.85GB
```
This cause test flakiness, as pulling the image might exceed timeouts. [1]
Most of the problem is in the dnf cache:
```
$ docker run quay.io/openshift-kni/cnf-tests:4.18 du -sh /var/cache/dnf
1.2G    /var/cache/dnf
```
Add `yum clean all` command after installing dependencies in the final image
With these changes, the image size is reduced to `665MB`:
```
$ docker images local-cnf-tests
REPOSITORY        TAG       IMAGE ID       CREATED          SIZE
local-cnf-tests   latest    681d224cbd65   44 …
```
=> cnf-tests: Reduce size of cnf-tests image

ztp/kube-compare-reference/metadata.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml, ztp/source-crs/PtpConfigBoundary.yaml, ztp/source-crs/PtpConfigBoundaryForEvent.yaml, ztp/source-crs/PtpConfigDualCardGmWpc.yaml, ztp/source-crs/PtpConfigGmWpc.yaml
This allows us to ignore customer-specified interfaces names in our PTP
configation testblobs, leading to better cluster-compare results.
=> CNF-15605: ztp: reference: Use capturegroupInlineDiff for PTPConfig [4.17]

ztp/kube-compare-reference/metadata.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml, ztp/source-crs/PtpConfigBoundary.yaml, ztp/source-crs/PtpConfigBoundaryForEvent.yaml, ztp/source-crs/PtpConfigDualCardGmWpc.yaml, ztp/source-crs/PtpConfigGmWpc.yaml
This allows us to ignore customer-specified interfaces names in our PTP
configation testblobs, leading to better cluster-compare results.
=> CNF-15792: ztp: reference: Use capturegroupInlineDiff for PTPConfig [4.14]

ztp/kube-compare-reference/metadata.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml, ztp/source-crs/PtpConfigBoundary.yaml, ztp/source-crs/PtpConfigBoundaryForEvent.yaml, ztp/source-crs/PtpConfigDualCardGmWpc.yaml, ztp/source-crs/PtpConfigGmWpc.yaml
This allows us to ignore customer-specified interfaces names in our PTP
configation testblobs, leading to better cluster-compare results.
=> CNF-15791: ztp: reference: Use capturegroupInlineDiff for PTPConfig [4.15]

cnf-tests/testsuites/e2esuite/security/tuning.go
To prevent errors and align how output is compared in other tests, check if the substring is contained instead of checking equality.
=> cnf-tests: Use ContainSubstring in sysctl tuning cni test

ztp/siteconfig-generator/siteConfig/clusterCRsV1.go, ztp/siteconfig-generator/siteConfig/clusterCRsV2.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badName.yaml, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badNamespace.yaml, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride.yaml, ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml, ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutputWithZap.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigV2TestOutput.yaml
OCPBUGS-42945, during node or cluster cleanup the BMH must complete deletion before the InfraEnv, NMStateConfig or Namespace are removed. This means the BMH must be in a higher wave (later for creation, earlier for deletion) than those other CRs.
The requirement comes from the cleanup phase of assisted installer/baremetal operator. If the BMH automatedCleanupMode is not disabled the node is rebooted into a new ISO image which cleans the disk. The creation of this ISO requires the Namespace to be not in the deleted state so that a new PreProvisioningImage CR can be created. The ISO creation also requires that the correct NMStateConfig CR be present (it is included in the ISO). The booting of the ISO requires the InfraEnv CR to be present.
=> OCPBUGS-42945: Ensure BMH deletion before InfrEnv and NS

cnf-tests/Dockerfile, cnf-tests/Dockerfile.openshift, cnf-tests/mirror/images.json, cnf-tests/pod-utils/hugepages-allocator/main.go, cnf-tests/testsuites/pkg/images/images.go, cnf-tests/testsuites/pkg/pods/pods.go
* move all builder to rhel9
* move cnf-tests image to rhel9
* replace `libhugetlbfs` ,which is not present in rhel9, with a local tool for allocating hugepages (more details in the commits)
=> CNF-15235: cnf-tests: move to rhel 9

Makefile
Main sriov-network-operator branch has moved from `master` to `main`.
Update the `SRIOV_NETWORK_OPERATOR_TARGET_COMMIT` variable accordingly to fix errors like [1]:
```
+ cd ../sriov-network-operator/
+ git fetch --all
+ git checkout origin/master
error: pathspec 'origin/master' did not match any file(s) known to git
make: *** [Makefile:140: init-git-submodules] Error 1
```
[1] https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift-kni_cnf-features-deploy/2148/pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests/1877360047533592576
cc @SchSeba @sshnaidm
=> infra: sriov git submodule should point to `main`

ztp/siteconfig-generator/siteConfig/clusterCRsV1.go, ztp/siteconfig-generator/siteConfig/clusterCRsV2.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badName.yaml, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badNamespace.yaml, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride.yaml, ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml, ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigV2TestOutput.yaml
This is a manual cherry-pick of #2136 
OCPBUGS-42945, during node or cluster cleanup the BMH must complete deletion before the InfraEnv, NMStateConfig or Namespace are removed. This means the BMH must be in a higher wave (later for creation, earlier for deletion) than those other CRs.
The requirement comes from the cleanup phase of assisted installer/baremetal operator. If the BMH automatedCleanupMode is not disabled the node is rebooted into a new ISO image which cleans the disk. The creation of this ISO requires the Namespace to be not in the deleted state so that a new PreProvisioningImage CR can be created. The ISO creation also requires that the correct NMStateConfig CR be present (it is included in the ISO). The booting of the ISO requires the InfraEnv CR to be present.
=> [release-4.15] OCPBUGS-47798: Ensure BMH deletion before InfrEnv and NS

hack/verify-commits.sh
- **infra: fixes branch to build the list of commits...**
- **infra: applies verification only to presubmits jobs, if a Prow run**
=> commit verify 4.14

hack/verify-commits.sh
- **infra: fixes branch to build the list of commits...**
- **infra: applies verification only to presubmits jobs, if a Prow run**
=> commit verify 4.15

ztp/siteconfig-generator/siteConfig/clusterCRs.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badName.yaml, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badNamespace.yaml, ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride.yaml, ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml, ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml, ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml, ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
Merged from pull request #2146
OCPBUGS-42945, during node or cluster cleanup the BMH must complete deletion before the InfraEnv, NMStateConfig or Namespace are removed. This means the BMH must be in a higher wave (later for creation, earlier for deletion) than those other CRs.
The requirement comes from the cleanup phase of assisted installer/baremetal operator. If the BMH automatedCleanupMode is not disabled the node is rebooted into a new ISO image which cleans the disk. The creation of this ISO requires the Namespace to be not in the deleted state so that a new PreProvisioningImage CR can be created. The ISO creation also requires that the correct NMStateConfig CR be present (it is included in the ISO). The booting of the ISO requires the InfraEnv CR to be present.
=> [release-4.14] OCPBUGS-48339: Ensure BMH deletion before InfrEnv and NS

ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go, ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
This PR is a fix for the ZTP siteconfig-generator and sitegen kustomize plugin panic if an empty file exists in the extra-manifest directory.
=> OCPBUGS-42068: ztp: emptyfile in siteconfig and sitegen kustomize plugin backport 

ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml, ztp/source-crs/PtpConfigDualCardGmWpc.yaml, ztp/source-crs/PtpConfigGmWpc.yaml
=> OCPBUGS-48803: [4.19] ztp: remove phc2sys -w option

ztp/kube-compare-reference/default_value.yaml, ztp/kube-compare-reference/metadata.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHA.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHAForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigMaster.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlave.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveForEvent.yaml
Part 2: Include the phc2sys '-n' option for domainNumber, as well as all
configs missed in the 1st commit.
=> OCPBUGS-47784: ztp: reference: Enable user customization of PTP priority1, priority2, and domainNumber fields

cnf-tests/testsuites/e2esuite/knmstate/knmstate_sriov.go, cnf-tests/testsuites/pkg/namespaces/namespaces.go, cnf-tests/testsuites/pkg/utils/consts.go, cnf-tests/testsuites/validationsuite/cluster/validation.go, feature-configs/ci/knmstate/operator_subscription.yaml, hack/setup-build-index-image.sh
Index image `quay.io/openshift-release-dev/ocp-release-nightly` contains
operator's nightly builds on Brew, which is not usually available on
Prow jobs.
These changes modify the `ci-index` CatalogSource, adding the knmstate operator
bundle, where the operator's image and operand image come from
promoted images in `registry.ci.openshift.org`.
depends on:
- https://github.com/openshift/release/pull/60779
- https://github.com/openshift-kni/cnf-features-deploy/pull/2165
=> infra: Build images for `knmstate`

ztp/kube-compare-reference/default_value.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHA.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHAForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigMaster.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlave.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveForEvent.yaml, ztp/source-crs/PtpConfigBoundaryForEvent.yaml, ztp/source-crs/PtpConfigDualCardGmWpc.yaml, ztp/source-crs/PtpConfigForHAForEvent.yaml, ztp/source-crs/PtpConfigGmWpc.yaml, ztp/source-crs/PtpConfigMasterForEvent.yaml, ztp/source-crs/PtpConfigSlaveForEvent.yaml
This change allows ptpClockThreshold to be set in all PtpConfig
scenarios, and also provides default values for the *ForEvent examples in
source-crs.
=> OCPBUGS-49786: ztp: Set up ptpClockThreshold in source-crs and reference templates

ztp/kube-compare-reference/default_value.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml, ztp/source-crs/PtpConfigDualCardGmWpc.yaml, ztp/source-crs/PtpConfigGmWpc.yaml
=> OCPBUGS-49785: ztp: Default WPC-GM MaxInSpecOffset to 1500 and allow user configuration of all settings values

ztp/kube-compare-reference/default_value.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigMaster.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlave.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveForEvent.yaml
For now we are supporting the G.8275.1 PTP profile for telco. The
priority1 field must be set to 128 for this profile and should not be
user-customizeable.
=> OCPBUGS-47784: ztp: Enforce PTP priority1 field must be 128 for telco ABMCA

ztp/kube-compare-reference/default_value.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigMaster.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlave.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveForEvent.yaml
For now we are supporting the G.8275.1 PTP profile for telco. The
priority1 field must be set to 128 for this profile and should not be
user-customizeable.
=> OCPBUGS-49793: ztp: Enforce PTP priority1 field must be 128 for telco ABMCA

cnf-tests/testsuites/pkg/utils/reporter.go, hack/run-functests.sh
Multus pod logs contains log entries from CNI instances, which  might be critical when debugging test failures.
Dump multus logs either on the SR-IOV conformance test suite and the integration test suite.
=> cnf-tests: Dump `openshift-multus` namespace on failure

ztp/kube-compare-reference/default_value.yaml, ztp/kube-compare-reference/metadata.yaml, ztp/kube-compare-reference/must_match_one_of.tmpl, ztp/kube-compare-reference/optional/local-storage-operator/StorageClass.yaml
=> OCPBUGS-48184: ztp: reference: Allow topolvm.io or kubernetes.io/no-provisioner for StorageClass provisioner

.githooks/commit-msg, .githooks/skipped-files.sh
These PRs are authored by a konflux application automatically, not by an upstream developer and we don't have control over the specific commit messages.
=> infra: skip Tekton checks (.tekton dir)

Makefile, hack/verify-images-updated.sh
This script ensures that developers update image references when creating a new branch.
How it works:
* A developer creates a new branch (e.g., release-4.19) and pushes it **without** verifying all image references are updated (using 4.19 images).
* He then submits a PR to the release repo to add a new CI configuration for the branch.
* If an outdated image references are detected (e.g 4.18), the script will fail the lane until they are updated and merged.
Note: I have prepared a POC to simulate this working in #2212.
This is the [failure results](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift-kni_cnf-features-deploy/2212/pull-ci-openshift-kni-cnf-features-deploy-release-4.18-ci/1886798140703510528)
depends on: …
=> Add script to check outdated image references

ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml, ztp/source-crs/PtpConfigDualCardGmWpc.yaml, ztp/source-crs/PtpConfigGmWpc.yaml
=> OCPBUGS-49371: [4.18] ztp: remove phc2sys -w option

ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml, ztp/source-crs/PtpConfigDualCardGmWpc.yaml, ztp/source-crs/PtpConfigGmWpc.yaml
=> OCPBUGS-49372: [4.17] ztp: remove phc2sys -w option

.tekton/ztp-site-generate-4-19-pull-request.yaml, .tekton/ztp-site-generate-4-19-push.yaml, ztp/resource-generator/.konflux/README.md, ztp/resource-generator/.konflux/rpms.in.yaml, ztp/resource-generator/.konflux/rpms.lock.yaml, ztp/resource-generator/.konflux/ubi.repo
We are enabling rpm pre-fetch based on `rpms.lock.yaml` for hermetic builds.
`rpms.lock.yaml `has been generated from the input provided by rpms.in.yaml:
- 'packages': rpms we depend on
- 'repofiles': currently, ubi8 is the runtime base image for ztp
using `rpm-lockfile-prototype` as a generator:
https://github.com/konflux-ci/rpm-lockfile-prototype?tab=readme-ov-file#installation
No additional subscription-manager/activation-key  config has been carried out,as the rpms we currently depend on don't require a Red Hat subscription.
Note: do not update these configuration files manually. The process about how to generate hermetic builds + rpms has been described as part of the konflux doc:
https://konflux.pages.redhat.com/docs/users/how-tos/configuring/activation-keys-subscription.html#_config …
=> ztp: make ztp a hermetic build

ztp/kube-compare-reference/default_value.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHAForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigMaster.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlave.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveForEvent.yaml, ztp/source-crs/PtpConfigBoundaryForEvent.yaml, ztp/source-crs/PtpConfigDualCardGmWpc.yaml, ztp/source-crs/PtpConfigForHAForEvent.yaml, ztp/source-crs/PtpConfigGmWpc.yaml, ztp/source-crs/PtpConfigMasterForEvent.yaml, ztp/source-crs/PtpConfigSlaveForEvent.yaml
This change allows ptpClockThreshold to be set in all PtpConfig
scenarios, and also provides default values for the *ForEvent examples
in source-crs.
=> OCPBUGS-52492: ztp: Set up ptpClockThreshold in source-crs and reference templates

cnf-tests/Dockerfile.openshift, cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go, cnf-tests/testsuites/e2esuite/security/tuning.go, cnf-tests/testsuites/pkg/machineconfigpool/machineconfigpool.go, cnf-tests/testsuites/pkg/nodes/nodes.go, cnf-tests/testsuites/pkg/utils/consts.go
Backport of:
- https://github.com/openshift-kni/cnf-features-deploy/pull/2110
- https://github.com/openshift-kni/cnf-features-deploy/pull/2120
- https://github.com/openshift-kni/cnf-features-deploy/pull/1967
=> [release-4.16] CNF-15765: CI fixes

ztp/kube-compare-reference/default_value.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigThreeCardGmWpc.yaml
Until we fix OCPBUGS-53199, there's really no good way to mix different
match classes, since matches with an exact api/kind/namespace/name will
always trump api/kind/namespace/* even if the latter is a closer match.
This change works around that behavior but forces the PtpConfig to be
named "grandmaster".  We can either relax the reference all at once
(allowing all PtpConfig to be named anything), or wait until the bug is
fixed and released to just relax some of the PtpConfigs.
=> ztp: Adjust 3-card PTP T-GM reference to not rely on fallback behavior

ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/README.md, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-example-multinode-reboot.yaml, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-example-sno-reboot.yaml, ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/kustomization.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/example-multinode-reboot.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-reboot.yaml, ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml, ztp/kube-compare-reference/compare_ignore, ztp/source-crs/RebootMachineConfig.yaml, ztp/source-crs/validatorCRs/rebootMachineConfigPoolValidator.yaml
Add reboot source CRs:
- dummy MachineConfig that triggers a reboot on nodes of a
MachineConifgPool
- MachineConfigPool validator that checks all nodes are updated
Add reboot PolicyGenerator examples
Add reboot PGT examples
Example:
```
$ ./policy-generator ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-example-multinode-reboot.yaml
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
annotations:
policy.open-cluster-management.io/categories: CM Configuration Management
policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
policy.open-cluster-management.io/description: ""
policy.open-cluster-management.io/standards: NIST SP 800-53
ran.openshift.io/soak-seconds: "120"
name: example-reboot
namespace: default
spec:
disabled: false …
```
=> ztp: CNF-15573: Add reboot manifests

cnf-tests/testsuites/e2esuite/multinetworkpolicy/multinetworkpolicy_sriov.go
Run `networks.CleanSriov(sriovclient)` before invoking `DiscoverSriov(...)`, as the latter needs a stable cluster to work.
See failure at:
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.18-e2e-telco5g-cnftests/1887924564965462016
```
Enter [BeforeEach] [multinetworkpolicy] MultiNetworkPolicy SR-IOV integration - /tmp/cnf-X9i6O/cnf-features-deploy/cnf-tests/testsuites/e2esuite/multinetworkpolicy/multinetworkpolicy_sriov.go:67 @ 02/07/25 21:10:45.332
< Exit [BeforeEach] [multinetworkpolicy] MultiNetworkPolicy SR-IOV integration - /tmp/cnf-X9i6O/cnf-features-deploy/cnf-tests/testsuites/e2esuite/multinetworkpolicy/multinetworkpolicy_sriov.go:67 @ 02/07/25 21:10:45.447 (115ms)
> Enter [BeforeEach] [multinetworkpolicy] …
```
=> cnf-tests: MultiNetworkPolicy `DiscoverSriov(...)` fix

ztp/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml, ztp/kube-compare-reference/unordered_list.tmpl, ztp/source-crs/PerformanceProfile.yaml
The vfio_pci kernel arguments are in support of the FEC accelerator. Allow these to be optional if not needed.
CNF-15761
=> ztp: Allow vfio kernel args to be optional

Makefile, cnf-tests/README.md
Job `periodic-ci-openshift-release-master-nightly-4.19-e2e-telco5g-cnftests` is failing [1] with the error:
```
+ cd ../cluster-node-tuning-operator/
+ git fetch --all
+ git checkout origin/master
error: pathspec 'origin/master' did not match any file(s) known to git
make: *** [Makefile:143: init-git-submodules] Error 1
```
Update the default reference for cluster-node-tuning submodule from `master` to `main`.
[1] https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.19-e2e-telco5g-cnftests/1902421134243008512
cc @shajmakh , @Tal-or
=> infra: update `cluster-node-tuning` ref to `main`

README.md
We've recently faced issues due to misaligned cnf-tests container images. Since it's easy to forget updating the image version across the repo, these changes to the branching guide are necessary to cover (hopefully) all required updates when creating a new release branch. The intention is for anyone creating the release-x.y branch to follow this, minimizing the chances of misalignments. Additionally, we implemented automation in the CI that will trigger a failure if these instructions are not followed: #2199.
=> Elaborated instructions for branching

ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml, ztp/source-crs/PtpConfigDualCardGmWpc.yaml, ztp/source-crs/PtpConfigGmWpc.yaml
=> OCPBUGS-49374: [4.15] ztp: remove phc2sys -w option

ztp/tools/pgt2acmpg/scripts/build-acmpg-plugin.sh
ztp-ci fails because the branch of ACM PG that is getting cloned is using golang-1.23.
This will lock the version to the lastest ACM PG that uses golang-1.22.
=> [release-4.18] ztp: Lock ACM PG version

ztp/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml, ztp/source-crs/PerformanceProfile-SetSelector.yaml, ztp/source-crs/PerformanceProfile.yaml
Add example hardwareTuning section to PerformanceProfile CR to show how isolated and reserved CPU frequencies can be configured.
=> CNF-13139: ztp: Add hardwareTuning to PerformanceProfile

ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml, ztp/source-crs/PtpConfigDualCardGmWpc.yaml, ztp/source-crs/PtpConfigGmWpc.yaml
=> OCPBUGS-44603: [4.14] ztp: remove phc2sys -w option

cnf-tests/pod-utils/cyclictest-runner/main.go, cnf-tests/pod-utils/hugepages-allocator/main.go, cnf-tests/pod-utils/hwlatdetect-runner/main.go, cnf-tests/pod-utils/oslat-runner/main.go
[syscall](https://pkg.go.dev/syscall) has been previously marked as deprecated as of Go 1.11 (since un-deprecated) and new functionality has been moved/added into [golang.org/x/sys](https://pkg.go.dev/golang.org/x/sys).
This PR replaces the calls to `syscall` with corresponding calls to `sys/unix`.
=> cnf-tests: syscall deprecated; use sys/unix pkg

cnf-tests/testsuites/e2esuite/multinetworkpolicy/reachmatcher.go, cnf-tests/testsuites/e2esuite/sctp/sctp.go, cnf-tests/testsuites/pkg/pods/pods.go
https://pkg.go.dev/k8s.io/utils/pointer has been deprecated in favor of `k8s.io/utils/ptr`.
=> cnf-tests: pointer deprecation: use 'ptr' instead

ztp/kube-compare-reference/default_value.yaml, ztp/kube-compare-reference/optional/ptp-config/PtpOperatorConfigForEvent.yaml, ztp/source-crs/PtpOperatorConfigForEvent.yaml
=> OCPBUGS-54517: ztp: reference: Ensure PtpOperatorConfig apiVersion is a string, and transportHost is optional

.tekton/cnf-tests-4-19-push.yaml
Use the latest tag to tag last produced image.
=> cnf-tests: tekton: tag konflux images as latest

openshift-ci/Dockerfile.tools
We want to support cnf-tests in aarch64 additionally to x86-x64, so far fedora specific x86-x64 was used. Use the multi arch tag to support building ARM images by openshift ci.
Quay image: https://quay.io/repository/fedora/fedora/manifest/sha256:811ab78abccb4376f4eb7d1c387165f5968a6cee0ed897800377fb79d210cf3c
The error we want to resolve:
```
Pulling image quay.io/fedora/fedora:41-x86_64 ...
Trying to pull quay.io/fedora/fedora:41-x86_64...
Getting image source signatures
Copying blob sha256:c47e6f71e1014f78efe620b6e419165ad1840d39e9bb6e69a2db43b0a5da4dd4
Copying config sha256:730f437472509e0d141824ba88a31f9d845a503a2d486f0a3e725c65a5993a7a
Writing manifest to image destination
WARNING: image platform (linux/amd64) does not match the expected
platform (linux/arm64)
```
=> infra: use multi-arch fedora

cnf-tests/.konflux/Dockerfile
Adapt to the rules of the official conforma:
* replace untrusted image with production image using the lastest
closest available build.
=> cnf-tests:k5x: adapt official conforma

.tekton/ztp-site-generate-4-19-push.yaml
Minor bug fix in ztp-site-generate 'push' tekton file
PR removes some missed references to 'workspace' in the push job, which is breaking 'Trusted Artifacts' pipeline on pr merge
=> fix ztp-site-generate push tekton file

ztp/policygenerator/policyGen/policyBuilder.go, ztp/policygenerator/policyGen/policyBuilder_test.go, ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericSecret.yaml, ztp/policygenerator/utils/utils.go
The purpose of this contribution is to implement the support of patching the stringData field in Secret source files via the PGT. 
It can be beneficial in the cases when the value of a secret is used to deliver a configuration file to the target application, and some parameters in the file should be collected from other secrets with the "fromSecret" template function.
Example:
The Secret definition in the policy should look like:
```yaml
kind: Secret
apiVersion: v1
metadata:
name: name
namespace: namespace
stringData:
mySecretFile.yaml: |
username: {{hub fromSecret "ns" "secretname" "username" | base64dec hub}}
password: {{hub fromSecret "ns" "secretname" "password" | base64dec hub}}
host: https://github.com
port: 3445
```
=> ztp: Support the patching of stringData in Secret source files

ztp/tools/pgt2acmpg/scripts/build-acmpg-plugin.sh
This PR locks the acmpg version being used in release 4.16 branch
Copy of this PR for release-4.17 #2354
=> ztp: lock acmpg version for release-4.16

ztp/.konflux/OWNERS
cc : @rauhersu @fontivan 
Adds k5x owners file in ztp/.konflux
=> tekton: add owners file in ztp konflux

.tekton/cnf-tests-4-20-pull-request.yaml, .tekton/cnf-tests-4-20-push.yaml
Define when to run the pipelines on the branch. We want to run them only if related tekton files changed or any change in `cnf-tests` directory.
=> cnf-tests: tekton: update on-cel-expression

.gitmodules
This PR locks release branch in gitmodules for release-4.19
=> infra: lock gitmodule branches

cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go, cnf-tests/testsuites/pkg/pods/pods.go
Test case
```
[sriov] NUMA node alignment [BeforeAll] Validate the creation of a pod with excludeTopology set to False and an SRIOV interface in a different NUMA node than the pod
```
flakes with the following error:
```
Can't find a suitable node for testing: node [cnfdu3] has no NUMA0 devices, node [cnfdu4] has no NUMA0 devices,
```
Dump NUMA nodes for each network device when failing.
Use Gomega instead of `ginkgo.Fail` to trigger a k8sreporter archive.
[Sample failure](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.18-e2e-telco5g-cnftests/1857483975761596416)
=> cnf-tests: Add debug information for flake tests

.tekton/OWNERS, .tekton/ztp-site-generate-4-16-pull-request.yaml, .tekton/ztp-site-generate-4-16-push.yaml, OWNERS_ALIASES, ztp/resource-generator/.konflux/OWNERS, ztp/resource-generator/.konflux/README.md, ztp/resource-generator/.konflux/redhat.repo, ztp/resource-generator/.konflux/rpms.in.yaml, ztp/resource-generator/.konflux/rpms.lock.yaml, ztp/resource-generator/Containerfile
This PR backports all konflux changes related to ztp-site-generate to release-4.16
- Add tekton pipeline files and konflux RPM lockfile
- Add owners for tekton files
=> ztp: backport ztp konflux to release-4.16

.tekton/OWNERS, .tekton/ztp-site-generate-4-17-pull-request.yaml, .tekton/ztp-site-generate-4-17-push.yaml, OWNERS_ALIASES, ztp/resource-generator/.konflux/OWNERS, ztp/resource-generator/.konflux/README.md, ztp/resource-generator/.konflux/redhat.repo, ztp/resource-generator/.konflux/rpms.in.yaml, ztp/resource-generator/.konflux/rpms.lock.yaml, ztp/resource-generator/Containerfile
This PR backports all konflux changes related to ztp-site-generate to release-4.17
- Add tekton pipeline files and konflux RPM lockfile
- Add owners for tekton files
=> ztp: backport ztp konflux to release-4.17

.tekton/OWNERS, .tekton/ztp-site-generate-4-12-pull-request.yaml, .tekton/ztp-site-generate-4-12-push.yaml, OWNERS_ALIASES, ztp/resource-generator/.konflux/OWNERS, ztp/resource-generator/.konflux/README.md, ztp/resource-generator/.konflux/redhat.repo, ztp/resource-generator/.konflux/rpms.in.yaml, ztp/resource-generator/.konflux/rpms.lock.yaml, ztp/resource-generator/Containerfile
This PR backports all konflux changes related to ztp-site-generate to release-4.14
- Add tekton pipeline files and konflux RPM lockfile
- Add owners for tekton files
=> ztp: backport ztp konflux to release-4.12

.gitmodules, go.mod, ztp/resource-generator/Containerfile
This PR:
- Upversions go mod file to 1.23
- Upversion container builder image to 1.23
- Adds a comment # in .gitmodules to fix Renovate parsing
=> Upversion golang to 1.23 in release-4.19

ztp/kube-compare-reference/metadata.yaml, ztp/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml, ztp/kube-compare-reference/required/node-tuning-operator/TunedPerformancePatch.yaml, ztp/kube-compare-reference/unordered_list.tmpl
- **ztp: RAN reference: Cleanup PerformanceProfile template**
- **ztp: RAN reference: Allow setting cpufreq governor when perPodPowermanagement is set**
- **ztp: RAN reference: Optionally allow max_perf_pct sysfs in Tuned**
=> OCPBUGS-55771: ran powersave reference 4.18

.tekton/cnf-tests-4-14-pull-request.yaml, .tekton/cnf-tests-4-14-push.yaml, cnf-tests/.konflux/Dockerfile, cnf-tests/.konflux/OWNERS, cnf-tests/.konflux/README.md, cnf-tests/.konflux/rpms.in.yaml, cnf-tests/.konflux/rpms.lock.yaml
* Add tekton files to configure pipeline jobs
* Add konflux dedicated Dockerfile and RPM lockfile
* Add owners for tekton files
* update cnf-tests/.konflux/README.md to specify the different flow for lockfile generation when using rhel8-based image.
=> cnf-tests: konflux 4.14 onboarding

.tekton/cnf-tests-4-15-pull-request.yaml, .tekton/cnf-tests-4-15-push.yaml, cnf-tests/.konflux/Dockerfile, cnf-tests/.konflux/OWNERS, cnf-tests/.konflux/README.md, cnf-tests/.konflux/rpms.in.yaml, cnf-tests/.konflux/rpms.lock.yaml
* Add tekton files to configure pipeline jobs
* Add konflux dedicated Dockerfile and RPM lockfile
* Add owners for tekton files
* update cnf-tests/.konflux/README.md to specify the different flow for lockfile generation when using rhel8-based image.
=> cnf-tests: konflux 4.15 onboarding

.tekton/cnf-tests-4-20-push.yaml
Fix misplaced ADDITIONAL_TAGS, should be under the `apply-tags` task.
=> cnf-tests: tekton: misplaced additional_tags

cnf-tests/.konflux/Dockerfile, cnf-tests/.konflux/rpms.in.yaml, cnf-tests/.konflux/rpms.lock.yaml
The health index for rhel9 images that are not based on the latest rhel9 minor versions are very low (D). Compared with the old method that used to build the container images there was an automatic mechanism enabling it to dynamically bump the base images such that the base will always be the most recent. It was noticed that using the old method, the builds used 9.6 and are A-scored. This commit bumps the ubi to 9.6 Considering there is no risk in that because cnf-tests is shipping tests only.
=> cnf-tests: k5x: bump rhel 9.4 -> 9.6

cnf-tests/.konflux/rpms.in.yaml, cnf-tests/.konflux/rpms.lock.yaml
Pam rpm is now avialable on top of 9.6 so consume it as well as updating the rest of the RPMs to the latests to consume latest security fixes and upgrade CHI to A.
(cherry picked from commit 61fb195f68dd03eb32a4d1709a4fb558859fedde)
=> [release-4.19] cnf-tests: k5x: update to latest RPMs (namely pam)

cnf-tests/.konflux/Dockerfile
Not specifying the suite path lead to block running the tests. The env var was missed during teh migration to konflux. re-add it to fix the problem.
The variable is used in: `cnf-tests/entrypoint/test-run.sh`
=> [release-4.14] cnf-tests: k5x: add missing SUITE_PATH

cnf-tests/.konflux/Dockerfile
Not specifying the suite path lead to block running the tests. The env var was missed during teh migration to konflux. re-add it to fix the problem.
The variable is used in: `cnf-tests/entrypoint/test-run.sh`
=> [release-4.12] cnf-tests: k5x: add missing SUITE_PATH

cnf-tests/testsuites/pkg/numa/numa.go, cnf-tests/testsuites/pkg/pods/pods.go
Starting from
- https://github.com/openshift-kni/cnf-features-deploy/pull/2109
stderr is not returned by the function `ExecCommandInContainer`. This PR means to restore that behavior.
=> cnf-tests: `ExecCommandInContainer` return combined output

ztp/kube-compare-reference/metadata.yaml, ztp/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml, ztp/kube-compare-reference/required/node-tuning-operator/TunedPerformancePatch.yaml, ztp/kube-compare-reference/unordered_list.tmpl
- **ztp: RAN reference: Cleanup PerformanceProfile template**
- **ztp: RAN reference: Allow setting cpufreq governor when perPodPowermanagement is set**
- **ztp: RAN reference: Optionally allow max_perf_pct sysfs in Tuned**
=> OCPBUGS-57792: ran powersave 4.15

.tekton/cnf-tests-4-18-pull-request.yaml, .tekton/cnf-tests-4-18-push.yaml
=> [release-4.18] AA: cnf-tests: tekton: use PR number as quay builds tag

.tekton/cnf-tests-4-12-pull-request.yaml, .tekton/cnf-tests-4-12-push.yaml
=> [release-4.12] AA: cnf-tests: tekton: use PR number as quay builds tag

.tekton/cnf-tests-4-14-pull-request.yaml, .tekton/cnf-tests-4-14-push.yaml
=> [release-4.14] AA: cnf-tests: tekton: use PR number as quay builds tag

.tekton/cnf-tests-4-19-pull-request.yaml, .tekton/cnf-tests-4-19-push.yaml
=> [release-4.19] AA: cnf-tests: tekton: use PR number as quay builds tag

.tekton/cnf-tests-4-19-push.yaml
replace `"` with `'` to ensure the specified files updates trigger the on-push pipeline.
=> cnf-tests: tekton: fix on-cel-expression `"` -> `'`

.tekton/cnf-tests-4-12-push.yaml
It was not visible to detect that the `pull_request_number` variable is not available on on-push pipeline. revert the change partially done previously.
=> cnf-tests: replace unfound variable `pull_request_number`[revert]

.tekton/cnf-tests-4-20-pull-request.yaml
=> AA: cnf-tests: tekton: use PR number as quay builds tag

.tekton/cnf-tests-4-16-pull-request.yaml, .tekton/cnf-tests-4-16-push.yaml, .tekton/ztp-site-generate-4-16-pull-request.yaml, .tekton/ztp-site-generate-4-16-push.yaml
This PR address a build issue that creeped in from a konflux reference update [PR](https://github.com/openshift-kni/cnf-features-deploy/pull/2719) that was merged without performing migration tasks
=> tekton: migrate source-build-oci-ta task with required params

.tekton/cnf-tests-4-15-pull-request.yaml, .tekton/cnf-tests-4-15-push.yaml, .tekton/ztp-site-generate-4-15-pull-request.yaml, .tekton/ztp-site-generate-4-15-push.yaml
The tasks digests were updated to the new release but the migration updates were missing. Add missing params needed by this update as per https://github.com/konflux-ci/build-definitions/blob/main/task/source-build-oci-ta/0.3/MIGRATION.md
=> tekton: migrate source-build-oci-ta with required params for v0.3

.tekton/cnf-tests-4-17-pull-request.yaml, .tekton/cnf-tests-4-17-push.yaml, .tekton/ztp-site-generate-4-17-pull-request.yaml, .tekton/ztp-site-generate-4-17-push.yaml
This PR address a build issue that creeped in from a konflux reference update that was merged without performing migration tasks
=> [release-4.17] tekton: build-source-image tekton task migration

ztp/kube-compare-reference/Makefile
This PR update helm binary version to 3.18.4 for fixing [CVE-2025-53547](https://github.com/advisories/GHSA-557j-xg8c-q2mm)
=> ztp: OCPBUGS-59095: update helm to 3.18.4 [release-4.16]

ztp/kube-compare-reference/Makefile
This PR update helm binary version to 3.18.4 for fixing CVE-2025-53547
=> ztp: OCPBUGS-59088: helm update to 3.18.4 [release-4.15]

ztp/kube-compare-reference/Makefile
This PR update helm binary version to 3.18.4 for fixing CVE-2025-53547
=> ztp: OCPBUGS-59094: update helm to 3.18.4 [release-4.14]

hack/setup-build-index-image.sh
openshift-marketplace requires specific selectors for pods to query DNS and go to internet.
CNF-19268
=> tools: Fix namespace for pod to build index image

cnf-tests/.konflux/lock-runtime/rpms.lock.yaml, cnf-tests/Makefile
- A missing backslash was causing parameters to not be passed correctly to the task
- The container image should be passed without stripping the digest
- After fixing the issues, re-run the task to ensure everything is good
=> Fix rpm lockfile task & Re-run lockfile task

Makefile, cnf-tests/Makefile, ztp/resource-generator/Makefile
- Revert bad commit that broke the functest ci
- Add a new target that just syncs the telco5g-konflux submodule and use that for the konflux targets
=> infra: Fix git submodule syncing

.tekton/cnf-tests-4-20-pull-request.yaml, .tekton/cnf-tests-4-20-push.yaml, .tekton/ztp-site-generate-4-20-pull-request.yaml, .tekton/ztp-site-generate-4-20-push.yaml
- Sorting them will make it easier to keep the paths sane going forward
- Since the library scripts are used by the tekton builds, changes there should trigger the builds
AI-attribution: AIA,Entirely human-created,v1.0
For more information on AI attribution statements, see: https://aiattribution.github.io/
=> Sort on-cel-expression file paths && add telco5g-konflux to it

ztp/kube-compare-reference/compare_ignore, ztp/kube-compare-reference/metadata.yaml, ztp/kube-compare-reference/required/machine-config/cgroup-check.yaml, ztp/kube-compare-reference/required/machine-config/container-runtime.yaml
All workloads should be moving to cgroup v2. Add a required check for cgroup. If users remain on cgroup v1 the check serves as a reminder that workloads must be moved to v2.
Manual backport of https://github.com/openshift-kni/telco-reference/pull/269
=> ztp: Add cgroup and runtime checks
