- feature-configs/base/ptp/01_namespace.yaml
- feature-configs/base/ptp/02_operator_group.yaml
- feature-configs/base/ptp/03_subscription.yaml
- feature-configs/base/ptp/kustomization.yaml
- feature-configs/demo/ptp/kustomization.yaml
- feature-configs/demo/ptp/subscription.yaml
This PR add the ptp feature using kustomize.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openshift-kni/cnf-features-deploy/6)
> Create ptp deployment manifests

- feature-configs/base/ptp/04-ptpconfig.yaml
- feature-configs/base/ptp/kustomization.yaml
- feature-configs/demo/ptp/kustomization.yaml
- feature-configs/demo/ptp/ptpconfig-grandmaster.yaml
- feature-configs/demo/ptp/ptpconfig-slave.yaml
> Add a demo for ptp grandmaster and slave

- go.mod
- go.sum
This is needed for builds to pass.
> update pinned repo

- feature-configs/base/sriov/01-sriov-namespace.yaml
- feature-configs/base/sriov/02-sriov-operatorgroup.yaml
- feature-configs/base/sriov/03-sriov-subscription.yaml
- feature-configs/base/sriov/04-sriov-networknodepolicy.yaml
- feature-configs/base/sriov/05-sriov-network.yaml
- feature-configs/base/sriov/kustomization.yaml
- feature-configs/demo/sriov/kustomization.yaml
- feature-configs/demo/sriov/sriov-networknodepolicy.yaml
- feature-configs/demo/sriov/sriov-subscription.yaml
This PR add the sriov operator deployment for the base.
For the demo I also create the test namespace and the policy.
> Add sriov feature deployment

- OWNERS_ALIASES
To add @mmirecki as a reviewer
> Add Marcin Mirecki as a reviewer

- hack/feature-deploy.sh
Running tests against a failed deployment will fail anyway.
> Fail if the deployment did not finish successfully.

- functests/sctp/sctp.go
https://github.com/openshift-kni/cnf-features-deploy/pull/14 got removed in applying new tests
> Check for lenght of nodes and gracefully fail instead of throwing panics

- feature-configs/demo/sctp/sctp_module_mc_patch.yaml
As it must stick to the new MCP
> Fix the sctp machine config role in demo layer

- openshift-ci/Dockerfile.tools
This needs to be in place before https://github.com/openshift-kni/cnf-features-deploy/pull/26
> Install skopeo as it's needed to harvest origin test binary

- README.md
As we changed the way we deploy / test, I am updating the readme to reflect that.
> Update README to the latest changes.

- hack/feature-wait.sh
such as those on baremetal hosts
Signed-off-by: Yuval Kashtan <yuval@redhat.com>
> change wait timeout to accomomdate long boot times

- README.md
As per @nikita133 suggestions  in https://github.com/openshift-kni/cnf-features-deploy/pull/37
> Makes variables section smaller as suggested

- hack/setup-test-cluster.sh
This PR adds a label of grandmaster on the first master and all the other nodes (master/workers) are labeled as slaves
> Add ptp labels on the nodes

- feature-configs/base/performance/operator_catalogsource.yaml
- feature-configs/demo/performance/kustomization.yaml
- feature-configs/demo/performance/operator_catalogsource.patch.yaml
- feature-configs/e2e-gcp/performance/kustomization.yaml
- feature-configs/e2e-gcp/performance/operator_catalogsource.patch.yaml
Use correct operator image in base config
> Use correct operator image in base config

- functests/sctp/sctp.go
Adding a new test checking if the pod 2 pod connectivity works in the default namespace.
> Add a new test for inter pod connectivity on the default namespace.

- README.md
Solves https://github.com/openshift-kni/cnf-features-deploy/issues/75
> Fix testing section stating that we need FEATURES 

- feature-configs/base/performance/performance_profile.yaml
- feature-configs/e2e-gcp/performance/performance_profile.patch.yaml
> Provide NUMA node for hugepages allocation

- openshift-ci/Dockerfile.tools
> Remove the creation of ~/bin and .bashrc as pods run /bin/sh

- openshift-ci/Dockerfile.tools
> Explicitly set HOME env variable

- openshift-ci/Dockerfile.tools
This is a temporary change to help debugging the CI issue
> Rollback ci workaround to make it possible to debug the issue

- tools/s2i-dpdk/Dockerfile
- tools/s2i-dpdk/README.md
- tools/s2i-dpdk/base-image/build-config.yaml
- tools/s2i-dpdk/s2i/bin/assemble
- tools/s2i-dpdk/s2i/bin/run
- tools/s2i-dpdk/s2i/bin/save-artifacts
- tools/s2i-dpdk/s2i/bin/usage
- tools/s2i-dpdk/test/run
- tools/s2i-dpdk/test/test-app/build.sh
- tools/s2i-dpdk/test/test-app/run.sh
- tools/s2i-dpdk/test/test-app/test-template.sh
This PR move ths s2i-dpdk from https://github.com/SchSeba/s2i-dpdk-centos7 to this repo.
> Move the s2i-dpdk build code to this repo

- hack/setup-test-cluster.sh
Minor fix to properly output the number of nodes labeled as worker-cnf
> Proper number of nodes message

- feature-configs/base/performance/performance_profile.yaml
- feature-configs/e2e-gcp/performance/performance_profile.patch.yaml
Updates our base performance profile to reflect the api changes in this pr, https://github.com/openshift-kni/performance-addon-operators/pull/73
> Update performance profile to reflect api changes

- feature-configs/e2e-gcp/performance/performance_profile.patch.yaml
CPU management test was updated, so we need to return balanceIsolated to default value
>  Adjust performance profile: set balanceIsolated by default

- OWNERS_ALIASES
> Add slintes to approvers

- feature-configs/base/performance/performance_profile.yaml
we need 3 isolated cpus for test workload to run
Signed-off-by: Yuval Kashtan <yuval@redhat.com>
> Fix base performance profile cpu isolation

- feature-configs/e2e-gcp/performance/performance_profile.patch.yaml
Reason: https://bugzilla.redhat.com/show_bug.cgi?id=1811630
> Temporarily disable RT kernel

- hack/feature-deploy.sh
Only print output of oc apply on last iteration. This is an example with 2 iterations only:
```
$ make feature-deploy
FEATURES_ENVIRONMENT=e2e-gcp FEATURES="sctp performance" hack/feature-deploy.sh
[INFO] Deploying feature 'sctp' for environment 'e2e-gcp'
[INFO] Deploying feature 'performance' for environment 'e2e-gcp'
[WARN] Deployment of feature 'performance' failed.
[WARN] At least one deployment failed, retrying in 10 sec, 1 retries left
[INFO] Deploying feature 'sctp' for environment 'e2e-gcp'
machineconfig.machineconfiguration.openshift.io/load-sctp-module unchanged
[INFO] Deploying feature 'performance' for environment 'e2e-gcp'
namespace/openshift-performance-addon unchanged
operatorgroup.operators.coreos.com/openshift-performance-addon-operatorgroup unchanged …
```
> Be less verbose while waiting for all deployments to be successful

- tools/s2i-dpdk/test/test-app/build.sh
- tools/s2i-dpdk/test/test-app/test-pmd/Makefile
- tools/s2i-dpdk/test/test-app/test-pmd/bpf_cmd.c
- tools/s2i-dpdk/test/test-app/test-pmd/bpf_cmd.h
- tools/s2i-dpdk/test/test-app/test-pmd/cmdline.c
- tools/s2i-dpdk/test/test-app/test-pmd/cmdline_flow.c
- tools/s2i-dpdk/test/test-app/test-pmd/cmdline_mtr.c
- tools/s2i-dpdk/test/test-app/test-pmd/cmdline_mtr.h
- tools/s2i-dpdk/test/test-app/test-pmd/cmdline_tm.c
- tools/s2i-dpdk/test/test-app/test-pmd/cmdline_tm.h
- tools/s2i-dpdk/test/test-app/test-pmd/config.c
- tools/s2i-dpdk/test/test-app/test-pmd/csumonly.c
- tools/s2i-dpdk/test/test-app/test-pmd/flowgen.c
- tools/s2i-dpdk/test/test-app/test-pmd/icmpecho.c
- tools/s2i-dpdk/test/test-app/test-pmd/ieee1588fwd.c
- tools/s2i-dpdk/test/test-app/test-pmd/iofwd.c
- tools/s2i-dpdk/test/test-app/test-pmd/macfwd.c
- tools/s2i-dpdk/test/test-app/test-pmd/macswap.c
- tools/s2i-dpdk/test/test-app/test-pmd/meson.build
- tools/s2i-dpdk/test/test-app/test-pmd/noisy_vnf.c
- tools/s2i-dpdk/test/test-app/test-pmd/parameters.c
- tools/s2i-dpdk/test/test-app/test-pmd/rxonly.c
- tools/s2i-dpdk/test/test-app/test-pmd/softnicfwd.c
- tools/s2i-dpdk/test/test-app/test-pmd/testpmd.c
- tools/s2i-dpdk/test/test-app/test-pmd/testpmd.h
- tools/s2i-dpdk/test/test-app/test-pmd/txonly.c
- tools/s2i-dpdk/test/test-app/test-pmd/util.c
- tools/s2i-dpdk/test/test-app/test-template.sh
This commit updates the dpdk s2i building process.
Now we are also building the testpmd application and not using the one that is shipped by the dkdk package.
> Update dpdk s2i build

- functests/dpdk/dpdk.go
> Add Numa aliment test for DPDK workload

- hack/setup-test-cluster.sh
by adding --overwrite to labels
Signed-off-by: Yuval Kashtan <yuvalkashtan@gmail.com>
> add support for setup-test-cluster rerun

- OWNERS_ALIASES
Signed-off-by: Yuval Kashtan <yuvalkashtan@gmail.com>
> Add Yuval Kashtan as a reviewer

- functests/dpdk/dpdk.go
- functests/utils/pods/pods.go
This commit checks the number of hugepages that can be allocated inside a pod.
> Hugepages allocation tests

- feature-configs/base/sctp/is_ready.sh
See https://github.com/kubernetes/kubernetes/commit/f4940cf55fd7c2787b370464d491a764c4febd78#diff-56412633454231b0d61039e010a64c2c
/assign @fedepaol
> oc wait --for condition is case sensitive now

- Makefile
- cnf-tests/testimages/images.json
- feature-configs/demo/dpdk/build-config.yaml
- feature-configs/demo/dpdk/deployment-config.yaml
- feature-configs/demo/dpdk/dpdk-network.yaml
- feature-configs/demo/dpdk/is_ready.sh
- feature-configs/demo/dpdk/scc.yaml
- functests/dpdk/dpdk.go
- functests/test_suite_test.go
- functests/utils/client/clients.go
- functests/utils/images/images.go
- functests/utils/pods/pods.go
- go.mod
- tools/s2i-dpdk/Dockerfile
- tools/s2i-dpdk/README.md
- tools/s2i-dpdk/base-image/build-config.yaml
This PR allow to run the DPDK functional tests independent of the configuration.
> Run DPDK functional tests

- tools/s2i-dpdk/Dockerfile
> Fix the dpdk image

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/functests/0_config/config.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/topology_manager.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/nodes/nodes.go
- vendor/modules.txt
This includes not hanging in the conifguration suite if the profile is already created.
> Upgrade to the latest performance operator tests.

- configsuite/test_suite_test.go
- functests/test_suite_test.go
- functests/utils/reporter.go
- go.sum
- validationsuite/test_suite_test.go
This includes catching test + operators pods, and adding their relevant crds to the list to be dumped.
> Collect pod logs for all the operators involved and for all test namespaces.

- hack/run-functests.sh
By setting CNF_TESTS_IMAGE, make functests will execute them in the dockerized form.
> Provide support for running the dockerized version of the tests.

- cnf-tests/README.md
Fixes https://github.com/openshift-kni/cnf-features-deploy/issues/177
> Fix the link to quay as without the protocol it's interpreted as local url.

- feature-configs/demo/ptp/kustomization.yaml
- feature-configs/demo/sctp/kustomization.yaml
- feature-configs/demo/sriov/kustomization.yaml
- feature-configs/demo/sriov/sriov-networknodepolicy.yaml
- feature-configs/demo/sriov/sriov-subscription.yaml
This commit fix the demo kustomize layer moving the base to be deploy
> Fix demo kustomize layer

- cnf-tests/Dockerfile
- cnf-tests/Dockerfile.openshift
The ping package is needed for the sriov tests
> Add ping package to the cnf-test image

- functests/dpdk/dpdk.go
- functests/utils/pods/pods.go
- tools/s2i-dpdk/Dockerfile
This commit run the deployment base pod with the already exist testpmd inside the dpdk package.
> Update the dpdk test to run without testpmd build

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/hugepages.go
- vendor/modules.txt
> Vendor the latest version of the performance tests with longer (and stabler) timeouts

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/hugepages.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/consts.go
- vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
- vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/profile/profile.go
- vendor/github.com/openshift/ptp-operator/test/ptp/ptp.go
- vendor/github.com/openshift/ptp-operator/test/utils/consts.go
- vendor/modules.txt
> Pin the latest version of the operator, pin to particular versions of sriov and ptp tests

- feature-configs/demo/dpdk/dpdk-network.yaml
- feature-configs/deploy/dpdk/kustomization.yaml
- feature-configs/deploy/dpdk/namespace.yaml
> Create the dpdk namespace in the deploy overlay

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
- vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
- vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/vfs_assignement.go
- vendor/github.com/openshift/sriov-network-operator/test/util/cluster/cluster.go
- vendor/modules.txt
Performance: handle change of format in kubelet config.
Sriov: make the tests compatible with 4.5 & 4.4.
> Vendor new versoin of performance / sriov tests.

- functests/ptp/prometheus.go
- functests/ptp/ptp.go
> Fix ptp and move the prometheus test

- feature-configs/integration-base/sctp/is_ready.sh
- hack/build-test-bin.sh
- hack/common.sh
- hack/feature-deploy.sh
- hack/feature-wait.sh
- hack/lint.sh
- hack/run-functests.sh
- hack/setup-test-cluster.sh
there is no longer 'base' directory
> fix feature-wait.sh to use is_ready from deploy

- functests/ptp/ptp.go
> Disable ptp test as measuring the latency with master + slave on nodes is not meaningful.

- go.mod
- go.sum
- vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
- vendor/github.com/openshift/sriov-network-operator/test/util/cluster/cluster.go
- vendor/modules.txt
Checks for the daemon to be running before asking for logs, comments the unhealthy tests.
> [release-4.5] Vendor latest sriov operator.

- cnf-tests/README.md
Add info about refactoring the perf profile so the test execution is quicker.
> CNF Tests: Extend the readme with running on 4.4 info plus using same perf profile for performance and dpdk

- feature-configs/deploy/dpdk/build-config.yaml
- functests/dpdk/dpdk.go
- tools/s2i-dpdk/Dockerfile
- tools/s2i-dpdk/test/test-app/build.sh
- tools/s2i-dpdk/test/test-app/test-pmd/cmdline.c
- tools/s2i-dpdk/test/test-app/test-pmd/cmdline_flow.c
- tools/s2i-dpdk/test/test-app/test-pmd/cmdline_mtr.c
- tools/s2i-dpdk/test/test-app/test-pmd/cmdline_tm.c
- tools/s2i-dpdk/test/test-app/test-pmd/config.c
- tools/s2i-dpdk/test/test-app/test-pmd/csumonly.c
- tools/s2i-dpdk/test/test-app/test-pmd/flowgen.c
- tools/s2i-dpdk/test/test-app/test-pmd/icmpecho.c
- tools/s2i-dpdk/test/test-app/test-pmd/ieee1588fwd.c
- tools/s2i-dpdk/test/test-app/test-pmd/macfwd.c
- tools/s2i-dpdk/test/test-app/test-pmd/macswap.c
- tools/s2i-dpdk/test/test-app/test-pmd/macswap.h
- tools/s2i-dpdk/test/test-app/test-pmd/macswap_common.h
- tools/s2i-dpdk/test/test-app/test-pmd/macswap_neon.h
- tools/s2i-dpdk/test/test-app/test-pmd/macswap_sse.h
- tools/s2i-dpdk/test/test-app/test-pmd/parameters.c
- tools/s2i-dpdk/test/test-app/test-pmd/softnicfwd.c
- tools/s2i-dpdk/test/test-app/test-pmd/testpmd.c
- tools/s2i-dpdk/test/test-app/test-pmd/testpmd.h
- tools/s2i-dpdk/test/test-app/test-pmd/txonly.c
- tools/s2i-dpdk/test/test-app/test-pmd/util.c
- tools/s2i-dpdk/test/test-app/test-template.sh
This commit fix an issue with the test pmd.
Error building the dpdk test application
```
STEP 1: FROM quay.io/openshift-kni/dpdk:4.5
STEP 2: LABEL "io.openshift.build.image"="quay.io/openshift-kni/dpdk:4.5"       "io.openshift.build.commit.author"="OpenShift Merge Robot <openshift-merge-robot@users.noreply.github.com>"       "io.openshift.build.commit.date"="Wed Jun 3 14:04:08 2020 +0200"       "io.openshift.build.commit.id"="315c7f6b6fc0a8db87d624878dcbd3bb00cccd3a"       "io.openshift.build.commit.ref"="master"       "io.openshift.build.commit.message"="Merge pull request #231 from yuvalk/run_tests_from_image"       "io.openshift.build.source-location"="https://github.com/openshift-kni/cnf-features-deploy.git"       "io.openshift.build.source-context-dir"="tools/s2i-dpdk/test/test-app" …
```
> Update test-pmd application

- functests/ptp/ptp.go
- functests/sctp/sctp.go
- functests/test_suite_test.go
- functests/utils/clean/sriov_clean.go
This includes:
- sriov networks / policies
- ptp labels / configurations
- sctp / sriov namespaces
> Delete any remaining dangling resorces.

- cnf-tests/README.md
> Doc fixes: change the name of the image from the local one, add a troubleshooting section, reword the mirroring section.

- configsuite/test_suite_test.go
> Fix the config suite reporter

- functests/dpdk/dpdk.go
- functests/utils/nodes/nodes.go
By setting the NODES_SELECTOR variable, we limit the cluster nodes that are impacted by the test.
This includes sriov configurations, choosing the nodes to run the pods on.
If not set, the tests continue to behave as before.
> Dpdk tests: impact only nodes selected by the optional node selector.

- feature-configs/deploy/dpdk/build-config.yaml
> [release-4.5] DPDK build use branch 4.5 branch

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/consts.go
- vendor/modules.txt
This includes fixing test 28026
> [release 4.5] Vendor the latest perf operator 4.5 tests.

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
- vendor/github.com/openshift-kni/performance-addon-operators/pkg/apis/performance/v1alpha1/performanceprofile_types.go
- vendor/modules.txt
> Update PAO dependencies

- feature-configs/typical-baremetal/dpdk/kustomization.yaml
- feature-configs/typical-baremetal/performance/kustomization.yaml
- feature-configs/typical-baremetal/performance/performance_profile.patch.yaml
- feature-configs/typical-baremetal/ptp/kustomization.yaml
- feature-configs/typical-baremetal/sctp/kustomization.yaml
- feature-configs/typical-baremetal/sriov/kustomization.yaml
Signed-off-by: Sabina Aledort <saledort@redhat.com>
> Add typical baremetal config

- OWNERS_ALIASES
Currently we have only one approver (me), so we reduce the lottery factor.
Signed-off-by: Federico Paolinelli <fpaoline@redhat.com>
> Add more approvers.

- go.mod
- go.sum
- vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
- vendor/modules.txt
> vendor latest sriov-network-operator release 4.6

- go.mod
- go.sum
- vendor/github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1/sriovnetworknodepolicy_types.go
- vendor/github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1/sriovnetworknodestate_types.go
- vendor/github.com/openshift/sriov-network-operator/test/util/cluster/cluster.go
- vendor/modules.txt
> [Release 4.5] Bump Sriov version

- functests/dpdk/dpdk.go
This commit fix the CPU set test.
The CPU list can contain multiple lists
example output:
```
NUMA node0 CPU(s):   0-19,40-59
NUMA node1 CPU(s):   20-39,60-79
```
> Fix the CPU set test

- functests/dpdk/dpdk.go
This PR change to dpdk test to create a policy when the test are not in discovery mode to find and use the default router and use that interface.
I make this change because on the default network there is always
traffic for the testpmd application to process, this makes the test stable.
> Use default network for dpdk test

- OWNERS_ALIASES
> [release 4.5] Update owner base on master

- go.mod
- go.sum
- vendor/github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1/helper.go
- vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
- vendor/github.com/openshift/sriov-network-operator/test/util/cluster/cluster.go
- vendor/modules.txt
base on this PR: https://github.com/openshift/sriov-network-operator/pull/325
> Bug 1870669: Bump latest sriov 4.6 tests

- functests/dpdk/dpdk.go
This commit fix the huge-pages test using the cpuset
function created in https://github.com/openshift-kni/cnf-features-deploy/pull/291
> Fix the cpuset for huge-pages test

- go.mod
- go.sum
- vendor/github.com/openshift/ptp-operator/test/ptp/ptp.go
- vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
- vendor/github.com/openshift/sriov-network-operator/test/util/cluster/cluster.go
- vendor/modules.txt
> Bump network feature tests

- functests/dpdk/dpdk.go
There are some nodes where bridge link do not return anything.
We use ip link then, cross-checking the uplink to be a sriov device.
> Change the way we look for the uplink when using ovs.

- go.mod
- go.sum
- vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
- vendor/github.com/openshift/sriov-network-operator/test/util/network/network.go
More waiting, choosing the default nic for macvlan
> Update the sriov operator tests

- go.mod
- go.sum
- vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
- vendor/modules.txt
Includes another fix for pf down test, for those nodes where
bridge link do not return anything.
> Vendor latest sriov operator.

- go.mod
- go.sum
- vendor/github.com/openshift/ptp-operator/test/ptp/ptp.go
- vendor/github.com/openshift/ptp-operator/test/utils/clean/clean.go
- vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
- vendor/modules.txt
Include discovery of ptp enabled interfaces before running the tests.
> New ptp / sriov tests vendor

- functests/dpdk/dpdk.go
- functests/utils/discovery/discovery.go
- Work also in case the resource name was dpdknic.
- Update the resource counter
- Consider only resources valid for dpdk (rdma, netdevice for mlnx, vfio-pci for intel)
- Take all the policies regardless of the selector type
> Fix dpdk test in discovery mode.

- go.mod
- go.sum
- vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
- vendor/modules.txt
Fixes crash in discovery mode because of bad placed skip.
> Update sriov test.

- go.mod
- go.sum
- vendor/github.com/openshift/ptp-operator/test/ptp/ptp.go
- vendor/modules.txt
Skips all the tests in discovery mode if configuration is not found.
> New ptp tests version.

- go.mod
- go.sum
- vendor/github.com/openshift/ptp-operator/test/ptp/ptp.go
- vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
- vendor/modules.txt
SRIOV Flag tests: ensure that the test pod and the hostnetwork pod run on the same node
PTP: Skip priority profile test in discovery mode, don't use the hardcoded master profile name
> Consume the latest sriov / ptp tests.

- functests/dpdk/dpdk.go
this commit runs a second dpdk pod in txonly mode to send traffic on the same network as the server.
output:
```
---------------------- Forward statistics for port 0  ----------------------
RX-packets: 34753303       RX-dropped: 0             RX-total: 34753303
TX-packets: 34753303       TX-dropped: 0             TX-total: 34753303
----------------------------------------------------------------------------
+++++++++++++++ Accumulated forward statistics for all ports+++++++++++++++
RX-packets: 34753303       RX-dropped: 0             RX-total: 34753303
TX-packets: 34753303       TX-dropped: 0             TX-total: 34753303
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```
> Bug 1889631: Make dpdk test more robust

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/hugepages.go
- vendor/github.com/openshift/ptp-operator/test/ptp/ptp.go
- vendor/github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1/helper.go
- vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
- vendor/modules.txt
This aligns the bugfixes in the related test suites.
> Update sriov, ptp, performance dependencies.

- feature-configs/deploy/performance/operator_catalogsource.yaml
- feature-configs/deploy/performance/operator_operatorgroup.yaml
- feature-configs/deploy/performance/operator_subscription.yaml
> Use index image to deploy PAO

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/hugepages.go
- vendor/modules.txt
Includes fix for test: hugepages with NUMA node
> Bug 1890087: Update PAO tests dependencies.

- go.mod
- go.sum
- vendor/github.com/openshift/ptp-operator/test/ptp/ptp.go
- vendor/modules.txt
Includes the fix for bug 1889835.
> Bug 1889835: Update the ptp tests dependency.

- functests/dpdk/dpdk.go
In regular mode it's safe to assume there are no extra configurations in the cluster. Not having to backup and restore will make the test cycle faster, and will reduce the chance of not restoring the configuration because of errors in the middle.
> Bug 1895871: DPDK test: don't backup and create sriov configuration in regular mode.

- functests/utils/discovery/discovery.go
When the discovery of sriov on one nodes of the cluster fails, the discovery function fails even
when the discovery is performed successfully on at least one node.
This is a manual cherry-pick of https://github.com/openshift-kni/cnf-features-deploy/pull/363
> Fix dpdk discovery mode.

- go.mod
- go.sum
- vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
- vendor/modules.txt
Vendor latest sriov tests, which include the fix for Bug #1890089
> Bug 1890089: Update to latest sriov operator tests.

- hack/run-functests.sh
During call to `hack/run-functests.sh` check the `LATENCY_TEST_RUN`
environment variable and when it equals to true, run latency tests
together with other tests.
> Add an option to run latency test together with other tests

- feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml
this commit change the grandmaster profile to use the same profile
as the salve one
> use the same interface for both ptp profiles

- hack/feature-deploy.sh
Will download and use the latest
kustomize tool version  instead
of the one integrated in the OC_TOOL
As of v3.7.0 Kustomize supports a special type of kustomization that allows one to define reusable pieces of configuration logic that can be included from multiple overlays.
Components come in handy when dealing with applications that support multiple optional features and you wish to enable only a subset of them in different overlays, i.e., different features for different environments or audiences.
It is not clear when kustomize 3.x will be integrated into the kubectl, current supported version is 2.x
The integration is tracked here: https://github.com/kubernetes/kubectl/issues/818
> Use standalone kustomize tool

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
- vendor/modules.txt
> Update PAO dependency

- go.mod
- go.sum
- vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go
- vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/images/images.go
- vendor/github.com/openshift/ptp-operator/test/ptp/ptp.go
- vendor/modules.txt
> Bump SRIOV and PTP

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/functests/0_config/config.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/clean/clean.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/mcps/mcps.go
- vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/consts.go
- vendor/modules.txt
This brings in the fixes for performance tests against a single node openshift.
> CNFTests: Update the PAO tests dependencies.

- cnf-tests/docgen/cmd/fill.go
added to the fill subcommand check of removed tests that are still in the jsons 
https://github.com/openshift-kni/cnf-features-deploy/issues/374
> added test removed from test suite case

- functests/sctp/sctp.go
- functests/xt_u32/xt_u32.go
- validationsuite/cluster/validation.go
https://github.com/openshift-kni/cnf-features-deploy/issues/372
> Find SCTP MachineConfigPool also via MatchLabels

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
- vendor/modules.txt
> [release-4.6] Update PAO dependencies

- openshift-ci/Dockerfile.tools
> Use the fedora image from quay

- openshift-ci/Dockerfile.tools
> Install diffutils package under tools image

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
- vendor/modules.txt
> [release-4.7] Update PAO dependencies

- README.md
Minor fixes to clean up README.md file
> Minor fixes/typos in readme

- cnf-tests/testsuites/validationsuite/cluster/validation.go
The mechanisms for checking MC and MCP was duplicated for both the sctp
and xt_u32 tests, and will be reused for other MC-related deployments in
the future.  This abstraction makes it easier to manage and reuse these
checks.
> Refactor some common logic in the cluster validation suite

- feature-configs/cn-ran-overlays/ran-profile/cluster-config/kustomization.yaml
- feature-configs/deploy/n3000/kustomization.yaml
- feature-configs/deploy/n3000/namespace.yaml
- feature-configs/deploy/n3000/operatorgroup.yaml
- feature-configs/deploy/n3000/subscription.yaml
- feature-configs/deploy/sriov-fec/kustomization.yaml
- feature-configs/deploy/sriov-fec/namespace.yaml
- feature-configs/deploy/sriov-fec/operatorgroup.yaml
- feature-configs/deploy/sriov-fec/subscription.yaml
This commit add the two operators develop by intel.
I also add this to the DU profile
> Add the n3000 and sriov-fec operators develop by intel

- feature-configs/deploy/ptp/03_subscription.yaml
- feature-configs/deploy/sriov/03-sriov-subscription.yaml
> Bump operators to 4.7

- cnf-tests/TESTLIST.md
- cnf-tests/docgen/e2e.json
- cnf-tests/testsuites/e2esuite/ptp/ptp.go
Add test to verify that the uds can not be used by an unprivileged pod
> Add negative test for ptp uds

- OWNERS_ALIASES
cleaning up notification emails... :)
> Remove slintes from OWNERS

- feature-configs/demo/ovs_qos/egress_mc.yaml
- feature-configs/demo/ovs_qos/ingress_mc.yaml
Added ExecStop so if the mc is deleted the QoS policy resets
> Fix ovs_qos mc

- ztp/ztp-playbooks/install-ai-operator/roles/install-assisted-installer/tasks/main.yml
- ztp/ztp-playbooks/install-ai-operator/roles/install-assisted-installer/templates/ai_secrets.yaml.j2
Signed-off-by: Yolanda Robla <yroblamo@redhat.com>
> Add secrets for the AI operator

- cnf-tests/TESTLIST.md
- cnf-tests/docgen/e2e.json
- cnf-tests/testsuites/e2esuite/fec/fec.go
- cnf-tests/testsuites/e2esuite/test_suite_test.go
- cnf-tests/testsuites/pkg/clean/clean.go
- cnf-tests/testsuites/pkg/namespaces/namespaces.go
- cnf-tests/testsuites/pkg/utils/consts.go
- cnf-tests/testsuites/pkg/utils/reporter.go
- cnf-tests/testsuites/validationsuite/cluster/validation.go
- feature-configs/deploy/n3000/namespace.yaml
- feature-configs/deploy/n3000/operatorgroup.yaml
- feature-configs/deploy/n3000/subscription.yaml
- feature-configs/deploy/sriov-fec/namespace.yaml
- feature-configs/deploy/sriov-fec/operatorgroup.yaml
- feature-configs/deploy/sriov-fec/subscription.yaml
* Bump intel operator
* add a basic sriov-fec test to check we are able to configure the acc100 card and the resources are exposed in the cluster.
waiting for  https://github.com/openshift-kni/cnf-features-deploy/pull/444
> Support basic sriov-fec test

- cnf-tests/TESTLIST.md
- cnf-tests/docgen/validation.json
- cnf-tests/testsuites/validationsuite/cluster/validation.go
"sriov fec" test had in it`s name the same name of another operator "sriov", which leads to incorrec operation of FEATURES variable.
> Changed the name of "sriov fec" tests to  "fec"

- hack/run-origin-tests.sh
> Fix the cluster provider flag setup for origin-tests

- go.mod
- go.sum
- openshift-ci/Dockerfile.tools
- vendor/modules.txt
> Update go version to 1.16.3

- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/policyBuilder.go
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/utils/utils.go
- ztp/ztp-policy-generator/policyGenTemplates/policyGenTemplate.yaml
- ztp/ztp-policy-generator/ranPolicyGenTempExamples/group-du-ranGen.yaml
- ztp/ztp-policy-generator/sourcePolicies/MachineConfigPool.yaml
- ztp/ztp-policy-generator/sourcePolicies/SriovNetwork.yaml
- fix delete missing spec items
- allow delete undefine spec items if it is empty value
- add labels to the policy gen template
> Fix delete missing spec items and add labels

- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/policyBuilder.go
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/policyHelper.go
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/utils/utils.go
- ztp/ztp-policy-generator/ranPolicyGenTempExamples/common-ranGen.yaml
- ztp/ztp-policy-generator/sourcePolicies/ClusterLogSubscription.yaml
- ztp/ztp-policy-generator/sourcePolicies/ClusterLogSubscriptionNS.yaml
- ztp/ztp-policy-generator/sourcePolicies/ClusterLogSubscriptionOperGroup.yaml
> Allow multiple yamls structure in same file for generated policy

- ztp/source-policy-crs/SriovOperatorConfig.yaml
> Add disableDrain flag to SRIOV config

- ztp/source-policy-crs/SriovOperatorConfig.yaml
- ztp/ztp-policy-generator/ranPolicyGenTempExamples/group-du-sno-ranGen.yaml
Prefer the default of disableDrain to be false and overide in the SNO
policyGen template.
> Set DU profile default SRIOV disableDrain false

- feature-configs/deploy/dpdk/build-config.yaml
- tools/s2i-dpdk/Dockerfile
This commit will update the dpdk container use for s2i to dpdk version 20.11
> Update dpdk version to 20.11

- cnf-tests/testsuites/e2esuite/fec/fec.go
This commit allows to run fec tests on SNO (one node cluster)
> Allow to run fec tests on SNO

- hack/run-functests.sh
This commit will remove any MTU or ipv6 vs ipv4 connectivity issues, between the container networking and the host networking.
> Run cnf-test with host network

- ztp/ran-site-plan-crd/site-config-cr-ex.yaml
- ztp/ran-site-plan-crd/site-config-crd.yaml
> Add site config CRD

- hack/run-functests.sh
> Print more detailed test output to the console

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
- vendor/modules.txt
> [release-4.8] Update PAO dependencies

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/consts.go
- vendor/modules.txt
> [release-4.8] Update PAO dependency

- go.mod
- go.sum
- vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go
- vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/client/clients.go
- vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/cluster/cluster.go
- vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/pod/pod.go
- vendor/modules.txt
> Bump sriov and ptp operator using release 4.9 branch

- cnf-tests/README.md
I was going through all of the README anyway,
so I decided to correct any mistakes I saw.
> Fixing README typos

- ztp/source-policy-crs/PerformanceProfile.yaml
Improve latency/responsiveness with idle=poll on kernel command line
> Update PerformanceProfile kernel args

- ztp/source-cluster-crs/cluster-crs.yaml
Underlying implementation will updated and added back tracked under https://github.com/openshift-kni/cnf-features-deploy/issues/619
> ztp: removing userData temporarily to enable testing for ztp

- cnf-tests/testsuites/e2esuite/sctp/sctp_sriov.go
> cnf-tests: Fix the sriov sctp test when secure boot is enable

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/hugepages.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/nodes/nodes.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/pods/pods.go
- vendor/modules.txt
- re-enable initramfs tests
- fix the latency tests
- update code to use REST client to execute commands on top of pod
> vendor: update pao dependencies

- feature-configs/deploy/ptp/03_subscription.yaml
- feature-configs/deploy/sriov/03-sriov-subscription.yaml
features: bump operators to 4.8
signed-off-by: Nishant Parekh <nparekh@redhat.com>
> features: bump operators to 4.8

- ztp/ran-site-plan-crd/site-config-cr-ex.yaml
- ztp/ran-site-plan-crd/site-config-crd.yaml
- ztp/source-cluster-crs/extra-manifest/disk-encryption.yaml.tmpl
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/go.mod
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/go.sum
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfig.go
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfigBuilder.go
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfigBuilder_test.go
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/testdata/empty.yaml.tmpl
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/testdata/execution_failure.yaml.tmpl
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/testdata/good.yaml.tmpl
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/testdata/parse_failure.yaml.tmpl
- ztp/ztp-policy-generator/siteConfigExamples/site1-sno-du.yaml
- ztp: SiteConfig spec and example changes for Disk Encryption
- ztp: Generate optional disk encryption manifest
Before merge:
> NDBE and ZTP integration

- ztp/source-policy-crs/MachineConfigContainerMountNS.yaml
- ztp/source-policy-crs/MachineConfigSctp.yaml
- ztp/source-policy-crs/PaoSubscription.yaml
- ztp/source-policy-crs/PaoSubscriptionCatalogSource.yaml
- ztp/source-policy-crs/PaoSubscriptionNS.yaml
- ztp/source-policy-crs/PaoSubscriptionOperGroup.yaml
- ztp/source-policy-crs/PtpSubscription.yaml
- ztp/source-policy-crs/PtpSubscriptionNS.yaml
- ztp/source-policy-crs/PtpSubscriptionOperGroup.yaml
- ztp/source-policy-crs/SriovSubscription.yaml
- ztp/source-policy-crs/SriovSubscriptionNS.yaml
- ztp/source-policy-crs/SriovSubscriptionOperGroup.yaml
To remove external dependencies of the  ztp folder.
No other changes done
/assign @serngawy 
/cc @imiller0 @yrobla @nishant-parekh
> ztp: remove soft links to deployment

- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/UNITTESTS.md
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/go.mod
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGenerator.go
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGenerator_test.go
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestMachineConfigPool/sourcePolicies/TestMachineConfigPool.yaml
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestMachineConfigPool/templates/TestMachineConfigPool.yaml
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestNamespace/sourcePolicies/TestNamespace.yaml
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestNamespace/templates/TestNamespace.yaml
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestOperatorGroup/sourcePolicies/TestOperatorGroup.yaml
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestOperatorGroup/templates/TestOperatorGroup.yaml
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestPtpConfig/templates/TestPtpConfig.yaml
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestSriovNetwork/sourcePolicies/TestSriovNetwork.yaml
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestSriovNetwork/templates/TestSriovNetwork.yaml
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestSubscription/sourcePolicies/TestSubscription.yaml
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestSubscription/templates/TestSubscription.yaml
ztp: added new tests for policyGenerator
- Added new tests covering the policyBuilder logic
- Added tests for day0 and day2 artifacts for ZTP
- Coverage of over 85% on the policyBuilder logic
> ztp: added new tests for policyGenerator

- feature-configs/deploy/ptp/03_subscription.yaml
- feature-configs/deploy/sriov/03-sriov-subscription.yaml
This commit bump the ptp and sriov subscription to version 4.8
> [release-4.8] switch the ptp and sriov operators to 4.8

- ztp/gitops-subscriptions/README.md
- ztp/gitops-subscriptions/argocd/README.md
- ztp/resource-generator/README.md
Add README for resource-generator and minor corrections to other README
files.
> Add README for resource-generator

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/api/v2/performanceprofile_validation.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/netqueues.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
- vendor/modules.txt
-Add latency test cases
-Add RT kernel check before checking rcu existence
-Fix netqueues test
> vendor: Update vendor PAO dependencies

- cnf-tests/testsuites/pkg/images/images.go
> cnf-tests: bump images to 4.9

- ztp/ran-crd/site-config-crd.yaml
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/resources/cluster-crs.yaml
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfigBuilder.go
- ztp/ztp-policy-generator/testSiteConfig/site2-standard-du.yaml
> ztp: add standard cluster deployment

- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/policyBuilder.go
- ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGenerator.go
This change allows multi-entry yaml files to pass through when creating
unwrapped raw CRs.
> ztp: Fix raw CR generation for multi-entry sources

- ztp/resource-generator/src/common.sh
- ztp/resource-generator/src/get-pre-sync-rv.sh
- ztp/resource-generator/src/post-sync-entrypoint.sh
- ztp/resource-generator/src/pre-sync-entrypoint.sh
Add retry logic to cluster API authentication and fast-fail if
authentication fails after 25 retries.
> Bug 2004510: ztp: Add authentication retries to ztp container

- feature-configs/cn-ran-overlays/ran-profile-gcp/catalog-4.8.yaml
- feature-configs/cn-ran-overlays/ran-profile-gcp/catalog-override-4.8.yaml
- feature-configs/cn-ran-overlays/ran-profile-gcp/kustomization.yaml
> Ran profile CI lane fix attempt

- Makefile
> infra: revert the deployment folder back to deploy

- tools/oot-driver/charts/dpdk-kni-driver-0.0.1/templates/0000-buildconfig.yaml
> oot-driver: fix dpdk-kni driver build

- cnf-tests/GATEKEEPER.md
- cnf-tests/README.md
Depends on https://github.com/openshift-kni/cnf-features-deploy/pull/592/
> features: gatekeeper validation tests doc

- ztp/source-crs/DefaultCatsrc.yaml
Add default catalog source for
consolidating all the disconnected catalog sources
/cc @serngawy
> ztp: add default catsrc to source crs

- feature-configs/ci/ptp/kustomization.yaml
- feature-configs/cn-ran-overlays/ran-profile/cluster-config/kustomization.yaml
- hack/setup-build-index-image.sh
This PR contains two commits needed to make the CI green again.
1. add the ci subscription for ptp
2. remove sro from the list because of the OLM bug
https://bugzilla.redhat.com/show_bug.cgi?id=2016425
> Fix CI system

- cnf-tests/testsuites/pkg/namespaces/namespaces.go
- cnf-tests/testsuites/pkg/utils/reporter.go
Signed-off-by: Ori Braunshtein <obraunsh@redhat.com>
> cnf-tests: Add default namespace to reporter

- ztp/source-crs/ReduceMonitoringFootprint.yaml
Additional CPU reductions for 4.10
> ztp: CNF-3071 Reduce Prometheus retention period

- cnf-tests/mirror/images.json
> cnf-tests: [release-4.9] bump image mirror tags

- tools/oot-driver/charts/dpdk-kni-driver-0.0.1/Dockerfile-driver.SRO
- tools/oot-driver/charts/iavf-driver-0.0.1/Dockerfile-driver.SRO
- tools/oot-driver/charts/ice-driver-0.0.1/Dockerfile-driver.SRO
This PR is needed for https://github.com/openshift-kni/cnf-features-deploy/pull/645
> oot-driver: update Dockerfiles for oot-drivers

- ztp/policygenerator/policyGen/policyBuilder.go
- ztp/policygenerator/policyGen/policyBuilder_test.go
- ztp/policygenerator/testData/TestMachineConfigPool/templates/TestMachineConfigPool.yaml
- ztp/policygenerator/utils/utils.go
- ztp/ran-crd/policy-gen-template-crd.yaml
add ability to generate inform policies from PGT
add sourceFile level override for remediationAction
error on conflict between sourceFiles
add unit tests to cover all scenarios
jira: CNF-3462
> ztp: added logic to override remediationAction from PGT

- cnf-tests/testsuites/pkg/images/images.go
> cnf-tests: bump the images for cnf-test to 4.10

- ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
- ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
- ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
- ztp/ran-crd/site-config-cr-ex.yaml
- ztp/ran-crd/site-config-crd.yaml
- ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml
- ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site2-sno-du.yaml
- ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site2-standard-du.yaml
- ztp/siteconfig-generator/siteConfig/siteConfig.go
- ztp/siteconfig-generator/siteConfig/siteConfig_test.go
- ztp: Compute SiteConfig NumMasters and NumWorkers from node roles
- ztp: deprecate SiteConfig clusters.clusterType
> ztp: Cleanup multinode siteconfig schema

- ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
- ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
- ztp/siteconfig-generator/siteConfig/testdata/user-extra-manifest/.bad-non-yaml-file.yaml
> ztp: Ignore hidden files in extra-manifests directories

- OWNERS_ALIASES
> owners: Add Jim Ramsay (lack) to ZTP approvers list

- ztp/resource-generator/Containerfile
- ztp/resource-generator/Makefile
- ztp/resource-generator/README.md
> ztp: Fix resourece-generator Make and Readme

- ztp/policygenerator/policyGen/policyBuilderOverlay_test.go
> ztp: Minor cleanup of unit tests

- ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
> ztp: comment the getCluserCR unit test for not blocking other commits

- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
New source-crs `DisableSnoNetworkDiag` is now added to example group-du for ZTP
> ztp: BZ-2029181 Add reference of DisableSnoNetworkDiag.yaml to group-du-sno PolicyGenTemplate

- ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
- ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
> ztp: re-enable getClusterCR unitTest

- ztp/.gitignore
- ztp/gitops-subscriptions/argocd/README.md
- ztp/policygenerator-kustomize-plugin/README.md
- ztp/policygenerator/README.md
> ztp: Update Readme and examples

- ztp/gitops-subscriptions/argocd/Upgrade.md
> ztp: Add upgrade.md

- ztp/source-crs/ClusterVersion.yaml
ztp: Added ClusterVersion source CR and updated common PGT to include reference
> ztp: Add platform update source CR for upgrades operator interoperability 

- go.mod
- openshift-ci/Dockerfile.tools
> [Release 4.7] bump CI image version

- ztp/source-crs/validatorCRs/informDuValidator.yaml
Correct the names of MCs in validator source cr
> Bug 2034300: ztp: Fix the name issue in validator source cr

- hack/build-test-bin.sh
- hack/lint.sh
> [release 4.7] remove the mod from the go install commands

- cnf-tests/hack/build-test-bin.sh
- cnf-tests/hack/lint.sh
> [release 4.8] use go install for golint package like ginkgo

- OWNERS_ALIASES
Update OWNERS_ALIASES file to resemble team changes.
> Update OWNERS_ALIASES file.

- OWNERS_ALIASES
> owners: Update OWNERS_ALIASES file

- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
- ztp/source-crs/PtpOperatorConfig.yaml
> Bug 2040705: ztp: Only run PTP daemons on worker nodes for standard clusters

- ztp/siteconfig-generator/siteConfig/clusterCRs.go
- ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
- ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
> Bug 2039425:  disable klusterlet applactionManager

- ztp/source-crs/ClusterVersion.yaml
> Bug 2037939 ztp fix cluster version source-crs

- ztp/resource-generator/Containerfile
> Bug 2040467: fix build ztp-site-generator image

- ztp/gitops-subscriptions/argocd/README.md
- ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/example-multinode-site.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
- ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
- ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
- ztp/policygenerator/README.md
> ztp: Update ZTP gitops documentation to reflect the new TALO-based policy application

- feature-configs/ci/sro/nfd-subscription.yaml
- feature-configs/cn-ran-overlays/ran-profile-gcp/cluster-config/ci/sro/nfd-subscription.yaml
> features: Fix ran profile CI lane

- ztp/gitops-subscriptions/argocd/README.md
- ztp/gitops-subscriptions/argocd/Upgrade.md
> ztp: Expand content in upgrade guide.

- ztp/gitops-subscriptions/argocd/README.md
- ztp/gitops-subscriptions/argocd/deployment/openshift-gitops-operator.yaml
> Bug2046775: ztp add openshift gitops operator

- ztp/gitops-subscriptions/argocd/README.md
> ztp: Add another example error to the troubleshooting section

- cnf-tests/pod-utils/oslat-runner/main.go
- cnf-tests/pod-utils/pkg/node/node.go
> Bug 2051443: cnf-tests: filter main thread CPU siblings under the oslat test

- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/api/v2/performanceprofile_types.go
- vendor/modules.txt
bump PAO to 4.8-release 158bf9c5
Signed-off-by: Mario Fernandez <mariofer@redhat.com>
> [release-4.8]  Bump pao dependency 4.8 158bf9c5

- .githooks/components.sh
- README.md
- infra: Add docs git component for edits to the base-level README.md
- docs: Update README.md with a pointer to ZTP
- docs: Update README.md with some repository branching notes
> Top-level README.md updates

- ztp/resource-generator/Containerfile
> ztp: Update container builder to golang 1.17

- ztp/siteconfig-generator/siteConfig/clusterCRs.go
Added proxy settings for AgentClusterInstall.
Signed-off-by: Mario Vazquez <mavazque@redhat.com>
> Bug 2056968: ztp: Added proxy definition for AgentClusterInstall

- ztp/gitops-subscriptions/argocd/README.md
- ztp/gitops-subscriptions/argocd/deployment/argocd-openshift-gitops-patch.json
- ztp/resource-generator/Makefile
- ztp/resource-generator/README.md
> ztp: Update upstream container location to quay.io/openshift-kni/ztp-site-generator

- ztp/source-crs/ClusterVersionUpgradeGraph.yaml
ztp: add cluster version status to source-crs
> ztp: ClusterVersion changes for platform upgrade 

- ztp/policygenerator/policyGen/policyBuilder.go
- ztp/policygenerator/policyGen/policyBuilderOverlay_test.go
- ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericStatusCR.yaml
- ztp/policygenerator/utils/utils.go
- ztp/ran-crd/policy-gen-template-crd.yaml
> ztp: PGT supports status updates or overlays

- OWNERS_ALIASES
owners: add Angie to ZTP and RAN Approvers
> owners: add Angie to ZTP and RAN Approvers

- ztp/source-crs/ClusterVersion.yaml
ztp: sync clusterVersion changes from master
added status.history section to verify updates
> Bug 2038954: ztp: ClusterVersion changes for platform upgrade

- ztp/source-crs/StoragePVC.yaml
> Bug 2060554: ztp: fix PersistentVolumeClaim source cr

- ztp/gitops-subscriptions/argocd/Upgrade.md
> ztp: Update the ArgoCD upgrade procedure

- ztp/gitops-subscriptions/argocd/README.md
- ztp/policygenerator/README.md
- ztp/source-crs/README.md
> Bug 2034926: ztp: Readme updates for ztp-deploy-wave

- feature-configs/deploy/performance/operator_catalogsource.yaml
- feature-configs/deploy/performance/operator_subscription.yaml
- go.mod
- go.sum
- vendor/github.com/openshift-kni/performance-addon-operators/build/assets/assets.go
- vendor/github.com/openshift-kni/performance-addon-operators/build/assets/configs/99-low-latency-hooks.json
- vendor/github.com/openshift-kni/performance-addon-operators/build/assets/configs/99-netdev-rps.rules
- vendor/github.com/openshift-kni/performance-addon-operators/build/assets/configs/99-runtimes.conf
- vendor/github.com/openshift-kni/performance-addon-operators/build/assets/scripts/hugepages-allocation.sh
- vendor/github.com/openshift-kni/performance-addon-operators/build/assets/scripts/low-latency-hooks.sh
- vendor/github.com/openshift-kni/performance-addon-operators/build/assets/scripts/set-rps-mask.sh
- vendor/github.com/openshift-kni/performance-addon-operators/build/assets/tuned/openshift-node-performance
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/netqueues.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
- vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
- vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
- vendor/modules.txt
> vendor: bump PAO to master branch 20220309

- ztp/gitops-subscriptions/argocd/example/siteconfig/KlusterletAddonConfigOverride.yaml
- ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
- ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
- ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
> ztp: Make the KlusterletAddonConfigOverride purpose more clear in a comment

- ztp/resource-generator/Makefile
Signed-off-by: tliu2021 <tali@redhat.com>
> ztp: update container Makefile to support Mac

- ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
- ztp/source-crs/AcceleratorsOperatorStatus.yaml
- ztp/source-crs/AmqOperatorStatus.yaml
- ztp/source-crs/ClusterLogOperatorStatus.yaml
- ztp/source-crs/PaoOperatorStatus.yaml
- ztp/source-crs/PtpOperatorStatus.yaml
- ztp/source-crs/SriovOperatorStatus.yaml
- ztp/source-crs/StorageOperatorStatus.yaml
The new operator resource added is used for determining
the successful operator install/upgrade.
> Bug 2054407: ztp: add the Operator source CR for each subscription

- ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/example-multinode-site.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-validator-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-validator-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-validator-ranGen.yaml
> Bug 2072086 ztp: add v4.10 label for policies in v4.10 branch.

- ztp/resource-generator/Containerfile
This reverts commit fedc8e863e6e3d16dcb1dbefd61946cf2714493f.
> Revert "ztp: include non yaml files from sourceCRs in container"

- .gitignore
> ignore jetbrains and macos auto generated folders and files

- cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
- cnf-tests/testsuites/pkg/pods/pods.go
Add context information to returned errors to make it easier
to debug test failures.
> Improve dpdk test debuggability

- OWNERS_ALIASES
update the active contributors
> owners: refresh list of compute contributors

- ztp/gitops-subscriptions/argocd/IssueWithCRGeneratedViaPolicy.md
> Bug 2057566: ztp: add doc explaining mustonlyhave use when modifying list via PGT

- cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
This commit give some time to the second dpdk application(client) to start and send traffic
> cnf-tests: fix dpdk vhost test

- hack/setup-build-index-image.sh
> infra: improve build index image script

- cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
> cnf-tests: support multiple hugepages size

- go.mod
- go.sum
- vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/cluster/cluster.go
- vendor/modules.txt
> vendor: [Bug 2057451] bump sriov package to support the ice driver

- go.mod
- go.sum
- vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/cluster/cluster.go
- vendor/modules.txt
> add ice driver to supported nics

- ztp/gitops-subscriptions/argocd/README.md
Signed-off-by: Leo Ochoa [lochoa@redhat.com](mailto:lochoa@redhat.com)
> ztp: Bump gitops operator version in docs

- cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
This change is needed because `-w` option in dpdk-testpmd was removed.
instead we need to use the new option `-a`
> cnf-tests: Fix dpdk tests

- cnf-tests/testsuites/e2esuite/security/tuning_sriov.go
> cnf-tests: fix tuning tests

- hack/setup-build-index-image.sh
> infra: use a specific podman version to build the index images

- tools/s2i-dpdk/Dockerfile
s2i: bump dpdk version to 21.11
> s2i: bump dpdk version to 21.11

- ztp/extra-manifests-builder/06-kdump/build.sh
- ztp/source-crs/extra-manifest/06-kdump-master.yaml
- ztp/source-crs/extra-manifest/06-kdump-worker.yaml
> Bug 2101356: ztp: Increase kdump size to 512M

- hack/feature-wait.sh
The current timeout can result a wait of ~5 hours if one of the validation tests is failing.
In a working run on BM the max time is takes for all the CNF features to be ready is 50 minutes.
We can reduce the timeout to 90 minutes and allow setting the timeout variable.
> infra: Improve feature-wait timeout

- cnf-tests/testsuites/e2esuite/security/tuning_sriov.go
> Bug 2101812: cnf-tests: fix tuning sriov skip on discovery mode

- ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/common-ranGen.yaml
- ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-1-ranGen.yaml
- ztp/source-crs/BareMetalEventRelaySubscription.yaml
- ztp/source-crs/BareMetalEventRelaySubscriptionNS.yaml
- ztp/source-crs/BareMetalEventRelaySubscriptionOperGroup.yaml
- ztp/source-crs/HardwareEvent.yaml
cherry-picked from https://github.com/openshift-kni/cnf-features-deploy/pull/1171
Signed-off-by: Jack Ding <jackding@gmail.com>
> ztp: rename Bare Metal Event Relay feature

- cnf-tests/testsuites/e2esuite/bond/bond.go
- cnf-tests/testsuites/e2esuite/bond/bond_sriov.go
- cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
- cnf-tests/testsuites/e2esuite/vrf/vrf.go
- cnf-tests/testsuites/e2esuite/vrf/vrf_sriov.go
- cnf-tests/testsuites/pkg/namespaces/namespaces.go
- cnf-tests/testsuites/pkg/networks/sriov.go
Manual backport of
- https://github.com/openshift-kni/cnf-features-deploy/pull/1207
> [release-4.10] fix [sriov] Bond CNI integration bond cni over sriov test

- cnf-tests/TESTLIST.md
- cnf-tests/docgen/e2e.json
- cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
- cnf-tests/testsuites/e2esuite/gatekeeper/gatekeeper.go
- cnf-tests/testsuites/e2esuite/s2i/s2i.go
- cnf-tests/testsuites/pkg/namespaces/namespaces.go
- cnf-tests/testsuites/pkg/pods/pods.go
> cnf-tests: Fix PSA and S2I filter

- cnf-tests/testsuites/pkg/namespaces/namespaces.go
- cnf-tests/testsuites/pkg/utils/reporter.go
- feature-configs/ci/metallb/operator_subscription.yaml
- feature-configs/deploy/metallb/operator_namespace.yaml
- feature-configs/deploy/metallb/operator_operatorgroup.yaml
- feature-configs/deploy/metallb/operator_subscription.yaml
- hack/common.sh
Adding MetalLB namespace for reporter to grab MetalLB logs as well.
> cnf-tests: reporter: Grab MetalLB logs

- hack/setup-build-index-image.sh
We were not increasing the number of iterations, causing an infinite loop.
> infra: Fix wait for build index container loop

- feature-configs/deploy/fec/kustomization.yaml
- feature-configs/deploy/fec/mc-worker.yaml
> Bug 2008689: deploy a MC to enable iommu when fec is requested

- ztp/policygenerator-kustomize-plugin/README.md
- ztp/policygenerator-kustomize-plugin/kustomization.yaml
- ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-2-ranGen.yaml
- ztp/source-crs/HardwareEvent.yaml
- ztp/source-crs/PtpOperatorConfigForEvent.yaml
Signed-off-by: Jack Ding <jackding@gmail.com>
> ztp: support HTTP transport for Cloud Event Proxy

- ztp/gitops-subscriptions/argocd/deployment/policies-app-project.yaml
> OCPBUGS-1898: ztp: Allow Argocd policy app to sync configmap

- cnf-tests/pod-utils/oslat-runner/main.go
We should handle the amount of minimal CPUs for oslat test more carefully.
When HT disabled oslat needs 2 CPUs.
But when HT enabled oslat needs at least 4 CPUs:
One CPU should be used to run oslat's main thread.
The second is the sibling of the first one, which should be excluded from the list of the tested CPUs,
Because it might cause to false spikes (noisy-neighbor issue).
The third one is the actual CPU to be tested, but due to SMT alignment restriction we need its sibling too.
Four in total.
> Bug 2051443: cnf-tests: verify minimal CPUs requirement for oslat test

- openshift-ci/Dockerfile.tools
Working to fix CI failures. Many thanks to @fromanirh for the fix.  
> infra: Pin packages for go version dependency

- ztp/source-crs/HardwareEvent.yaml
- ztp/source-crs/PtpOperatorConfigForEvent.yaml
Signed-off-by: Jack Ding <jackding@gmail.com>
> ztp: set AMQP as default transport type

- tools/s2i-dpdk/Dockerfile
> s2i: update python version to support meson

- hack/setup-build-index-image.sh
This commit remove the unsupported file from the bundle folder of SRO
> infra: Fix SRO deployment

- tools/s2i-dpdk/Dockerfile
> s2i: [release-4.10] fix the dpdk s2i container file

- hack/common.sh
> infra: update the NFD manifest version

- cnf-tests/pod-utils/cyclictest-runner/main.go
- cnf-tests/pod-utils/oslat-runner/main.go
> cnf-tests: call klog.Infof function

- feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-grandmaster.yaml
- feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-slave.yaml
- feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml
- feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml
- ztp/policygenerator/testData/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml
- ztp/source-crs/PtpConfigMaster.yaml
- ztp/source-crs/PtpConfigSlave.yaml
- ztp/source-crs/PtpConfigSlaveCvl.yaml
> ztp: OCPBUGS-2336: Set dataset_comparison to G.8275.x

- feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-boundary.yaml
- feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-grandmaster.yaml
- feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-slave.yaml
- feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-boundary.yaml
- feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml
- feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml
- ztp/policygenerator/testData/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml
- ztp/source-crs/PtpConfigBoundary.yaml
- ztp/source-crs/PtpConfigMaster.yaml
- ztp/source-crs/PtpConfigSlave.yaml
- ztp/source-crs/PtpConfigSlaveCvl.yaml
/hold
Don't merge until https://github.com/openshift-kni/cnf-features-deploy/pull/1318 merges
> ztp: OCPBUGS-4406: Update PTP configs to match reference

- hack/run-functests.sh
> infra: revert "cnf-tests: Filter tests by features suites"

- hack/setup-build-index-image.sh
> [release-4.11] infra: Fix SRO deployment

- OWNERS_ALIASES
> update aliases 20230109

- hack/run-functests.sh
> cnf-tests: Add option for custom GINKGO_PARAMS for tests

- openshift-ci/Dockerfile.tools
Signed-off-by: Bart Wensley <bwensley@redhat.com>
> infra: Update openshift-ci base image to fedora 37

- OWNERS_ALIASES
Signed-off-by: Bart Wensley <bwensley@redhat.com>
> Add bartwensley to cnf-features-reviewers

- cnf-tests/Dockerfile
- cnf-tests/Dockerfile.openshift
- go.mod
- openshift-ci/Dockerfile.tools
> infra: bump golang to 1.19 on openshift-ci image

- ztp/gitops-subscriptions/argocd/deployment/argocd-openshift-gitops-patch.json
- ztp/gitops-subscriptions/argocd/deployment/policies-app-project.yaml
Reverts openshift-kni/cnf-features-deploy#1404
> Revert "Add ACM policyGenerator to ArgoCD ZTP workflow"

- ztp/source-crs/PtpConfigGmWpc.yaml
ptp config to support ts2phc implementation
> ztp: Add ts2phc configuration to new ptpconfig 

- ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
- ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
> ztp: Only provide composable openshift examples for SNO clusters

- OWNERS_ALIASES
Add Sharat Akhoury to ZTP and RAN review / approval list.
Signed-off-by: Sharat Akhoury <sakhoury@redhat.com>
/assign @lack @imiller0
> owners: Add Sharat Akhoury to review and approval list for ZTP and RAN

- ztp/gitops-subscriptions/argocd/README.md
- ztp/gitops-subscriptions/argocd/deployment/disable-cluster-proxy-addon.json
/cc @Missxiaoguo 
/cc @imiller0
> OCPBUGS-7652: ztp: add patch in deployment directory to remove cluster-proxy-addon

- ztp/ran-crd/site-config-crd.yaml
- ztp/siteconfig-generator/siteConfig/clusterCRs.go
- ztp/siteconfig-generator/siteConfig/siteConfig.go
Since for Telco ZTP we're targeting e2e deployments with no user action, I just set the default value to false.
Signed-off-by: Leo Ochoa [lochoa@redhat.com](mailto:lochoa@redhat.com)
> Add a holdInstallation flag to SiteConfig

- ztp/siteconfig-generator/siteConfig/siteConfig.go
- ztp/siteconfig-generator/siteConfig/siteConfig_test.go
> OCPBUGS-9272: ztp: validate disk partitioning is applied only for SNO

- ztp/source-crs/PerformanceProfile.yaml
Signed-off-by: Brent Rowsell <browsell@redhat.com>
> ztp: OCPBUGS-8718: Unload idrma driver for DU profile

- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
- ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
- ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
- ztp/source-crs/optional-extra-manifest/enable-crun-master.yaml
- ztp/source-crs/optional-extra-manifest/enable-crun-worker.yaml
Jira: [CNF-7823](https://issues.redhat.com/browse/CNF-7823)
> ztp: config crun as the default container runtime for 4.13+

- README.md
- ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/example-multinode-site.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-validator-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-validator-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-validator-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
- ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
- ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
> ztp: add latest label for policies in master branch.

- ztp/policygenerator/policyGen/policyBuilder.go
- ztp/policygenerator/policyGen/policyBuilderOverlay_test.go
- ztp/policygenerator/utils/filesHandler.go
source crs are looked first at git repo, then inside the ztp container
/cc @serngawy @imiller0
> ztp: CNF-7798: git-first-search-path-for-ztp

- ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
- ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/common-ranGen.yaml
This update reorders the subscriptions-policy to reflect the dependency order.
> ztp: CNF-7722 Fix ordering of common-subscriptions policies

- feature-configs/deploy/sriov/01-sriov-namespace.yaml
- ztp/policygenerator/testData/TestNamespace/sourcePolicies/TestNamespace.yaml
- ztp/policygenerator/testData/TestUnwrappedNamespace/sourcePolicies/TestUnwrappedNamespace.yaml
- features: remove `run-level: 1` from sriov
- ztp: remove `run-level: 1` from ztp
> remove runlevel 1

- ztp/policygenerator-kustomize-plugin/README.md
- ztp/source-crs/ClusterLogCatSource.yaml
- ztp/source-crs/DefaultCatsrc.yaml
- ztp/source-crs/PaoSubscriptionCatalogSource.yaml
- ztp/source-crs/PtpCatSource.yaml
- ztp/source-crs/SriovCatSource.yaml
- ztp/source-crs/StorageCatSource.yaml
Update DefaultCatSrc with Status and add depreciation warning in rest of the CatalogueSource (we are meant to use just the  one)
/cc @imiller0 
/cc @jc-rh
> CNF-8518: ztp: Update DefaultCatSrc with Status and add depreciation warning in the rest of the cat sources

- ztp/source-crs/PerformanceProfile.yaml
should be help with must-gather
/cc @imiller0
> CNF-8413: ztp: add annotation in source-cr pp to assist with search

- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-validator-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-validator-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml
- ztp/policygenerator-kustomize-plugin/kustomization.yaml
- ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/example-group-du-sno-validator-ranGen.yaml
- reduce compliant interval for validators
- patch validator PGTs to add soaking annotation
> [release-4.12] OCPBUGS-14297: ztp: Add soaking annotation to validator PGTs

- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
- ztp/source-crs/DisableOLMPprof.yaml
OLM collect-profiles Cron job is triggered every 15min to collect performance profiles, which causes huge CPU bursts. Add a source cr to disable it via PGT.
/cc @lack @imiller0
> OCPBUGS-14511: ztp: disable OLM pprof collection on SNO

- ztp/policygenerator-kustomize-plugin/Makefile
Reverts openshift-kni/cnf-features-deploy#1531
> Revert "ztp: copy source-crs in current working directory to mimic git behavior in Makefile"

- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
- ztp/source-crs/DisableOLMPprof.yaml
This is a manual cherry-pick of #1548.
> [release-4.12] OCPBUGS-15912: ztp: disable OLM pprof collection on SNO

- ztp/siteconfig-generator/siteConfig/siteConfigHelper.go
- ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml
- ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
- ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml
- deprecation warning added for extraManifestPath in Siteconfig
/assign @imiller0 @serngawy @eggfoobar
> CNF-8851: ztp: Create warning for deprecated field: extraManifestPath

- feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-boundary.yaml
- feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-grandmaster.yaml
- feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-slave.yaml
- feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-boundary.yaml
- feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml
- feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml
- ztp/policygenerator/testData/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml
- ztp/source-crs/PtpConfigBoundary.yaml
- ztp/source-crs/PtpConfigMaster.yaml
- ztp/source-crs/PtpConfigSlave.yaml
- ztp/source-crs/PtpConfigSlaveCvl.yaml
/jira cherrypick OCPBUGS-14300
> OCPBUGS-16362: ztp: cherry-pick reference config changes to 4.12

- ztp/source-crs/PerformanceProfile.yaml
- ztp/source-crs/SriovFecClusterConfig.yaml
this commit also contains the needed parameters for the vfio driver
> ztp: [release 4.13] update fec config to use vfio-pci

- ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
- ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
- ztp/siteconfig-generator/siteConfig/testdata/ConfigMapOverride.yaml
SiteConfig crTemplates override does not work with a ConfigMap CR
> OCPBUGS-7092 SiteConfig crTemplates override does not work with a ConfigMap CR

- ztp/source-crs/ClusterLogForwarder.yaml
- ztp/source-crs/ClusterLogging.yaml
Signed-off-by: Brent Rowsell <browsell@redhat.com>
> ztp: Update reference CRs to use vector

- ztp/siteconfig-generator/siteConfig/siteConfigHelper.go
- ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml
- ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
> fix: update wording to correctly reflect version 4.14

- ztp/source-crs/SriovOperatorConfig-SetSelector.yaml
- ztp/source-crs/SriovOperatorConfig.yaml
Signed-off-by: Brent Rowsell <browsell@redhat.com>
Reduce default SRIOV log verbosity in the DU profile
> ztp: OCPBUGS-18151: Reduce SRIOV log verbosity

- cnf-tests/Dockerfile
- cnf-tests/Dockerfile.openshift
- go.mod
- openshift-ci/Dockerfile.tools
- ztp/resource-generator/Containerfile
This PR bumps the cnf-tests and ztp to go v1.20
> Bump cnf-features-deploy to go 1.20

- cnf-tests/testsuites/pkg/machineconfigpool/machineconfigpool.go
When `ApplyKubeletConfigToNode` moves the node back to the previous role, we have to wait for the relative MachineConfigPool to update the node. Since the function has no clue about which MCP the node belonged to before applying the KubeletConfig, the best strategy is to wait for at least one MCP to start updating and then wait for the whole cluster (every MCP) to be stable.
Before these changes, the test case that runs after the cleanup function is likely to fail, as it found a cluster in a non-stable state.
Introduce utility functions `WaitForAllMCPStable()` and `WaitForAtLeastOneMCPUpdating()` to query the state of the cluster without specifying a single MCP.
Failing job example: [HTML Report](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-opensh …
> cnf-tests: fix `ApplyKubeletConfigToNode` cleanup

- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-validator-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-validator-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml
- ztp/policygenerator-kustomize-plugin/kustomization.yaml
- ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/example-group-du-sno-validator-ranGen.yaml
- reduce compliant interval for validators
- patch validator PGTs to add soaking annotation
> [release-4.13] OCPBUGS-18290: ztp: Add soaking annotation to validator PGTs

- ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
This is required for "NodeTuning" and other operator operations.
> OCPBUGS-22812: ztp: Enable newly required OperatorLifecycleManager capability for 4.15

- ztp/resource-generator/Containerfile
- updated the build and base image to rhel9
- locally generated  CRS using siteconfig and policygenTemplate binary from the image
> ztp: CNF-10088 container image updated to rhel9

- ztp/resource-generator/Containerfile
- Note updated to point towards new midstream location
- Instruction added to make changes in the midstream
- Warning added for any version update
> ztp: Notes added to reflect on new midstream info in the containerFile

- ztp/source-crs/ClusterLogging.yaml
> ztp: OCPBUGS-24657: fix manifest for vector

- cnf-tests/testsuites/e2esuite/vrf/vrf.go
VRF negative tests may fail after deleting a pod, as happened in
the following case:
```
STEP: Run client/server ICMP negative connectivity tests @ 12/05/23 16:49:55.92
[FAILED] in [It] - /home/apanatto/dev/github.com/openshift-kni/cnf-features-deploy/cnf-tests/testsuites/e2esuite/vrf/vrf.go:248 @ 12/05/23 16:50:02.622
<< Timeline
[FAILED] Expected ping error, but output was: {ping: Warning: source address might be selected on device other than blue.
PING 10.255.255.2 (10.255.255.2) from 10.255.255.1 blue: 56(84) bytes of data.
64 bytes from 10.255.255.2: icmp_seq=1 ttl=64 time=0.058 ms
--- 10.255.255.2 ping statistics ---
5 packets transmitted, 1 received, 80% packet loss, time 4098ms
rtt min/avg/max/mdev = 0.058/0.058/0.058/0.000 ms
%!s(int=0) %!s(bytes.readOp=0)}
Expected an error to …
```
> OCPBUGS-24435: Fix for `VRF integration Integration: SRIOV, IPAM: static, Interfaces: 1, Scheme: 2 Pods 2 VRFs OCP Primary network overlap`

- ztp/source-crs/ImageBasedUpgrade.yaml
Add IBU CR to ztp/source-crs and set the stage to Idle.
/cc @imiller0 @Missxiaoguo @donpenney
> CNF-9624: Add IBU CR to ztp/source-crs

- Makefile
- cnf-tests/testsuites/pkg/j2html/j2html.go
- hack/common.sh
- hack/run-functests.sh
parse results from Junit XML to HTML to see the results in more human-friendly way.
> infra: Parse results to HTML

- ztp/source-crs/PtpConfigDualCardGmWpc.yaml
Remove duplicate lines and change the delay to a more realistic value
> [release-4.15] ztp: update SMA cable delay on PtpConfigDualCardGmWpc

- ztp/source-crs/PtpConfigDualCardGmWpc.yaml
Remove duplicate lines and change the delay to a more realistic value
> ztp: update SMA cable delay on PtpConfigDualCardGmWpc

- ztp/extra-manifests-builder/99-sync-time-once/build.sh
- ztp/source-crs/extra-manifest/99-sync-time-once-master.yaml
- ztp/source-crs/extra-manifest/99-sync-time-once-worker.yaml
This is a manual cherry-pick combination of
https://github.com/openshift-kni/cnf-features-deploy/pull/1698 and
https://github.com/openshift-kni/cnf-features-deploy/pull/1702
/assign @imiller0
> [release-4.14] ztp: OCPBUGS-23298: fix chrony contention

- ztp/source-crs/SriovOperatorConfig-SetSelector.yaml
- ztp/source-crs/SriovOperatorConfig.yaml
Signed-off-by: Brent Rowsell <browsell@redhat.com>
> ztp: Disable sriov operator injector and webhook pods

- ztp/source-crs/PtpConfigForHA.yaml
4.16 : ptp operator enables HA via ptpconfig.
This PR adds config required to enable HA
> ztp: ptp add ptpconfig for High Availability

- ztp/gitops-subscriptions/argocd/WorkerNodeDeletion.md
- ztp/ran-crd/site-config-crd.yaml
- ztp/siteconfig-generator/siteConfig/siteConfig.go
- ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
- ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
- ztp/siteconfig-generator/siteConfig/siteConfigHelper.go
- ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
This is a manual cherry-pick of https://github.com/openshift-kni/cnf-features-deploy/pull/1577
/cc @sabbir-47 @imiller0
> [release-4.14] CNF-12187: Support node deletion using ZTP

- ztp/gitops-subscriptions/argocd/example/image-based-upgrades/README.md
- ztp/source-crs/ibu/PlatformBackupRestore.yaml
/cc @browsell @imiller0 @sabbir-47
> OCPBUGS-32771: ztp: update the default PlatformBackupRestore CR

- Makefile
- cnf-tests/testsuites/pkg/j2html/j2html.go
- hack/common.sh
- hack/run-functests.sh
This is a cherry-pick of #1750
> [release-4.14] tools: Add HTML converting to code and make true by default

- cnf-tests/testsuites/e2esuite/security/tuning.go
In case of failure, subsequent retries of the allowlist test fail because the macvlan is already present. This changes ensure that the macvlan nad is deleted.
> cnf-tests: Delete macvlan nad to retry allowlist test

- ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-ranGen.yaml
- ztp/source-crs/TunedPerformancePatch.yaml
[OCPBUGS-33527](https://issues.redhat.com/browse/OCPBUGS-33527)
Update ice-dplls tuning to SCHED_FIFO 10
> OCPBUGS-33527: ztp: Update ice-dplls tuning to SCHED_FIFO 10

- ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
Description:
- update the ZTP SNO example to include the newly required Ingress capability
- related PRs: 
* https://github.com/openshift/installer/pull/8502
* https://github.com/openshift/installer/pull/8525
* https://github.com/openshift/installer/pull/8528
> ztp: OCPBUGS-35225 - update ZTP Example with Ingress Capability

- ztp/gitops-subscriptions/argocd/deployment/policies-app-project.yaml
Reverts openshift-kni/cnf-features-deploy#1934 to fix the commit message
> Revert "Add ClusterImageSet CR in the whitelist of policies-app-project" to fix commit message

- ztp/gitops-subscriptions/argocd/deployment/policies-app-project.yaml
Reverts openshift-kni/cnf-features-deploy#1936 to correct the git message.
> Add ClusterImageSet CR in the whitelist of policies-app-project

- ztp/gitops-subscriptions/argocd/AcceleratedZtp.md
Add accelerated ZTP documentation
/cc @sabbir-47 @imiller0
>  CNF-11528: ztp: Add accelerated ZTP doc

- ztp/source-crs/PtpConfigDualCardGmWpc.yaml
- ztp/source-crs/PtpConfigGmWpc.yaml
This fixes previous out-of bounds number
/cc @aneeshkp @jzding @josephdrichard @nishant-parekh
> OCPBUGS-37118: ztp: fix NAV-TIMELS reporting period

- ztp/kube-compare-reference/required/sriov-operator/SriovOperatorConfigForSNO.yaml
sync the file with the one in source-crs to add disableDrain: true
> add disableDrain: true in SriovOperatorConfigForSNO.yaml

- ztp/kube-compare-reference/metadata.yaml
ignore more annotations for sriovnetwork CR and DisableOLMPprof CM
> ignore more annotations

- ztp/kube-compare-reference/required/sriov-operator/SriovNetworkNodePolicy.yaml
> OCPBUGS-38945: ztp: Reference: Allow SriovNetworkNodePolicy to be fully customizable

- ztp/kube-compare-reference/metadata.yaml
- **ztp: Reference: Allow merged DisableSnoNetworkDiag object matching**
- **ztp: Reference: Allow merged ImageRegistryConfig object matching**
> OCPBUGS-39093: Reference: Allow merged object validation in more cases

- ztp/kube-compare-reference/metadata.yaml
- ztp/kube-compare-reference/optional/local-storage-operator/StorageNS.yaml
- ztp/kube-compare-reference/optional/sriov-fec-operator/AcceleratorsNS.yaml
- ztp/kube-compare-reference/optional/storage/StorageLVMSubscriptionNS.yaml
- ztp/kube-compare-reference/optional/storage/StoragePV.yaml
- ztp/kube-compare-reference/optional_labels.tmpl
- ztp/kube-compare-reference/required/cluster-logging/ClusterLogNS.yaml
- ztp/kube-compare-reference/required/lca/LcaSubscriptionNS.yaml
- ztp/kube-compare-reference/required/ptp-operator/PtpSubscriptionNS.yaml
- ztp/kube-compare-reference/required/sriov-operator/SriovSubscriptionNS.yaml
> OCPBUGS-39093: reference: Enhance namespace templates to allow optional pod-security.kubernetes.io labels

- ztp/kube-compare-reference/metadata.yaml
Should have been part of !2037
> ztp: reference: Add unordered_list.tmpl to metadata.yaml

- ztp/kube-compare-reference/unordered_list.tmpl
- **ztp: reference: Add unordered_list.tmpl to metadata.yaml**
- **ztp: reference: Fix unordered list template**
> Reference: Fix unordered list template

- ztp/kube-compare-reference/required/cluster-logging/ClusterLogForwarder.yaml
- ztp/kube-compare-reference/required/cluster-logging/ClusterLogSubscription.yaml
- ztp/source-crs/ClusterLogSubscription.yaml
- Fix channel name to match what should be the final version in the catalog
- Update kube-compare references based on test result feedback
> ztp: CNF-14458: Follow up fixes for channel name & kubecompare-references

- ztp/kube-compare-reference/ClusterVersionOperator.yaml
- ztp/kube-compare-reference/compare_ignore
- ztp/kube-compare-reference/metadata.yaml
- ztp/kube-compare-reference/version_match.tmpl
> CNF-15048: Enforce cluster version for this reference to be 4.17

- ztp/kube-compare-reference/ClusterVersionOperator.yaml
- ztp/kube-compare-reference/compare_ignore
- ztp/kube-compare-reference/metadata.yaml
- ztp/kube-compare-reference/version_match.tmpl
> CNF-15048: Enforce cluster version for this reference to be 4.16

- ztp/tools/pgt2acmpg/.gitignore
- ztp/tools/pgt2acmpg/scripts/build-acmpg-plugin.sh
- Cherry pick master PR
- Update ACM branch to match oldest supported z stream
> [release-4.16] Backport CNF-14991: Fix instability in policy-generator-plugin usage

- ztp/tools/pgt2acmpg/.gitignore
- ztp/tools/pgt2acmpg/scripts/build-acmpg-plugin.sh
- Cherry pick master PR
- Update ACM branch to match oldest supported z stream
> [release-4.17] Backport CNF-14991: Fix instability in policy-generator-plugin usage

- ztp/gitops-subscriptions/argocd/README.md
- ztp/gitops-subscriptions/argocd/deployment/allow-acm-managedcluster-control.json
- ztp/gitops-subscriptions/argocd/deployment/clusters-app.yaml
- ztp/gitops-subscriptions/argocd/example/siteconfig/KlusterletAddonConfigOverride.yaml
- ztp/siteconfig-generator/siteConfig/clusterCRs.go
- ztp/siteconfig-generator/siteConfig/siteConfig.go
- ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
- ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
- ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingArgocdAnnotation.yaml
- ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingMetadata.yaml
- ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingMetadataAnnotations.yaml
- ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-NotTemplated.yaml
- ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride.yaml
- ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml
- ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml
- ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml
- ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
- ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml
- ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml
- ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml
- ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml
- ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
- ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
Manual cherry pick of https://github.com/openshift-kni/cnf-features-deploy/pull/2005
/cc @sabbir-47
> [release-4.14] ztp: remove unsupported KlusterletAddonConfig clusterLabels and update managecluster CR to include cloud and vendor label

- ztp/gitops-subscriptions/argocd/deployment/policies-app.yaml
Not important, but lint fails and brakes me other CI
> ztp: fix lint policies-app.yaml

- ztp/kube-compare-reference/metadata.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
- ztp/source-crs/PtpConfigBoundary.yaml
- ztp/source-crs/PtpConfigBoundaryForEvent.yaml
- ztp/source-crs/PtpConfigDualCardGmWpc.yaml
- ztp/source-crs/PtpConfigGmWpc.yaml
> CNF-13528: ztp: reference: Use capturegroupInlineDiff for PTPConfig

- cnf-tests/testsuites/e2esuite/security/tuning.go
Since the tests are re-attempted on failure, we should cleanup the NADs each time to not get an "Already exists" error on the retries. Also, added a missing Expect(err).
> cnf-tests: delete NADs between tuning tests

- ztp/kube-compare-reference/metadata.yaml
> CNF-15582: ztp: reference: Add description text to metadata.yaml

- ztp/kube-compare-reference/metadata.yaml
> CNF-15583: Add description text to metadata.yaml [4.17 backport]

- ztp/kube-compare-reference/metadata.yaml
> CNF-15584: Add description text to metadata.yaml [4.16 backport]

- ztp/kube-compare-reference/metadata.yaml
> CNF-15585: Add description text to metadata.yaml [4.15 backport]

- ztp/kube-compare-reference/metadata.yaml
> CNF-15586: Add description text to metadata.yaml [4.14 backport]

- ztp/gitops-subscriptions/Makefile
- ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-sno-ranGen-templated.yaml
- ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/configMaps/group-zones-configmap.yaml
- ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/schema.openapi
- ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/configMaps/group-zones-configmap.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-sno-ranGen-templated.yaml
- ztp/kube-compare-reference/default_value.yaml
- ztp/kube-compare-reference/required/cluster-logging/ClusterLogForwarder.yaml
- ztp/source-crs/ClusterLogForwarder.yaml
- ztp/tools/pgt2acmpg/test/newptpconfig-schema.json
Description:
- new CluserLogForwarder update to be compatible with templated and non templated PGT and ACM PG.
* validated scenarios have been locked in in this source-cr
- update all the dependencies:
* acmpgtopgt
* ACM PG, PGT and ConfigMap examples
* kube-compare required and default values
> ztp: OCPBUGS-44518: ClusterLogForwarder source-cr update

- ztp/kube-compare-reference/default_value.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
- ztp/source-crs/PtpConfigDualCardGmWpc.yaml
- ztp/source-crs/PtpConfigGmWpc.yaml
> OCPBUGS-48343: Update WPC GM e180 pin example to be more user-friendly

- ztp/kube-compare-reference/required/cluster-logging/ClusterLogNS.yaml
- ztp/source-crs/ClusterLogNS.yaml
/cc @imiller0 @lack @sabbir-47
> ztp: OCPBUGS-48088: Add monitoring label for openshift-logging ns

- ztp/kube-compare-reference/default_value.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
> OCPBUGS-47784: ztp: reference: Enable user customization of PTP priority1, priority2, and domainNumber fields

- ztp/kube-compare-reference/default_value.yaml
- ztp/kube-compare-reference/metadata.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHA.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHAForEvent.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigMaster.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlave.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveForEvent.yaml
> OCPBUGS-49793: ztp: reference: Enable user customization of PTP priority1, priority2, and domainNumber [4.18]

- ztp/kube-compare-reference/default_value.yaml
- ztp/kube-compare-reference/required/sriov-operator/SriovOperatorConfig.yaml
- ztp/kube-compare-reference/required/sriov-operator/SriovOperatorConfigForSNO.yaml
- ztp/source-crs/SriovOperatorConfigForSNO.yaml
> OCPBUGS-44271: ztp: reference: Make SriovOperatorConfig optional fields truly optional

- cnf-tests/Dockerfile.openshift
- cnf-tests/testsuites/e2esuite/security/tuning.go
- cnf-tests/testsuites/pkg/machineconfigpool/machineconfigpool.go
Backport of:
- https://github.com/openshift-kni/cnf-features-deploy/pull/2110
- https://github.com/openshift-kni/cnf-features-deploy/pull/2120
> [release-4.17] CNF-15765: CI fixes

- ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-example-sno-site.yaml
- ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml
- ztp/source-crs/OadpBackupStorageLocationStatus.yaml
Add the metadata name in the OadpBackupStorageLocationStatus source cr. This is to make it work with both ZTP PG and ACM PG.
/cc @jc-rh
> ztp: update OadpBackupStorageLocationStatus source cr with metadata name

- ztp/kube-compare-reference/default_value.yaml
- ztp/kube-compare-reference/metadata.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHA.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHAForEvent.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigMaster.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlave.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveForEvent.yaml
> OCPBUGS-49815: ztp: reference: Enable user customization of PTP priority2 and domainNumber fields

- OWNERS_ALIASES
> owners: expand konflux reviewers and approvers (.tekton dir)

- .tekton/OWNERS
We don't want to wait for approval/review from other folks.
Marked as a draft as it depends on: https://github.com/openshift-kni/cnf-features-deploy/pull/2255 being merged first.
Cc: @shajmakh @yanirq
> infra: introduce reviewers for Konflux (.tekton dir)

- .githooks/check-skipped-files.sh
- .githooks/commit-msg
- hack/verify-commits.sh
This is a completion of the previous intend here: https://github.com/openshift-kni/cnf-features-deploy/pull/2238
> infra: skip .tekton checks for staging files and upstream commits

- cnf-tests/entrypoint/test-run.sh
- hack/run-functests.sh
Adapt https://github.com/openshift/cluster-node-tuning-operator/pull/857.
> cnf-tests: omit LatencyTestRun env variable

- .githooks/components.sh
This changes allow automated commits from konflux like this:
- https://github.com/openshift-kni/cnf-features-deploy/pull/2249
to pass the `ci/prow/ci` job
> infra: add `chore(deps)` to the list of components

- ztp/gitops-subscriptions/argocd/deployment/policies-app-project.yaml
PR#1937 was incorrectly sent to release-4.16 directly, this is a PR for master branch.
> ztp: Add ClusterImageSet CR in the whitelist of policies-app-project

- ztp/kube-compare-reference/default_value.yaml
- ztp/kube-compare-reference/required/sriov-operator/SriovOperatorConfig.yaml
/jira cherry-pick OCPBUGS-52433
> OCPBUGS-52877: ztp: reference: Make SriovOperatorConfig optional fields truly optional

- ztp/kube-compare-reference/default_value.yaml
- ztp/kube-compare-reference/metadata.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigThreeCardGmWpc.yaml
- ztp/source-crs/PtpConfigThreeCardGmWpc.yaml
> CNF-16811: ztp: Add an example PtpConfig and reference template for the T-GM 3-card WPC

- ztp/kube-compare-reference/ClusterVersionOperator.yaml
> ztp: reference: bump cluster-compare version check to 4.19

- ztp/kube-compare-reference/default_value.yaml
- ztp/kube-compare-reference/metadata.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigThreeCardGmWpc.yaml
- ztp/source-crs/PtpConfigThreeCardGmWpc.yaml
> OCPBUGS-53275: ztp: Add an example PtpConfig and reference template for the T-GM 3-card WPC

- ztp/kube-compare-reference/default_value.yaml
- ztp/kube-compare-reference/metadata.yaml
- ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualFollower.yaml
- ztp/source-crs/PtpConfigDualFollower.yaml
Adding PTP Dual Follower configuration templates
> ztp: add dual-follower ptpconfig example

- ztp/policygenerator/policyGen/policyBuilder_test.go
- ztp/policygenerator/policyGen/policyHelper.go
- ztp/policygenerator/utils/utils.go
This will add `watch` as an accepted value for evaluation interval of policy in PGT.
/cc @sabbir-47 @irinamihai
> OCPBUGS-54381: ztp: Allow watch for policy evaluation intervals in PGT 

- ztp/kube-compare-reference/default_value.yaml
- ztp/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml
> OCPBUGS-54312: ztp: reference: Enable users to set PerformanceProfile perPodPowerManagement

- ztp/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml
> OCPBUGS-54194: ztp: reference: Allow PerformanceProfile kernelPageSize to optionally be set

- renovate.json
This PR contains fixes from a sanity check for renovate bot.
```
-> npx --yes --package renovate -- renovate-config-validator
INFO: Validating renovate.json
INFO: Config validated successfully
```
> infra: validated renovate config

- .tekton/cnf-tests-4-19-pull-request.yaml
- .tekton/cnf-tests-4-19-push.yaml
- cnf-tests/.konflux/Dockerfile
- cnf-tests/.konflux/rpms.in.yaml
As per https://konflux.pages.redhat.com/docs/users/getting-started/components-applications.html#other-configurations-to-make-in-your-pipelines
> cnf-tests: k5x: build source image

- .tekton/ztp-site-generate-4-19-pull-request.yaml
- .tekton/ztp-site-generate-4-19-push.yaml
This MR updates ztp-site-generate konflux to Trusted Artifacts Pipeline
> ztp: Update resource-generator to Trusted Artifacts Pipeline

- .githooks/commit-msg
- hack/verify-commits.sh
This PR adds the upstream commit check to restrict updates to ZTP folders.
> infra: CNF-16868: verify and restrict ztp commits

- .tekton/ztp-site-generate-4-19-pull-request.yaml
- .tekton/ztp-site-generate-4-19-push.yaml
- ztp/resource-generator/.konflux/rpms.lock.yaml
Fixes in ztp-site-generate for passing konflux conforma checks
> ztp: resource-generator konflux conforma

- cnf-tests/.konflux/Dockerfile
> cnf-tests: konflux dockerfile updates

- cnf-tests/.konflux/Dockerfile
- cnf-tests/.konflux/rpms.in.yaml
- cnf-tests/.konflux/rpms.lock.yaml
- cnf-tests/Dockerfile.openshift
The binary is useful for testing so add it.
> cnf-tests: add `findutils` binary

- .tekton/ztp-site-generate-4-19-pull-request.yaml
- .tekton/ztp-site-generate-4-19-push.yaml
- build-args-konflux.conf
- ztp/.konflux/OWNERS
- ztp/.konflux/build-args-konflux.conf
- ztp/resource-generator/.konflux/OWNERS
- ztp/resource-generator/.konflux/redhat.repo
- ztp/resource-generator/.konflux/rpms.in.yaml
- ztp/resource-generator/.konflux/rpms.lock.yaml
This PR backports konflux changes to release 4.19
cc: @rauhersu @fontivan
> tekton: backport konflux to release 4.19

- .tekton/ztp-site-generate-4-20-pull-request.yaml
- .tekton/ztp-site-generate-4-20-push.yaml
This PR adds service account to ztp site generate
> tekton: update service account in ztp 4.20

- cnf-tests/.konflux/OWNERS
Specify reviewers and approvers for konflux related updates.
> cnf-tests: k5x: add OWNERS file

- .tekton/cnf-tests-4-18-pull-request.yaml
- .tekton/cnf-tests-4-18-push.yaml
- cnf-tests/.konflux/Dockerfile
- cnf-tests/.konflux/OWNERS
- cnf-tests/.konflux/README.md
- cnf-tests/.konflux/rpms.in.yaml
- cnf-tests/.konflux/rpms.lock.yaml
* Add tekton files to configure pipeline jobs
* Add konflux dedicated Dockerfile and RPM lockfile
* Add owners for tekton files
> cnf-tests: konflux 4.18 onboarding

- .tekton/cnf-tests-4-19-pull-request.yaml
- .tekton/cnf-tests-4-19-push.yaml
- cnf-tests/.konflux/Dockerfile
- cnf-tests/.konflux/rpms.in.yaml
- cnf-tests/.konflux/rpms.lock.yaml
- cnf-tests/Dockerfile.openshift
Updates backports to 4.19 and target_branch fix. Please see commits for detailed info.
> [release-4.19] cnf-tests konflux backports

- .tekton/ztp-site-generate-4-12-pull-request.yaml
- .tekton/ztp-site-generate-4-12-push.yaml
This PR fixes ZTP tekton branch in release-4.12
> ztp: fix tekton target branch in 4.12

- .tekton/cnf-tests-4-16-pull-request.yaml
- .tekton/cnf-tests-4-16-push.yaml
- cnf-tests/.konflux/Dockerfile
- cnf-tests/.konflux/OWNERS
- cnf-tests/.konflux/README.md
- cnf-tests/.konflux/rpms.in.yaml
- cnf-tests/.konflux/rpms.lock.yaml
* Add tekton files to configure pipeline jobs
* Add konflux dedicated Dockerfile and RPM lockfile
* Add owners for tekton files
> cnf-tests: konflux 4.16 onboarding

- .tekton/cnf-tests-4-19-pull-request.yaml
- .tekton/cnf-tests-4-19-push.yaml
- .tekton/ztp-site-generate-4-19-pull-request.yaml
- .tekton/ztp-site-generate-4-19-push.yaml
Consume lastest digests for tekton tasks.
> chore(deps): update tasks references

- .tekton/cnf-tests-4-16-pull-request.yaml
- .tekton/cnf-tests-4-16-push.yaml
- .tekton/ztp-site-generate-4-16-pull-request.yaml
- .tekton/ztp-site-generate-4-16-push.yaml
This PR updates the on-cel-expression for ztp & cnf-tests to trigger for go.mod changes
> tekton: update on-cel-expression for go.mod [release-4.16]

- .tekton/cnf-tests-4-14-pull-request.yaml
- .tekton/cnf-tests-4-14-push.yaml
- .tekton/ztp-site-generate-4-14-pull-request.yaml
- .tekton/ztp-site-generate-4-14-push.yaml
This PR updates the on-cel-expression for ztp & cnf-tests to trigger for go.mod changes
> tekton: update on-cel-expression for go.mod [release-4.14]

- .tekton/cnf-tests-4-12-pull-request.yaml
- .tekton/cnf-tests-4-12-push.yaml
- .tekton/ztp-site-generate-4-12-pull-request.yaml
- .tekton/ztp-site-generate-4-12-push.yaml
This PR updates the on-cel-expression for ztp & cnf-tests to trigger for go.mod changes
> tekton: update on-cel-expression for go.mod [release-4.12]

- .tekton/cnf-tests-4-18-pull-request.yaml
- .tekton/cnf-tests-4-18-push.yaml
- .tekton/ztp-site-generate-4-18-pull-request.yaml
- .tekton/ztp-site-generate-4-18-push.yaml
This PR updates the on-cel-expression for ztp & cnf-tests to trigger for go.mod changes
> tekton: update on-cel-expression for go.mod [release-4.18]

- cnf-tests/.konflux/rpms.in.yaml
- cnf-tests/.konflux/rpms.lock.yaml
bump rhel8 RPM packages to fix CHI score.
> [release-4.18] cnf-tests: k5x: RPMs bump

- cnf-tests/.konflux/rpms.in.yaml
- cnf-tests/.konflux/rpms.lock.yaml
bump rhel8 RPM packages to fix CHI score.
> [release-4.16] cnf-tests: k5x: RPMs bump

- cnf-tests/.konflux/rpms.in.yaml
- cnf-tests/.konflux/rpms.lock.yaml
bump rhel8 RPM packages to fix CHI score.
> [release-4.14] cnf-tests: k5x: RPMs bump

- ztp/resource-generator/Containerfile
- ztp/tools/siteconfig-converter/README.md
- ztp/tools/siteconfig-converter/main.go
This is needed by siteconfig-converter tool
> ztp: Add siteconfig-generator to ztp-site-generate PATH

- .tekton/cnf-tests-4-17-pull-request.yaml
- .tekton/cnf-tests-4-17-push.yaml
- .tekton/ztp-site-generate-4-17-pull-request.yaml
- .tekton/ztp-site-generate-4-17-push.yaml
> [release-4.17] tekton: task digest updates

- ztp/kube-compare-reference/required/node-tuning-operator/TunedPerformancePatch.yaml
- ztp/source-crs/TunedPerformancePatch.yaml
This PR updates the comment in tuned performance patch, such that the user can understand the recommended configuration for stdkernel performance patch and implement it.
> ztp: comment update for TunedPerformancePatch

- ztp/policygenerator-kustomize-plugin/Makefile
This reverts commit b134f436c39ed4065734c1c676e1c3a4dac622a5.
> Revert "ztp: update policygenerator makefile"

- Makefile
- cnf-tests/Makefile
- ztp/resource-generator/Makefile
- This is a manual backport of https://github.com/openshift-kni/cnf-features-deploy/pull/3006
- A minor git conflict was present in the root project Makefile because it does not have the functtest submodule usage present in newer releases
> [release-4.14] infra: Fix git submodule syncing
